CREATE FUNCTION [dbo].[AI]
(@kol1 NVARCHAR(40),
@KOL2 NVARCHAR(40))
RETURNS TABLE
AS
RETURN ( SELECT     TOP 100 PERCENT dbo.DEED_DTL.HES_M, dbo.DEED_DTL.HES_T, dbo.DEED_HED.DATE_S, dbo.DEED_DTL.N_S, dbo.DEED_DTL.BED, 
                      dbo.DEED_DTL.BES, dbo.DEED_DTL.HES, dbo.DEED_DTL.SHARH, dbo.DEED_DTL.BED - dbo.DEED_DTL.BES AS MAND, 
                      dbo.DEED_DTL.HES_K
FROM         dbo.DEED_DTL INNER JOIN
                      dbo.DEED_HED ON dbo.DEED_DTL.N_S = dbo.DEED_HED.N_S
WHERE     (dbo.DEED_DTL.HES BETWEEN @kol1 AND @KOL2)
ORDER BY dbo.DEED_DTL.HES, dbo.DEED_DTL.HES_M, dbo.DEED_DTL.HES_T, dbo.DEED_HED.DATE_S, dbo.DEED_DTL.BED )
