CREATE FUNCTION [dbo].[AK_MOGO_AVL_KOL]
(@Forms___F_MENU_ANBAR___DT2 BIGINT,
@Forms___F_MENU_ANBAR___MANBAR NVARCHAR(10))
RETURNS TABLE
AS
RETURN ( SELECT     CODE, SUM(dbo.UIIF(MEG, N'=', 0, NULL, MEG)) AS SMEGH, SUM(SumOfMABL_A) AS SMABLA, ANBAR
FROM         dbo.AK_MOGO_AVL_KOL_SUB(@Forms___F_MENU_ANBAR___DT2, @Forms___F_MENU_ANBAR___MANBAR) AK_MOGO_AVL_KOL_SUB
GROUP BY CODE, ANBAR )
