CREATE FUNCTION [dbo].[AK_MOGO_FR]
(@Forms___F_MENU_ANBAR___DT2 bigint,
@Forms___F_MENU_ANBAR___MANBAR NVARCHAR(10))
RETURNS TABLE
AS
RETURN ( SELECT     CODE, SUM(MEG) AS MEG, AVG(AvgOfMABL) AS AvgOfMABL, ANBAR
FROM         dbo.AK_MOGO_FR_SUB(@Forms___F_MENU_ANBAR___DT2, @Forms___F_MENU_ANBAR___MANBAR) AK_MOGO_FR_SUB
GROUP BY CODE, ANBAR )
