 CREATE FUNCTION dbo.AK_RESERVED
  (@Forms___F_MENU_ANBAR___DT2 bigint,
  @Forms___F_MENU_ANBAR___MANBAR nvarchar(10))
  RETURNS TABLE
  AS
  RETURN ( SELECT     dbo.INVO_LST.CODE, SUM(dbo.INVO_LST.MEGHk) AS MEGHRES, AVG(dbo.INVO_LST.MABL) AS AvgOfMABL, dbo.INVO_LST.ANBAR
  FROM         dbo.HEAD_LST INNER JOIN
                        dbo.INVO_LST ON dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG AND dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER
  WHERE     (dbo.INVO_LST.TAG = 20) AND (dbo.HEAD_LST.DATE_N <= @Forms___F_MENU_ANBAR___DT2) AND (dbo.HEAD_LST.TAMIR = 1 OR dbo.HEAD_LST.TAMIR = 4)
  GROUP BY dbo.INVO_LST.CODE, dbo.INVO_LST.ANBAR
  HAVING      (dbo.INVO_LST.ANBAR LIKE @Forms___F_MENU_ANBAR___MANBAR) )
  
 

