CREATE  FUNCTION [dbo].[AKMOGUDI_KOL_ANBAR_ONE]
 (@Forms___F_MENU_ANBAR___DT2 BIGINT,
 @Forms___F_MENU_ANBAR___MANBAR nvarchar(10))
 RETURNS TABLE
 AS
 RETURN ( SELECT     AKMOGO_AVL_KOL.CODE, ROUND(ISNULL(ISNULL(AKMOGO_AVL_KOL.SMEGH, 0) - ISNULL(AK_MOGO_FR.MEG, 0), 0), 2) AS MAND, 
                       AKMOGO_AVL_KOL.ANBAR
 FROM         dbo.STUF_DEF INNER JOIN
                       dbo.STUF_FSK LEFT OUTER JOIN
                       dbo.AKMOGO_AVL_KOL(@Forms___F_MENU_ANBAR___DT2, @Forms___F_MENU_ANBAR___MANBAR) AKMOGO_AVL_KOL ON 
                       dbo.STUF_FSK.ANBAR = AKMOGO_AVL_KOL.ANBAR AND dbo.STUF_FSK.CODE = AKMOGO_AVL_KOL.CODE LEFT OUTER JOIN
                       dbo.AK_MOGO_FR(@Forms___F_MENU_ANBAR___DT2, @Forms___F_MENU_ANBAR___MANBAR) AK_MOGO_FR ON 
                       dbo.STUF_FSK.ANBAR = AK_MOGO_FR.ANBAR AND dbo.STUF_FSK.CODE = AK_MOGO_FR.CODE ON dbo.STUF_DEF.CODE = dbo.STUF_FSK.CODE
 WHERE     (NOT (AKMOGO_AVL_KOL.CODE IS NULL)) )
