CREATE FUNCTION [dbo].[AKMOGO_AVL_KOL]
(@Forms___F_MENU_ANBAR___DT2 bigint,
@Forms___F_MENU_ANBAR___MANBAR nvarchar(50))
RETURNS TABLE
AS
RETURN ( SELECT     CODE, SMEGH, ISNULL(SMABLA / SMEGH, 0) AS FI, ANBAR
FROM         dbo.AK_MOGO_AVL_KOL(@Forms___F_MENU_ANBAR___DT2, @Forms___F_MENU_ANBAR___MANBAR) AK_MOGO_AVL_KOL )
