CREATE FUNCTION [dbo].[AMAR_TOLID]
(@fromdate bigint,
@todate bigint)
RETURNS TABLE
AS
RETURN (SELECT     dbo.INVO_LST.CODE, SUM(dbo.INVO_LST.MEGHk) AS MEGHT, dbo.STUF_DEF.NAME, dbo.TCOD_STUFGROUP.NAMES, dbo.TCOD_VAHEDS.NAMES AS vahed, 
                      dbo.STUF_DEF.N_FANI
FROM         dbo.HEAD_LST INNER JOIN
                      dbo.INVO_LST ON dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG INNER JOIN
                      dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE INNER JOIN
                      dbo.TCOD_STUFGROUP ON dbo.STUF_DEF.RADAH = dbo.TCOD_STUFGROUP.CODE INNER JOIN
                      dbo.TCOD_VAHEDS ON dbo.STUF_DEF.VAHED = dbo.TCOD_VAHEDS.CODE
WHERE     (dbo.HEAD_LST.TAG = 9) AND (dbo.HEAD_LST.DATE_N >= @FROMDATE) AND (dbo.HEAD_LST.DATE_N <= @TODATE)
GROUP BY dbo.INVO_LST.CODE, dbo.STUF_DEF.NAME, dbo.TCOD_STUFGROUP.NAMES, dbo.TCOD_VAHEDS.NAMES, dbo.STUF_DEF.N_FANI )
