CREATE FUNCTION [dbo].[AMAR_TOLID_FAREE]
(@fromdate bigint,
@todate bigint)
RETURNS TABLE
AS
RETURN ( SELECT     dbo.INVO_LST.CODE, SUM(dbo.INVO_LST.MEGHk) AS MEGHT, SUM(ROUND(dbo.INVO_LST.MEGHk / dbo.FNESBAT.FNESBAT, 2)) AS MEGHKF, dbo.STUF_DEF.NAME, 
                      dbo.TCOD_STUFGROUP.NAMES, dbo.TCOD_VAHEDS.NAMES AS vahed, dbo.STUF_DEF.N_FANI, LEFT(dbo.STUF_DEF.N_FANI, 4) AS SAIZE, 
                      SUBSTRING(dbo.STUF_DEF.N_FANI, 5, 3) AS TARH, SUBSTRING(dbo.STUF_DEF.N_FANI, 9, 2) AS RAD, SUBSTRING(dbo.STUF_DEF.N_FANI, 8, 1) AS DEGR, 
                      SUBSTRING(dbo.STUF_DEF.N_FANI, 11, LEN(dbo.STUF_DEF.N_FANI) - 10) AS Expr2
FROM         dbo.HEAD_LST INNER JOIN
                      dbo.INVO_LST ON dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG INNER JOIN
                      dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE INNER JOIN
                      dbo.TCOD_STUFGROUP ON dbo.STUF_DEF.RADAH = dbo.TCOD_STUFGROUP.CODE INNER JOIN
                      dbo.TCOD_VAHEDS ON dbo.STUF_DEF.VAHED = dbo.TCOD_VAHEDS.CODE INNER JOIN
                      dbo.FNESBAT ON dbo.STUF_DEF.CODE = dbo.FNESBAT.CODE
WHERE     (dbo.HEAD_LST.TAG = 9) AND (dbo.HEAD_LST.DATE_N >= @FROMDATE) AND (dbo.HEAD_LST.DATE_N <= @TODATE)
GROUP BY dbo.INVO_LST.CODE, dbo.STUF_DEF.NAME, dbo.TCOD_STUFGROUP.NAMES, dbo.TCOD_VAHEDS.NAMES, dbo.STUF_DEF.N_FANI, LEFT(dbo.STUF_DEF.N_FANI, 4), 
                      SUBSTRING(dbo.STUF_DEF.N_FANI, 5, 3), SUBSTRING(dbo.STUF_DEF.N_FANI, 9, 2), SUBSTRING(dbo.STUF_DEF.N_FANI, 11, LEN(dbo.STUF_DEF.N_FANI) - 10) )
