CREATE FUNCTION [dbo].[AMAR_MASRAF]
(@FROMDATE bigint,
@TODATE bigint,
@KONTROL INT)
RETURNS TABLE
AS
RETURN ( SELECT     CODE, MEGH, MABL, KALA, VAHED, GRP, price, mabst, mabst - MABL AS MOGNERKH, MABLST, MEGHST, MEGHST - MEGH AS MOGMAS, 
                      (MEGHST - MEGH) * price AS MOGRMAS
FROM         dbo.AMAR_MASRAF_SUB(@FROMDATE, @TODATE, @KONTROL) AMAR_MASRAF_SUB )
