CREATE FUNCTION [dbo].[ASNAD_WITHOUT_CHEK2]
 (@Forms___Baseknow___ADA nvarchar(20),
 @Forms___Baseknow___ADV nvarchar(20))
 RETURNS TABLE
 AS
 RETURN ( SELECT     ASNAD_DARYAFTY2.N_SERI, ASNAD_DARYAFTY2.BANK, ASNAD_DARYAFTY2.BED, ASNAD_DARYAFTY2.N_S, ASNAD_DARYAFTY2.HES_K, 
                       ASNAD_DARYAFTY2.HES_M, ASNAD_DARYAFTY2.HES_T, ASNAD_DARYAFTY2.SHARH, ASNAD_DARYAFTY2.NUMBER, ASNAD_DARYAFTY2.TAG, 
                       dbo.PAY_GETD.N_SERI AS Expr1, dbo.PAY_GETD.BANK AS Expr2
 FROM         dbo.ASNAD_DARYAFTY2(@Forms___Baseknow___ADA, @Forms___Baseknow___ADV) ASNAD_DARYAFTY2 LEFT OUTER JOIN
                       dbo.PAY_GETD ON ASNAD_DARYAFTY2.BED = dbo.PAY_GETD.MABL AND ASNAD_DARYAFTY2.N_SERI = dbo.PAY_GETD.N_SERI AND 
                       ASNAD_DARYAFTY2.BANK = dbo.PAY_GETD.BANK
 WHERE     (dbo.PAY_GETD.N_SERI IS NULL) AND (ASNAD_DARYAFTY2.BES = 0) )
