CREATE FUNCTION [dbo].[ASNAD_WITHOUT_CHEK]
(@Forms___Baseknow___ADA nvarchar(20),
@Forms___Baseknow___ADV nvarchar(20))
RETURNS TABLE
AS
RETURN ( SELECT     ASNAD_DARYAFTY.N_SERI, ASNAD_DARYAFTY.BANK, ASNAD_DARYAFTY.BED, ASNAD_DARYAFTY.N_S, ASNAD_DARYAFTY.HES_K, ASNAD_DARYAFTY.HES_M, 
                      ASNAD_DARYAFTY.HES_T, ASNAD_DARYAFTY.SHARH, ASNAD_DARYAFTY.NUMBER, ASNAD_DARYAFTY.TAG, dbo.PAY_GETD.N_SERI AS Expr1, 
                      dbo.PAY_GETD.BANK AS Expr2
FROM         dbo.ASNAD_DARYAFTY(@Forms___Baseknow___ADA, @Forms___Baseknow___ADV) ASNAD_DARYAFTY LEFT OUTER JOIN
                      dbo.PAY_GETD ON ASNAD_DARYAFTY.BED = dbo.PAY_GETD.MABL AND ASNAD_DARYAFTY.N_SERI = dbo.PAY_GETD.N_SERI AND 
                      ASNAD_DARYAFTY.BANK = dbo.PAY_GETD.BANK
WHERE     (dbo.PAY_GETD.N_SERI IS NULL) AND (ASNAD_DARYAFTY.BES = 0) )
