CREATE FUNCTION [dbo].[BEDEH_USER]
(@DT1 BIGINT,
@DT2 BIGINT,
@USER nvarchar(40))
RETURNS TABLE
AS
RETURN ( SELECT     NUMBER, DATE_N, PNUMBER, NAME AS person1, MOLAH, USER_NAME, SumOfM_NAGHD AS NAGHD, SumOfMABL_VAR AS VARm, 
                      SumOfMABL_HAV AS HAV, SumOfMABL_HAZ AS HAZ, SumOfTAKHFIF AS TAKH, SumOfMABL AS CHKM, SumOfMABL_K AS MABK, 
                      SumOfMABL_K - (SumOfMABL + SumOfM_NAGHD + SumOfMABL_VAR + SumOfMABL_HAV - SumOfMABL_HAZ + SumOfTAKHFIF) AS MAND
FROM         dbo.Q_FROOSH_DAYLY_USER(@DT1, @DT2, @USER) Q_FROOSH_DAYLY_USER
WHERE     (USER_NAME = @USER) AND 
                      (SumOfMABL_K - (SumOfMABL + SumOfM_NAGHD + SumOfMABL_VAR + SumOfMABL_HAV - SumOfMABL_HAZ + SumOfTAKHFIF) <> 0) )
