CREATE FUNCTION [dbo].[C_TARAZ_ANBAR_MAIN]
(@FORMS___F_MENU_ANBAR_TARAZ___DT2 nvarchar(50))
RETURNS TABLE
AS
RETURN ( SELECT     ANBAR, CODE, CASE TAG WHEN 0 THEN MEG ELSE 0 END AS MEGHAV, CASE TAG WHEN 0 THEN avgofmabl ELSE 0 END AS MABAV, 
                      CASE TAG WHEN 1 THEN MEG ELSE 0 END AS MEGHKH, CASE TAG WHEN 1 THEN avgofmabl ELSE 0 END AS MABKH, 
                      CASE TAG WHEN 2 THEN MEG ELSE 0 END AS MEGHFR, CASE TAG WHEN 2 THEN avgofmabl ELSE 0 END AS MABFR, 
                      CASE TAG WHEN 5 THEN MEG ELSE 0 END AS MEGHENKR, CASE TAG WHEN 5 THEN avgofmabl ELSE 0 END AS MABENKR, 
                      CASE TAG WHEN 6 THEN MEG ELSE 0 END AS MEGHENVO, CASE TAG WHEN 6 THEN avgofmabl ELSE 0 END AS MABENVO, 
                      CASE TAG WHEN 9 THEN MEG ELSE 0 END AS MEGHTO, CASE TAG WHEN 9 THEN avgofmabl ELSE 0 END AS MABTO, 
                      CASE TAG WHEN 10 THEN MEG ELSE 0 END AS MEGHEX, CASE TAG WHEN 10 THEN avgofmabl ELSE 0 END AS MABEX, 
                      CASE TAG WHEN 11 THEN MEG ELSE 0 END AS MEGHEXS, CASE TAG WHEN 11 THEN avgofmabl ELSE 0 END AS MABEXS, 
                      CASE TAG WHEN 17 THEN MEG ELSE 0 END AS MEGHKAS, CASE TAG WHEN 17 THEN avgofmabl ELSE 0 END AS MABKAS, 
                      CASE TAG WHEN 18 THEN MEG ELSE 0 END AS MEGHEZ, CASE TAG WHEN 18 THEN avgofmabl ELSE 0 END AS MABEZ, 
                      CASE TAG WHEN 22 THEN MEG ELSE 0 END AS MEGHBF, CASE TAG WHEN 22 THEN avgofmabl ELSE 0 END AS MABBF, 
                      CASE TAG WHEN 26 THEN MEG ELSE 0 END AS MEGHBKHA, CASE TAG WHEN 26 THEN avgofmabl ELSE 0 END AS MABKHA
FROM         dbo.C_TARAZ_ANBAR_SUB(@FORMS___F_MENU_ANBAR_TARAZ___DT2) C_TARAZ_ANBAR_SUB )
