CREATE FUNCTION [dbo].[C_TARAZ_ANBAR_KHAS]
(@FORMS___F_MENU_ANBAR_TARAZ___DT2 BIGINT,
@ANB NVARCHAR(50))
RETURNS TABLE
AS
RETURN ( SELECT     TOP 100 PERCENT C_TARAZ_ANBAR_MAIN.ANBAR, dbo.TCOD_ANBAR.NAMES AS ANBNAM, C_TARAZ_ANBAR_MAIN.CODE, 
                      dbo.STUF_DEF.NAME AS KALA, dbo.STUF_DEF.VAHED, dbo.TCOD_VAHEDS.NAMES AS VAHNAM, dbo.STUF_DEF.RADAH, 
                      dbo.TCOD_STUFGROUP.NAMES AS grname, SUM(C_TARAZ_ANBAR_MAIN.MEGHAV) AS MEGHAVM, SUM(C_TARAZ_ANBAR_MAIN.MABAV) 
                      AS MABAVM, 
                      SUM((C_TARAZ_ANBAR_MAIN.MEGHAV + C_TARAZ_ANBAR_MAIN.MEGHKH + C_TARAZ_ANBAR_MAIN.MEGHENVO + C_TARAZ_ANBAR_MAIN.MEGHTO
                       + C_TARAZ_ANBAR_MAIN.MEGHKAS + C_TARAZ_ANBAR_MAIN.MEGHBF) 
                      - (C_TARAZ_ANBAR_MAIN.MEGHFR + C_TARAZ_ANBAR_MAIN.MEGHENKR + C_TARAZ_ANBAR_MAIN.MEGHEX + C_TARAZ_ANBAR_MAIN.MEGHEXS +
                       C_TARAZ_ANBAR_MAIN.MEGHEZ + C_TARAZ_ANBAR_MAIN.MEGHBKHA)) AS MOG, 
                      SUM((C_TARAZ_ANBAR_MAIN.MABAV + C_TARAZ_ANBAR_MAIN.MABKH + C_TARAZ_ANBAR_MAIN.MABENVO + C_TARAZ_ANBAR_MAIN.MABTO + C_TARAZ_ANBAR_MAIN.MABKAS
                       + C_TARAZ_ANBAR_MAIN.MABBF) 
                      - (C_TARAZ_ANBAR_MAIN.MABFR + C_TARAZ_ANBAR_MAIN.MABENKR + C_TARAZ_ANBAR_MAIN.MABEX + C_TARAZ_ANBAR_MAIN.MABEXS + C_TARAZ_ANBAR_MAIN.MABEZ
                       + C_TARAZ_ANBAR_MAIN.MABKHA)) AS MABLM, 
                      SUM(C_TARAZ_ANBAR_MAIN.MEGHKH + C_TARAZ_ANBAR_MAIN.MEGHENVO + C_TARAZ_ANBAR_MAIN.MEGHTO + C_TARAZ_ANBAR_MAIN.MEGHKAS
                       + C_TARAZ_ANBAR_MAIN.MEGHBF) AS MEGHVARED, 
                      SUM(C_TARAZ_ANBAR_MAIN.MABKH + C_TARAZ_ANBAR_MAIN.MABENVO + C_TARAZ_ANBAR_MAIN.MABTO + C_TARAZ_ANBAR_MAIN.MABKAS + C_TARAZ_ANBAR_MAIN.MABBF)
                       AS MABVARED, 
                      SUM(C_TARAZ_ANBAR_MAIN.MEGHFR + C_TARAZ_ANBAR_MAIN.MEGHENKR + C_TARAZ_ANBAR_MAIN.MEGHEX + C_TARAZ_ANBAR_MAIN.MEGHEXS
                       + C_TARAZ_ANBAR_MAIN.MEGHEZ + C_TARAZ_ANBAR_MAIN.MEGHBKHA) AS MEGHSADER, 
                      SUM(C_TARAZ_ANBAR_MAIN.MABFR + C_TARAZ_ANBAR_MAIN.MABENKR + C_TARAZ_ANBAR_MAIN.MABEX + C_TARAZ_ANBAR_MAIN.MABEXS + C_TARAZ_ANBAR_MAIN.MABEZ
                       + C_TARAZ_ANBAR_MAIN.MABKHA) AS MABSADER, SUM(C_TARAZ_ANBAR_MAIN.MEGHKH) AS MEGHKHM, SUM(C_TARAZ_ANBAR_MAIN.MABKH) 
                      AS MABKHM, SUM(C_TARAZ_ANBAR_MAIN.MEGHFR) AS MEGHFRM, SUM(C_TARAZ_ANBAR_MAIN.MABFR) AS MABFRM, 
                      SUM(C_TARAZ_ANBAR_MAIN.MEGHENKR) AS MEGHENKRM, SUM(C_TARAZ_ANBAR_MAIN.MABENKR) AS MABENKRM, 
                      SUM(C_TARAZ_ANBAR_MAIN.MEGHENVO) AS MEGHENVOM, SUM(C_TARAZ_ANBAR_MAIN.MABENVO) AS MABENVOM, 
                      SUM(C_TARAZ_ANBAR_MAIN.MEGHTO) AS MEGHTOM, SUM(C_TARAZ_ANBAR_MAIN.MABTO) AS MABTOM, SUM(C_TARAZ_ANBAR_MAIN.MEGHEX) 
                      AS MEGHEXM, SUM(C_TARAZ_ANBAR_MAIN.MABEX) AS MABEXM, SUM(C_TARAZ_ANBAR_MAIN.MEGHEXS) AS MEGHEXSM, 
                      SUM(C_TARAZ_ANBAR_MAIN.MABEXS) AS MABEXSM, SUM(C_TARAZ_ANBAR_MAIN.MEGHKAS) AS MEGHKASM, 
                      SUM(C_TARAZ_ANBAR_MAIN.MABKAS) AS MABKASM, SUM(C_TARAZ_ANBAR_MAIN.MEGHEZ) AS MEGHEZM, SUM(C_TARAZ_ANBAR_MAIN.MABEZ) 
                      AS MABEZM, SUM(C_TARAZ_ANBAR_MAIN.MEGHBF) AS MEGHBFM, SUM(C_TARAZ_ANBAR_MAIN.MABBF) AS MABBFM, 
                      CAST(dbo.STUF_DEF.CODE AS int) AS VCOD, SUM(C_TARAZ_ANBAR_MAIN.MEGHBF + C_TARAZ_ANBAR_MAIN.MEGHKAS) AS MEGHSAYER, 
                      SUM(C_TARAZ_ANBAR_MAIN.MABBF + C_TARAZ_ANBAR_MAIN.MABKAS) AS MABSAYER, 
                      SUM(C_TARAZ_ANBAR_MAIN.MEGHEX + C_TARAZ_ANBAR_MAIN.MEGHEXS) AS MEGHSAYES, 
                      SUM(C_TARAZ_ANBAR_MAIN.MABEX + C_TARAZ_ANBAR_MAIN.MABEXS) AS MABSAYES, SUM(C_TARAZ_ANBAR_MAIN.MEGHBKHA) 
                      AS MEGHBKHAM, SUM(C_TARAZ_ANBAR_MAIN.MABKHA) AS MABKHAM
FROM         dbo.C_TARAZ_ANBAR_MAIN(@FORMS___F_MENU_ANBAR_TARAZ___DT2) C_TARAZ_ANBAR_MAIN INNER JOIN
                      dbo.STUF_DEF ON C_TARAZ_ANBAR_MAIN.CODE = dbo.STUF_DEF.CODE INNER JOIN
                      dbo.TCOD_ANBAR ON C_TARAZ_ANBAR_MAIN.ANBAR = dbo.TCOD_ANBAR.CODE LEFT OUTER JOIN
                      dbo.TCOD_VAHEDS ON dbo.STUF_DEF.VAHED = dbo.TCOD_VAHEDS.CODE LEFT OUTER JOIN
                      dbo.TCOD_STUFGROUP ON dbo.STUF_DEF.RADAH = dbo.TCOD_STUFGROUP.CODE
WHERE     (dbo.STUF_DEF.KINDK = 1)
GROUP BY C_TARAZ_ANBAR_MAIN.ANBAR, dbo.TCOD_ANBAR.NAMES, C_TARAZ_ANBAR_MAIN.CODE, dbo.STUF_DEF.NAME, dbo.STUF_DEF.VAHED, 
                      dbo.TCOD_VAHEDS.NAMES, dbo.STUF_DEF.RADAH, dbo.TCOD_STUFGROUP.NAMES, CAST(dbo.STUF_DEF.CODE AS int)
HAVING      (C_TARAZ_ANBAR_MAIN.ANBAR LIKE @ANB)
ORDER BY CAST(dbo.STUF_DEF.CODE AS int) )
