CREATE FUNCTION [dbo].[DRIVER_HAVALAH]
(@DT1 bigint,
@DT2 bigint,
@DRIVER nvarchar(50))
RETURNS TABLE
AS
RETURN ( SELECT     dbo.INVO_LST.CODE, SUM(dbo.INVO_LST.MEGH) AS SMEGH, SUM(dbo.INVO_LST.MEGHk) AS SMEGHK, dbo.TCOD_VAHEDS.NAMES AS vahed, 
                      dbo.TCOD_ANBAR.NAMES AS anbar, dbo.STUF_DEF.NAME + N' ' + ISNULL(dbo.INVO_LST.MANDAH, N'') AS KALA, SUM(dbo.INVO_LST.MABL_K) 
                      AS smabk, dbo.OTHER_DTL.REQUEST_NO, dbo.OTHER_DTL.BARNAMEH, dbo.OTHER_DTL.DRIVER_MOB, dbo.OTHER_DTL.CAMIUN_NUM, 
                      dbo.OTHER_DTL.MAGHSAD, dbo.OTHER_DTL.CAM_KHALY, dbo.OTHER_DTL.CAM_POOR, dbo.OTHER_DTL.TOZIH, dbo.OTHER_DTL.CAMIUN, 
                      dbo.OTHER_DTL.DRIVER, dbo.HEAD_LST.DATE_N
FROM         dbo.INVO_LST INNER JOIN
                      dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE INNER JOIN
                      dbo.TCOD_VAHEDS ON dbo.INVO_LST.VAHED_K = dbo.TCOD_VAHEDS.CODE INNER JOIN
                      dbo.TCOD_ANBAR ON dbo.INVO_LST.ANBAR = dbo.TCOD_ANBAR.CODE INNER JOIN
                      dbo.HEAD_LST ON dbo.INVO_LST.NUMBER = dbo.HEAD_LST.NUMBER AND dbo.INVO_LST.TAG = dbo.HEAD_LST.TAG INNER JOIN
                      dbo.OTHER_DTL ON dbo.HEAD_LST.NUMBER = dbo.OTHER_DTL.NUMBER AND dbo.HEAD_LST.TAG = dbo.OTHER_DTL.TAG
WHERE     (dbo.HEAD_LST.DATE_N BETWEEN @DT1 AND @DT2) AND (dbo.OTHER_DTL.DRIVER = @DRIVER)
GROUP BY dbo.INVO_LST.CODE, dbo.TCOD_VAHEDS.NAMES, dbo.TCOD_ANBAR.NAMES, dbo.HEAD_LST.DATE_N, dbo.OTHER_DTL.DRIVER, 
                      dbo.OTHER_DTL.CAMIUN, dbo.OTHER_DTL.TOZIH, dbo.OTHER_DTL.CAM_POOR, dbo.OTHER_DTL.CAM_KHALY, dbo.OTHER_DTL.MAGHSAD, 
                      dbo.OTHER_DTL.CAMIUN_NUM, dbo.OTHER_DTL.DRIVER_MOB, dbo.OTHER_DTL.BARNAMEH, dbo.OTHER_DTL.REQUEST_NO, 
                      dbo.STUF_DEF.NAME + N' ' + ISNULL(dbo.INVO_LST.MANDAH, N'') )
