CREATE FUNCTION [dbo].[FINDSFROSH](@Forms___HEAD_LST_FROOSH___DATE varchar (255))
RETURNS TABLE
AS
RETURN ( SELECT     N_S, DATE_S, SHARH_S, NO_S, ANBAR, N_FACTOR, GHATEI
FROM         dbo.DEED_HED
WHERE     (DATE_S = @Forms___HEAD_LST_FROOSH___DATE) AND (NO_S = 2) )
