CREATE FUNCTION [dbo].[FROOSH_COUNT]
(@F_MENU_DATE_DT1 bigint,
@F_MENU_DATE_DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     TOP 100 PERCENT COUNT(dbo.INVO_LST.CODE) AS TEDAD, dbo.STUF_DEF.CODE, dbo.STUF_DEF.NAME, SUM(dbo.INVO_LST.MEGHk) AS SMEGHk, 
                      dbo.HEAD_LST.DEPATMAN, dbo.DEPART.DEPNAME, SUM(dbo.INVO_LST.MABL_K) AS SMABL
FROM         dbo.HEAD_LST INNER JOIN
                      dbo.INVO_LST ON dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_LST.TAG - 11 = dbo.INVO_LST.TAG INNER JOIN
                      dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE INNER JOIN
                      dbo.DEPART ON dbo.HEAD_LST.DEPATMAN = dbo.DEPART.DEPATMAN
WHERE     (dbo.HEAD_LST.TAG = 13) AND (dbo.HEAD_LST.DATE_N BETWEEN @F_MENU_DATE_DT1 AND @F_MENU_DATE_DT2)
GROUP BY dbo.STUF_DEF.NAME, dbo.HEAD_LST.DEPATMAN, dbo.DEPART.DEPNAME, dbo.STUF_DEF.CODE
ORDER BY dbo.STUF_DEF.NAME )
