CREATE FUNCTION [dbo].[FROOSH_COUNT_baz]
(@F_MENU_DATE_DT1 bigint,
@F_MENU_DATE_DT2 bigint,
@dep nvarchar(50))
RETURNS TABLE
AS
RETURN ( SELECT     TOP 100 PERCENT COUNT(dbo.INVO_LST.CODE) AS TEDAD, dbo.STUF_DEF.CODE, dbo.STUF_DEF.NAME, SUM(dbo.INVO_LST.MEGHk) AS SMEGHk, 
                      dbo.HEAD_LST.DEPATMAN, dbo.DEPART.DEPNAME, SUM(dbo.INVO_LST.MABL_K) AS SMABL, dbo.STUF_DEF.N_FANI
FROM         dbo.HEAD_LST INNER JOIN
                      dbo.INVO_LST ON dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG INNER JOIN
                      dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE INNER JOIN
                      dbo.DEPART ON dbo.HEAD_LST.DEPATMAN = dbo.DEPART.DEPATMAN
WHERE     (dbo.HEAD_LST.TAG = 2) AND (dbo.HEAD_LST.DATE_N BETWEEN @F_MENU_DATE_DT1 AND @F_MENU_DATE_DT2) AND 
                      (CAST(dbo.HEAD_LST.DEPATMAN AS nvarchar) LIKE @dep)
GROUP BY dbo.STUF_DEF.NAME, dbo.HEAD_LST.DEPATMAN, dbo.DEPART.DEPNAME, dbo.STUF_DEF.CODE, dbo.STUF_DEF.N_FANI
ORDER BY dbo.STUF_DEF.NAME )
