CREATE FUNCTION [dbo].[FROOSH_COUNTALL_CITY_N_FANI]
(@F_MENU_DATE_DT1 bigint,
@F_MENU_DATE_DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     COUNT(dbo.INVO_LST.CODE) AS TEDAD, dbo.STUF_DEF.CODE, dbo.STUF_DEF.NAME, SUM(dbo.INVO_LST.MEGHk) AS MEGHkK, 
                      SUM(ROUND(dbo.INVO_LST.MEGHk / dbo.FNESBAT.FNESBAT, 2)) AS MEGHKF, dbo.TCOD_MAP.MPNAME AS MPNAME, dbo.STUF_DEF.N_FANI, 
                      dbo.HEAD_LST.CUST_NO, SUM(dbo.INVO_LST.MABL) AS MAB, SUM(dbo.INVO_LST.MABL_K) AS MABK, LEFT(dbo.STUF_DEF.N_FANI, 4) AS SAIZE, 
                      SUBSTRING(dbo.STUF_DEF.N_FANI, 5, 3) AS TARH, SUBSTRING(dbo.STUF_DEF.N_FANI, 9, 2) AS RAD, SUBSTRING(dbo.STUF_DEF.N_FANI, 8, 1) AS DEGR, 
                      SUBSTRING(dbo.STUF_DEF.N_FANI, 11, LEN(dbo.STUF_DEF.N_FANI) - 10) AS Expr2, dbo.TCOD_MAP.MPCODE, dbo.TCOD_MAP.OSCO
FROM         dbo.HEAD_LST INNER JOIN
                      dbo.INVO_LST ON dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG INNER JOIN
                      dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE INNER JOIN
                      dbo.FNESBAT ON dbo.STUF_DEF.CODE = dbo.FNESBAT.CODE INNER JOIN
                      dbo.HEAD_LST HEAD_LST_1 ON dbo.HEAD_LST.NUMBER = HEAD_LST_1.NUMBER AND dbo.HEAD_LST.TAG = HEAD_LST_1.TAG - 11 LEFT OUTER JOIN
                      dbo.TCOD_MAP ON dbo.HEAD_LST.MAS = dbo.TCOD_MAP.MPCODE
WHERE     (dbo.TCOD_MAP.MPP = 100) AND (HEAD_LST_1.TAG = 13) AND (HEAD_LST_1.DATE_N BETWEEN @F_MENU_DATE_DT1 AND @F_MENU_DATE_DT2)
GROUP BY dbo.STUF_DEF.NAME, dbo.STUF_DEF.CODE, dbo.TCOD_MAP.MPNAME, dbo.STUF_DEF.N_FANI, dbo.HEAD_LST.CUST_NO, dbo.TCOD_MAP.MPCODE, 
                      dbo.TCOD_MAP.OSCO, LEFT(dbo.STUF_DEF.N_FANI, 4), SUBSTRING(dbo.STUF_DEF.N_FANI, 5, 3), SUBSTRING(dbo.STUF_DEF.N_FANI, 9, 2), 
                      SUBSTRING(dbo.STUF_DEF.N_FANI, 11, LEN(dbo.STUF_DEF.N_FANI) - 10) )
