CREATE FUNCTION [dbo].[GOZARESH_FROOSH_ROZANAH]
(@Forms___F_MENU_GOZARESH_FROOSH___USERR nvarchar(40),
@Forms___F_MENU_GOZARESH_FROOSH___SSHIFT NVARCHAR(10),
@Forms___F_MENU_GOZARESH_FROOSH___DEPART INT,
@Forms___F_MENU_GOZARESH_FROOSH___DT1 BIGINT,
@Forms___F_MENU_GOZARESH_FROOSH___DT2 BIGINT)
RETURNS TABLE
AS
RETURN ( SELECT     HEAD_LST_FROOSH_USER.SumOfM_NAGHD, HEAD_LST_FROOSH_USER.SumOfMABL_VAR, HEAD_LST_FROOSH_USER.SumOfMABL_HAV, 
                      HEAD_LST_FROOSH_USER.SumOfMABL_HAZ, HEAD_LST_FROOSH_USER.chk, HEAD_LST_FROOSH_USER.USER_NAME, HEAD_LST_FROOSH_USER.SHIFT, 
                      HEAD_LST_FROOSH_USER.DEPATMAN, INVO_LST_TAKHFIFAT.NAME, INVO_LST_TAKHFIFAT.SUMOFMEGHK, INVO_LST_TAKHFIFAT.MABL, 
                      INVO_LST_TAKHFIFAT.SumOfMABL_K + INVO_LST_TAKHFIFAT.SIMBAA AS SumOfMABL_K, INVO_LST_TAKHFIFAT.SHNAME, INVO_LST_TAKHFIFAT.DEPNAME, 
                      INVO_LST_TAKHFIFAT.TFP, INVO_LST_TAKHFIFAT.TAKH, INVO_LST_TAKHFIFAT.CUSTKNAME, INVO_LST_TAKHFIFAT.SIMBAA, 
                      HEAD_LST_FROOSH_USER.smbaa
FROM         dbo.HEAD_LST_FROOSH_USER(@Forms___F_MENU_GOZARESH_FROOSH___USERR, @Forms___F_MENU_GOZARESH_FROOSH___SSHIFT, 
                      @Forms___F_MENU_GOZARESH_FROOSH___DEPART, @Forms___F_MENU_GOZARESH_FROOSH___DT1, @Forms___F_MENU_GOZARESH_FROOSH___DT2) 
                      HEAD_LST_FROOSH_USER INNER JOIN
                      dbo.INVO_LST_TAKHFIFAT(@Forms___F_MENU_GOZARESH_FROOSH___USERR, @Forms___F_MENU_GOZARESH_FROOSH___SSHIFT, 
                      @Forms___F_MENU_GOZARESH_FROOSH___DEPART, @Forms___F_MENU_GOZARESH_FROOSH___DT1, @Forms___F_MENU_GOZARESH_FROOSH___DT2) 
                      INVO_LST_TAKHFIFAT ON HEAD_LST_FROOSH_USER.DEPATMAN = INVO_LST_TAKHFIFAT.DEPATMAN AND 
                      HEAD_LST_FROOSH_USER.SHIFT = INVO_LST_TAKHFIFAT.SHIFT AND HEAD_LST_FROOSH_USER.USER_NAME = INVO_LST_TAKHFIFAT.USER_NAME )
