CREATE FUNCTION [dbo].[GOZARESH_FROOSH_ROZANAH2]
 (@Forms___F_MENU_GOZARESH_FROOSH___USERR nvarchar(40),
 @Forms___F_MENU_GOZARESH_FROOSH___SSHIFT NVARCHAR(10),
 @Forms___F_MENU_GOZARESH_FROOSH___DEPART INT,
 @Forms___F_MENU_GOZARESH_FROOSH___DT1 BIGINT,
 @Forms___F_MENU_GOZARESH_FROOSH___DT2 BIGINT)
 RETURNS TABLE
 AS
 RETURN ( SELECT     HEAD_LST_FROOSH_USER2.SumOfM_NAGHD, HEAD_LST_FROOSH_USER2.SumOfMABL_VAR, HEAD_LST_FROOSH_USER2.SumOfMABL_HAV, 
                       HEAD_LST_FROOSH_USER2.SumOfMABL_HAZ, HEAD_LST_FROOSH_USER2.chk, HEAD_LST_FROOSH_USER2.USER_NAME, HEAD_LST_FROOSH_USER2.SHIFT, 
                       HEAD_LST_FROOSH_USER2.DEPATMAN, INVO_LST_TAKHFIFAT2.NAME, INVO_LST_TAKHFIFAT2.SUMOFMEGHK, INVO_LST_TAKHFIFAT2.MABL, 
                       INVO_LST_TAKHFIFAT2.SumOfMABL_K, INVO_LST_TAKHFIFAT2.SHNAME, INVO_LST_TAKHFIFAT2.DEPNAME, INVO_LST_TAKHFIFAT2.TFP, 
                       INVO_LST_TAKHFIFAT2.TAKH, INVO_LST_TAKHFIFAT2.SIMBAA, HEAD_LST_FROOSH_USER2.MBAAs, HEAD_LST_FROOSH_USER2.TAKHFIFs
 FROM         dbo.HEAD_LST_FROOSH_USER2(@Forms___F_MENU_GOZARESH_FROOSH___USERR, @Forms___F_MENU_GOZARESH_FROOSH___SSHIFT, 
                       @Forms___F_MENU_GOZARESH_FROOSH___DEPART, @Forms___F_MENU_GOZARESH_FROOSH___DT1, @Forms___F_MENU_GOZARESH_FROOSH___DT2) 
                       HEAD_LST_FROOSH_USER2 INNER JOIN
                       dbo.INVO_LST_TAKHFIFAT2(@Forms___F_MENU_GOZARESH_FROOSH___USERR, @Forms___F_MENU_GOZARESH_FROOSH___SSHIFT, 
                       @Forms___F_MENU_GOZARESH_FROOSH___DEPART, @Forms___F_MENU_GOZARESH_FROOSH___DT1, @Forms___F_MENU_GOZARESH_FROOSH___DT2) 
                       INVO_LST_TAKHFIFAT2 ON HEAD_LST_FROOSH_USER2.DEPATMAN = INVO_LST_TAKHFIFAT2.DEPATMAN AND 
                       HEAD_LST_FROOSH_USER2.SHIFT = INVO_LST_TAKHFIFAT2.SHIFT AND HEAD_LST_FROOSH_USER2.USER_NAME = INVO_LST_TAKHFIFAT2.USER_NAME )
