CREATE FUNCTION [dbo].[GOZARESH_FROOSH_ROZANEH3]
 (@Forms___F_MENU_GOZARESH_FROOSH___DEPART INT,
 @Forms___F_MENU_GOZARESH_FROOSH___DT1 BIGINT,
 @Forms___F_MENU_GOZARESH_FROOSH___DT2 BIGINT)
 RETURNS TABLE
 AS
 RETURN ( SELECT     HEAD_LST_FROOSH_USER3.SumOfM_NAGHD, HEAD_LST_FROOSH_USER3.SumOfMABL_VAR, HEAD_LST_FROOSH_USER3.SumOfMABL_HAV, 
                       HEAD_LST_FROOSH_USER3.SumOfMABL_HAZ, HEAD_LST_FROOSH_USER3.chk, HEAD_LST_FROOSH_USER3.DEPATMAN, INVO_LST_TAKHFIFAT3.NAME, 
                       INVO_LST_TAKHFIFAT3.SUMOFMEGHK, INVO_LST_TAKHFIFAT3.MABL, INVO_LST_TAKHFIFAT3.SumOfMABL_K, INVO_LST_TAKHFIFAT3.SHNAME, 
                       INVO_LST_TAKHFIFAT3.DEPNAME, INVO_LST_TAKHFIFAT3.TFP, INVO_LST_TAKHFIFAT3.TAKH, INVO_LST_TAKHFIFAT3.SIMBAA, HEAD_LST_FROOSH_USER3.MBAAs, 
                       HEAD_LST_FROOSH_USER3.TAKHFIFs
 FROM         dbo.INVO_LST_TAKHFIFAT3(@Forms___F_MENU_GOZARESH_FROOSH___DEPART, @Forms___F_MENU_GOZARESH_FROOSH___DT1, 
                       @Forms___F_MENU_GOZARESH_FROOSH___DT2) INVO_LST_TAKHFIFAT3 INNER JOIN
                       dbo.HEAD_LST_FROOSH_USER3(@Forms___F_MENU_GOZARESH_FROOSH___DEPART, @Forms___F_MENU_GOZARESH_FROOSH___DT1, 
                       @Forms___F_MENU_GOZARESH_FROOSH___DT2) HEAD_LST_FROOSH_USER3 ON INVO_LST_TAKHFIFAT3.DEPATMAN = HEAD_LST_FROOSH_USER3.DEPATMAN )
