create FUNCTION [dbo].[GUSER_JAM_CHEKS_PERDEPART_SUB]
 (@USERR nvarchar(40),
 @SSHIFT nvarchar(50),
 @DEPART int,
 @DT1 bigint,
 @DT2 bigint)
 
 RETURNS TABLE
 AS
 RETURN ( SELECT     SUM(ISNULL(dbo.PAY_GETD.MABL, 0)) AS mab, COUNT(dbo.PAY_GETD.MABL) AS CountOfMABL, dbo.HEAD_LST.NUMBER
 FROM         dbo.HEAD_LST LEFT OUTER JOIN
                       dbo.PAY_GETD ON dbo.HEAD_LST.TAG = dbo.PAY_GETD.TAG AND dbo.HEAD_LST.NUMBER = dbo.PAY_GETD.NUMBER
 WHERE     (dbo.HEAD_LST.TAG = 2) AND (dbo.HEAD_LST.DATE_N BETWEEN @DT1 AND @DT2) AND (dbo.HEAD_LST.DEPATMAN = @DEPART) AND 
                       (CAST(dbo.HEAD_LST.SHIFT AS NVARCHAR) LIKE @SSHIFT) AND (dbo.HEAD_LST.USER_NAME LIKE @USERR)
 GROUP BY dbo.HEAD_LST.NUMBER )
