CREATE FUNCTION [dbo].[GUSER_FACT_PERDEPART_SUB]
(@DT1 bigint,
@DT2 bigint,
@DEPART int,
@SSHIFT nvarchar(50),
@USERR nvarchar(40))
RETURNS TABLE
AS
RETURN ( SELECT     dbo.HEAD_LST.NUMBER, dbo.HEAD_LST.M_NAGHD, dbo.HEAD_LST.MABL_VAR, dbo.HEAD_LST.MABL_HAV, dbo.UIIF(dbo.HEAD_LST.VAS, '=', 1, 
                      dbo.HEAD_LST.MABL_HAZ, dbo.HEAD_LST.MABL_HAZ * - 1) AS HAZ, dbo.HEAD_LST.TAKHFIF, dbo.HEAD_LST.MBAA, 
                      ISNULL(GUSER_FACTDTL_PERDEPART_SUB.SMABK, 0) AS SMAB, ISNULL(GUSER_JAM_CHEKS_PERDEPART_SUB.mab, 0) AS CHK
FROM         dbo.HEAD_LST LEFT OUTER JOIN
                      dbo.GUSER_FACTDTL_PERDEPART_SUB(@USERR, @SSHIFT, @DEPART, @DT1, @DT2) GUSER_FACTDTL_PERDEPART_SUB ON 
                      dbo.HEAD_LST.NUMBER = GUSER_FACTDTL_PERDEPART_SUB.NUMBER LEFT OUTER JOIN
                      dbo.GUSER_JAM_CHEKS_PERDEPART_SUB(@USERR, @SSHIFT, @DEPART, @DT1, @DT2) GUSER_JAM_CHEKS_PERDEPART_SUB ON 
                      dbo.HEAD_LST.NUMBER = GUSER_JAM_CHEKS_PERDEPART_SUB.NUMBER
WHERE     (dbo.HEAD_LST.TAG = 2) AND (dbo.HEAD_LST.DATE_N BETWEEN @DT1 AND @DT2) AND (dbo.HEAD_LST.DEPATMAN = @DEPART) AND 
                      (CAST(dbo.HEAD_LST.SHIFT AS NVARCHAR) LIKE @SSHIFT) AND (dbo.HEAD_LST.USER_NAME LIKE @USERR) )
