CREATE FUNCTION [dbo].[GUSER_FACTDTL_PERDEPART_SUB]
 (@USERR nvarchar(40),
 @SSHIFT nvarchar(50),
 @DEPART int,
 @DT1 bigint,
 @DT2 bigint)
 RETURNS TABLE
 AS
 RETURN ( SELECT     dbo.INVO_LST.NUMBER, dbo.INVO_LST.TAG, SUM(dbo.INVO_LST.MABL_K) AS SMABK
 FROM         dbo.INVO_LST INNER JOIN
                       dbo.HEAD_LST ON dbo.INVO_LST.NUMBER = dbo.HEAD_LST.NUMBER AND dbo.INVO_LST.TAG = dbo.HEAD_LST.TAG
 WHERE     (dbo.HEAD_LST.USER_NAME LIKE @USERR) AND (CAST(dbo.HEAD_LST.SHIFT AS NVARCHAR) LIKE @SSHIFT) AND (dbo.HEAD_LST.DEPATMAN = @DEPART) AND 
                       (dbo.HEAD_LST.DATE_N BETWEEN @DT1 AND @DT2)
 GROUP BY dbo.INVO_LST.NUMBER, dbo.INVO_LST.TAG
 HAVING      (dbo.INVO_LST.TAG = 2) )
