CREATE FUNCTION [dbo].[HAVALAH_KO] (@Forms___HEAD_MAN___NUMBER varchar (255)
) 
RETURNS TABLE 
AS RETURN (SELECT DTL_MANF.CODE, DTL_MANF.ANBAR, DTL_MANF.VAHED_K, (DTL_MANF.MEGHk+PERT)*INVO_LST.MEGHk AS M, (DTL_MANF.MEGHk+PERT)*INVO_LST.MEGHk AS MK, INVO_LST.NUMBER, INVO_LST.TAG, DTL_MANF.FNUMB
FROM INVO_LST LEFT JOIN (DTL_MANF RIGHT JOIN HEAD_MANF ON (DTL_MANF.FNUMB = HEAD_MANF.FNUMB)) ON (INVO_LST.CODE = HEAD_MANF.CODE)
WHERE (((INVO_LST.NUMBER)=@Forms___HEAD_MAN___NUMBER) AND ((INVO_LST.TAG)=7)))
