create FUNCTION [dbo].[HEAD_LST_CHK_USER3]
 (@Forms___F_MENU_GOZARESH_FROOSH___DEPART int,
 @Forms___F_MENU_GOZARESH_FROOSH___DT1 bigint,
 @Forms___F_MENU_GOZARESH_FROOSH___DT2 bigint)
 RETURNS TABLE
 AS
 RETURN ( SELECT     dbo.HEAD_LST.DEPATMAN, SUM(dbo.PAY_GETD.MABL) AS SumOfMABL, dbo.HEAD_LST.NUMBER, dbo.HEAD_LST.TAG
 FROM         dbo.HEAD_LST INNER JOIN
                       dbo.PAY_GETD ON dbo.HEAD_LST.TAG = dbo.PAY_GETD.TAG AND dbo.HEAD_LST.NUMBER = dbo.PAY_GETD.NUMBER AND 
                       dbo.HEAD_LST.TAG = dbo.PAY_GETD.TAG AND dbo.HEAD_LST.NUMBER = dbo.PAY_GETD.NUMBER AND dbo.HEAD_LST.TAG = dbo.PAY_GETD.TAG AND 
                       dbo.HEAD_LST.NUMBER = dbo.PAY_GETD.NUMBER AND dbo.HEAD_LST.TAG = dbo.PAY_GETD.TAG AND dbo.HEAD_LST.NUMBER = dbo.PAY_GETD.NUMBER
 GROUP BY dbo.HEAD_LST.DEPATMAN, dbo.HEAD_LST.NUMBER, dbo.HEAD_LST.TAG, dbo.HEAD_LST.DATE_N
 HAVING      (dbo.HEAD_LST.DEPATMAN = @Forms___F_MENU_GOZARESH_FROOSH___DEPART) AND (dbo.HEAD_LST.DATE_N BETWEEN 
                       @Forms___F_MENU_GOZARESH_FROOSH___DT1 AND @Forms___F_MENU_GOZARESH_FROOSH___DT2) )
