CREATE FUNCTION [dbo].[HEAD_LST_FROOSH_USER3]
 (@Forms___F_MENU_GOZARESH_FROOSH___DEPART INT,
 @Forms___F_MENU_GOZARESH_FROOSH___DT1 BIGINT,
 @Forms___F_MENU_GOZARESH_FROOSH___DT2 BIGINT)
 RETURNS TABLE
 AS
 RETURN ( SELECT     SUM(dbo.HEAD_LST.M_NAGHD) AS SumOfM_NAGHD, SUM(dbo.HEAD_LST.MABL_VAR) AS SumOfMABL_VAR, SUM(dbo.HEAD_LST.MABL_HAV) AS SumOfMABL_HAV, 
                       SUM(dbo.HEAD_LST.MABL_HAZ) AS SumOfMABL_HAZ, dbo.HEAD_LST.DEPATMAN, SUM(ISNULL(HEAD_LST_CHK_USER3.SumOfMABL, 0)) AS chk, 
                       SUM(dbo.HEAD_LST.MBAA) AS MBAAs, SUM(dbo.HEAD_LST.TAKHFIF) AS TAKHFIFs
 FROM         dbo.HEAD_LST LEFT OUTER JOIN
                       dbo.HEAD_LST_CHK_USER3(@Forms___F_MENU_GOZARESH_FROOSH___DEPART, @Forms___F_MENU_GOZARESH_FROOSH___DT1, 
                       @Forms___F_MENU_GOZARESH_FROOSH___DT2) HEAD_LST_CHK_USER3 ON dbo.HEAD_LST.TAG - 11 = HEAD_LST_CHK_USER3.TAG AND 
                       dbo.HEAD_LST.NUMBER = HEAD_LST_CHK_USER3.NUMBER
 WHERE     (dbo.HEAD_LST.DATE_N BETWEEN @Forms___F_MENU_GOZARESH_FROOSH___DT1 AND @Forms___F_MENU_GOZARESH_FROOSH___DT2) AND 
                       (dbo.HEAD_LST.TAG = 13)
 GROUP BY dbo.HEAD_LST.DEPATMAN
 HAVING      (dbo.HEAD_LST.DEPATMAN = @Forms___F_MENU_GOZARESH_FROOSH___DEPART) )
