CREATE FUNCTION [dbo].[HEAD_LST_FROOSH_USER]
(@Forms___F_MENU_GOZARESH_FROOSH___USERR nvarchar(40),
@Forms___F_MENU_GOZARESH_FROOSH___SSHIFT int,
@Forms___F_MENU_GOZARESH_FROOSH___DEPART int,
@Forms___F_MENU_GOZARESH_FROOSH___DT1 bigint,
@Forms___F_MENU_GOZARESH_FROOSH___DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     SUM(dbo.HEAD_LST.M_NAGHD) AS SumOfM_NAGHD, SUM(dbo.HEAD_LST.MABL_VAR) AS SumOfMABL_VAR, SUM(dbo.HEAD_LST.MABL_HAV) AS SumOfMABL_HAV, 
                      SUM(dbo.HEAD_LST.MABL_HAZ) AS SumOfMABL_HAZ, dbo.HEAD_LST.USER_NAME, dbo.HEAD_LST.SHIFT, dbo.HEAD_LST.DEPATMAN, 
                      SUM(ISNULL(HEAD_LST_CHK_USER.SumOfMABL, 0)) AS chk, SUM(dbo.HEAD_LST.MBAA) AS smbaa
FROM         dbo.HEAD_LST LEFT OUTER JOIN
                      dbo.HEAD_LST_CHK_USER(@Forms___F_MENU_GOZARESH_FROOSH___USERR, @Forms___F_MENU_GOZARESH_FROOSH___SSHIFT, 
                      @Forms___F_MENU_GOZARESH_FROOSH___DEPART, @Forms___F_MENU_GOZARESH_FROOSH___DT1, @Forms___F_MENU_GOZARESH_FROOSH___DT2) 
                      HEAD_LST_CHK_USER ON dbo.HEAD_LST.TAG = HEAD_LST_CHK_USER.TAG AND dbo.HEAD_LST.NUMBER = HEAD_LST_CHK_USER.NUMBER
WHERE     (dbo.HEAD_LST.DATE_N BETWEEN @Forms___F_MENU_GOZARESH_FROOSH___DT1 AND @Forms___F_MENU_GOZARESH_FROOSH___DT2)
GROUP BY dbo.HEAD_LST.USER_NAME, dbo.HEAD_LST.SHIFT, dbo.HEAD_LST.DEPATMAN
HAVING      (dbo.HEAD_LST.USER_NAME = @Forms___F_MENU_GOZARESH_FROOSH___USERR) AND 
                      (dbo.HEAD_LST.SHIFT = @Forms___F_MENU_GOZARESH_FROOSH___SSHIFT) AND 
                      (dbo.HEAD_LST.DEPATMAN = @Forms___F_MENU_GOZARESH_FROOSH___DEPART) )
