CREATE FUNCTION [dbo].[HEAD_CHEK_FROOSH]
()
RETURNS TABLE
AS
RETURN ( SELECT     dbo.HEAD_LST.NUMBER, dbo.HEAD_LST.TAG, dbo.HEAD_LST.ANBAR, dbo.HEAD_LST.NUMBER1, dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.TAH, 
                      dbo.HEAD_LST.MAS, dbo.HEAD_LST.VAS, dbo.HEAD_LST.N_S, dbo.HEAD_LST.CUST_NO, dbo.HEAD_LST.MOLAH, dbo.HEAD_LST.M_NAGHD, 
                      dbo.HEAD_LST.MABL_VAR, dbo.HEAD_LST.MOIN_VAR, dbo.HEAD_LST.MABL_HAV, dbo.HEAD_LST.MOIN_HAV, dbo.HEAD_LST.MABL_HAZ, 
                      dbo.HEAD_LST.MOIN_HAZ, dbo.HEAD_LST.TAKHFIF, dbo.HEAD_LST.MOIN_KHF, dbo.HEAD_LST.ANBARF, dbo.HEAD_LST.FNUMCO, 
                      COUNT(dbo.PAY_GETD.MABL) AS CountOfMABL, dbo.HEAD_LST.USER_NAME, dbo.SHIFT.SHNAME, dbo.DEPART.DEPNAME, 
                      SUM(ISNULL(dbo.PAY_GETD.MABL, 0)) AS mab, dbo.HEAD_LST.MBAA, dbo.HEAD_LST.SHARAYET
FROM         dbo.SHIFT INNER JOIN
                      dbo.DEPART INNER JOIN
                      dbo.HEAD_LST ON dbo.DEPART.DEPATMAN = dbo.HEAD_LST.DEPATMAN AND dbo.DEPART.DEPATMAN = dbo.HEAD_LST.DEPATMAN ON 
                      dbo.SHIFT.SHIFT_ID = dbo.HEAD_LST.SHIFT AND dbo.SHIFT.SHIFT_ID = dbo.HEAD_LST.SHIFT LEFT OUTER JOIN
                      dbo.PAY_GETD ON dbo.HEAD_LST.TAG = dbo.PAY_GETD.TAG AND dbo.HEAD_LST.NUMBER = dbo.PAY_GETD.NUMBER
GROUP BY dbo.HEAD_LST.NUMBER, dbo.HEAD_LST.TAG, dbo.HEAD_LST.ANBAR, dbo.HEAD_LST.NUMBER1, dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.TAH, 
                      dbo.HEAD_LST.MAS, dbo.HEAD_LST.VAS, dbo.HEAD_LST.N_S, dbo.HEAD_LST.CUST_NO, dbo.HEAD_LST.MOLAH, dbo.HEAD_LST.M_NAGHD, 
                      dbo.HEAD_LST.MABL_VAR, dbo.HEAD_LST.MOIN_VAR, dbo.HEAD_LST.MABL_HAV, dbo.HEAD_LST.MOIN_HAV, dbo.HEAD_LST.MABL_HAZ, 
                      dbo.HEAD_LST.MOIN_HAZ, dbo.HEAD_LST.TAKHFIF, dbo.HEAD_LST.MOIN_KHF, dbo.HEAD_LST.ANBARF, dbo.HEAD_LST.FNUMCO, 
                      dbo.HEAD_LST.USER_NAME, dbo.SHIFT.SHNAME, dbo.DEPART.DEPNAME, dbo.HEAD_LST.MBAA, dbo.HEAD_LST.SHARAYET
HAVING      (dbo.HEAD_LST.TAG = 2) )
