CREATE FUNCTION [dbo].[INVO_LST_TAKHFIFAT2]
 (@Forms___F_MENU_GOZARESH_FROOSH___USERR nvarchar(40),
 @Forms___F_MENU_GOZARESH_FROOSH___SSHIFT NVARCHAR(10),
 @Forms___F_MENU_GOZARESH_FROOSH___DEPART INT,
 @Forms___F_MENU_GOZARESH_FROOSH___DT1 BIGINT,
 @Forms___F_MENU_GOZARESH_FROOSH___DT2 BIGINT)
 RETURNS TABLE
 AS
 RETURN ( SELECT     dbo.STUF_DEF.NAME, SUM(dbo.INVO_LST_TAKH.MEGHk) AS SUMOFMEGHK, dbo.INVO_LST_TAKH.MABL, SUM(dbo.INVO_LST_TAKH.MABL_K) AS SumOfMABL_K, 
                       dbo.SHIFT.SHNAME, dbo.DEPART.DEPNAME, dbo.INVO_LST_TAKH.N_KOL AS TFP, SUM(dbo.INVO_LST_TAKH.N_MOIN) AS TAKH, dbo.INVO_LST_TAKH.DEPATMAN, 
                       dbo.INVO_LST_TAKH.SHIFT, dbo.INVO_LST_TAKH.USER_NAME, SUM(dbo.INVO_LST_TAKH.IMBAA) AS SIMBAA
 FROM         dbo.SHIFT INNER JOIN
                       dbo.DEPART INNER JOIN
                       dbo.STUF_DEF INNER JOIN
                       dbo.INVO_LST_TAKH ON dbo.STUF_DEF.CODE = dbo.INVO_LST_TAKH.CODE ON dbo.DEPART.DEPATMAN = dbo.INVO_LST_TAKH.DEPATMAN ON 
                       dbo.SHIFT.SHIFT_ID = dbo.INVO_LST_TAKH.SHIFT
 WHERE     (dbo.INVO_LST_TAKH.USER_NAME = @Forms___F_MENU_GOZARESH_FROOSH___USERR) AND 
                       (dbo.INVO_LST_TAKH.DEPATMAN = @Forms___F_MENU_GOZARESH_FROOSH___DEPART) AND (dbo.INVO_LST_TAKH.DATE_N BETWEEN 
                       @Forms___F_MENU_GOZARESH_FROOSH___DT1 AND @Forms___F_MENU_GOZARESH_FROOSH___DT2) AND 
                       (dbo.INVO_LST_TAKH.SHIFT = @Forms___F_MENU_GOZARESH_FROOSH___SSHIFT)
 GROUP BY dbo.STUF_DEF.NAME, dbo.INVO_LST_TAKH.MABL, dbo.SHIFT.SHNAME, dbo.DEPART.DEPNAME, dbo.INVO_LST_TAKH.DEPATMAN, dbo.INVO_LST_TAKH.SHIFT, 
                       dbo.INVO_LST_TAKH.USER_NAME, dbo.INVO_LST_TAKH.N_KOL )
