create  FUNCTION [dbo].[KHAREED_MP] (@Forms___F_MENU_ANBAR___DT1 BIGINT,@Forms___F_MENU_ANBAR___DT2 BIGINT)
 RETURNS Table AS 
 RETURN 
 ( SELECT     dbo.STUF_DEF.CODE, dbo.STUF_DEF.NAME, dbo.INVO_LST.MEGHk, dbo.STUF_DEF.N_FANI, dbo.INVO_LST.MABL, dbo.INVO_LST.MABL_K, LEFT(dbo.STUF_DEF.N_FANI, 2) AS col1, SUBSTRING(dbo.STUF_DEF.N_FANI, 3, 1) AS col2, 
 SUBSTRING(dbo.STUF_DEF.N_FANI, 4, 3) AS col3, SUBSTRING(dbo.STUF_DEF.N_FANI, 7, 2) AS col4, 
 SUBSTRING(dbo.STUF_DEF.N_FANI, 9, 2)   AS col5,
 SUBSTRING(dbo.STUF_DEF.N_FANI, 11, 2) AS col6,
 SUBSTRING(dbo.STUF_DEF.N_FANI, 13, 2) AS col7, SUBSTRING(dbo.STUF_DEF.N_FANI, 15, 2) AS col8,  
 SUBSTRING(dbo.STUF_DEF.N_FANI, 17, 2) AS col9, 
 dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.CUST_NO, dbo.HEAD_LST.NUMBER 
 FROM         dbo.HEAD_LST INNER JOIN    dbo.INVO_LST ON dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG INNER JOIN   dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE 
 WHERE     (dbo.HEAD_LST.TAG = 1) AND (dbo.HEAD_LST.DATE_N BETWEEN 1 AND 99999999))
