CREATE FUNCTION [dbo].[LASTHOKM]
(@Forms___WORKHEAD___WDATE bigint)
RETURNS TABLE
AS
RETURN ( SELECT     MAX(HONUM) AS MaxOfHONUM, CODE, MAX(HDATE) AS MaxOfHDATE
FROM         dbo.PHOKM
WHERE     (HDATE < @Forms___WORKHEAD___WDATE)
GROUP BY CODE )
