CREATE FUNCTION [dbo].[MAKEMODTL]
	(
		@VMONUM INT
	)
RETURNS @MODTL TABLE (MONUM INT, N_S FLOAT , HES_K INT, HES_M int, HES_T int,SHARH NVARCHAR(60),BED FLOAT,BES FLOAT,TICK BIT, N_SERI FLOAT,BANK INT,NUMBER FLOAT,TAG FLOAT)
AS
	BEGIN
                      INSERT INTO  @MODTL
	                             SELECT MO_DTL.MONUM, MO_DTL.N_S, MO_DTL.HES_K, MO_DTL.HES_M, MO_DTL.HES_T, MO_DTL.SHARH, MO_DTL.BED, MO_DTL.BES, MO_DTL.TICK, MO_DTL.N_SERI, MO_DTL.BANK, MO_DTL.NUMBER, MO_DTL.TAG                             FROM MO_DTL
                             WHERE (((MO_DTL.MONUM)=@VMONUM));
	RETURN
	END
