CREATE FUNCTION [dbo].[MANDGHEMAT]
(@GHEMAT int,
@DT1 bigint,
@DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     dbo.DEED_DTL.HES_K, dbo.DEED_DTL.HES_M, dbo.DEED_DTL.HES_T, SUM(dbo.DEED_DTL.BED - dbo.DEED_DTL.BES) AS GHEMAT
FROM         dbo.DEED_DTL INNER JOIN
                      dbo.DEED_HED ON dbo.DEED_DTL.N_S = dbo.DEED_HED.N_S
WHERE     (dbo.DEED_HED.DATE_S BETWEEN @DT1 AND @DT2)
GROUP BY dbo.DEED_DTL.HES_K, dbo.DEED_DTL.HES_M, dbo.DEED_DTL.HES_T
HAVING      (dbo.DEED_DTL.HES_K = @GHEMAT) )
