CREATE FUNCTION [dbo].[MANDFROOSH]
(@FROOSH int,
@DT1 bigint,
@DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     dbo.DEED_DTL.HES_K, dbo.DEED_DTL.HES_M, SUM(dbo.DEED_DTL.BES - dbo.DEED_DTL.BED) AS FROOSH, dbo.DETA_HES.NAME
FROM         dbo.DEED_DTL INNER JOIN
                      dbo.DETA_HES ON dbo.DEED_DTL.HES_K = dbo.DETA_HES.N_KOL AND dbo.DEED_DTL.HES_M = dbo.DETA_HES.NUMBER INNER JOIN
                      dbo.DEED_HED ON dbo.DEED_DTL.N_S = dbo.DEED_HED.N_S
WHERE     (dbo.DEED_HED.DATE_S BETWEEN @DT1 AND @DT2)
GROUP BY dbo.DEED_DTL.HES_K, dbo.DEED_DTL.HES_M, dbo.DETA_HES.NAME
HAVING      (dbo.DEED_DTL.HES_K = @FROOSH) )
