CREATE FUNCTION [dbo].[MASRAFST]
(@FROMDATE bigint,
@TODATE bigint,
@kontrol int)
RETURNS TABLE
AS
RETURN ( SELECT     dbo.DEED_DTL.HES_T, SUM(dbo.DEED_DTL.BES) AS MABLST
FROM         dbo.DEED_DTL INNER JOIN
                      dbo.DEED_HED ON dbo.DEED_DTL.N_S = dbo.DEED_HED.N_S
WHERE     (dbo.DEED_DTL.HES_K = @kontrol) AND (dbo.DEED_HED.DATE_S >= @FROMDATE) AND (dbo.DEED_HED.DATE_S <= @TODATE)
GROUP BY dbo.DEED_DTL.HES_T
HAVING      (dbo.DEED_DTL.HES_T <> 99999996) AND (dbo.DEED_DTL.HES_T <> 99999997) AND (dbo.DEED_DTL.HES_T <> 99999998) AND 
                      (dbo.DEED_DTL.HES_T <> 99999999) )
