CREATE FUNCTION [dbo].[MOG_KH_A](@FORMS___F_MENU_ANBAR_TARAZ___DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     ANBARF AS ANBAR, CODE, SUM(MEG) AS SMEG, SUM(SumOfMABL_K) AS SMABL_K
FROM         dbo.MOG_EN(@FORMS___F_MENU_ANBAR_TARAZ___DT2) MOG_EN
GROUP BY ANBARF, CODE )
