CREATE FUNCTION [dbo].[MOG_FR_A]
(@FORMS___F_MENU_ANBAR_TARAZ___DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     ANBAR, CODE, SUM(MEG) AS MEG, SUM(avgofmabl) AS avgofmabl
FROM         dbo.MOG_FR_A_sub(@FORMS___F_MENU_ANBAR_TARAZ___DT2) MOG_FR_A_sub
GROUP BY ANBAR, CODE )
