CREATE FUNCTION [dbo].[Q_BEDEHBESTANHA_2]
 (@dt bigint)
 RETURNS TABLE
 AS
 RETURN ( SELECT     Q_BEDEHBESTANHA_SUB.TAFZIL, Q_BEDEHBESTANHA_SUB.HES_K, Q_BEDEHBESTANHA_SUB.HES_M, Q_BEDEHBESTANHA_SUB.SumOfBED, 
                       Q_BEDEHBESTANHA_SUB.SumOfBES, Q_BEDEHBESTANHA_SUB.BEDBES, Q_BEDEHBESTANHA_SUB.NAME, Q_BEDEHBESTANHA_SUB.MOIN, 
                       dbo.UIIF(Q_BEDEHBESTANHA_SUB.BEDBES, '>', 0, Q_BEDEHBESTANHA_SUB.BEDBES, 0) AS BEDM, dbo.UIIF(Q_BEDEHBESTANHA_SUB.BEDBES, 
                       '<', 0, Q_BEDEHBESTANHA_SUB.BEDBES * - 1, 0) AS BESM, Q_BEDEHBESTANHA_SUB.HES_T, Q_BEDEHBESTANHA_SUB.ADDRESS, 
                       Q_BEDEHBESTANHA_SUB.TEL, Q_BEDEHBESTANHA_SUB.CODE_E, Q_BEDEHBESTANHA_SUB.TOZIH, Q_BEDEHBESTANHA_SUB.HES, 
                       Q_BEDEHBESTANHA_SUB.ECODE, Q_BEDEHBESTANHA_SUB.CUST_COD, Q_BEDEHBESTANHA_SUB.ROUTE_NAME, dbo.Visit_route.HES AS VCOD, 
                       dbo.CUST_HESAB.NAME AS VNAME, Q_BEDEHBESTANHA_SUB.HES_T2, Q_BEDEHBESTANHA_SUB.HES_T3, Q_BEDEHBESTANHA_SUB.HES_T4, 
                       CUST_HESAB_1.NAME AS tafname
 FROM         dbo.CUST_HESAB CUST_HESAB_1 INNER JOIN
                       dbo.Q_BEDEHBESTANHA_SUB(@dt) Q_BEDEHBESTANHA_SUB ON CUST_HESAB_1.hes = Q_BEDEHBESTANHA_SUB.HES LEFT OUTER JOIN
                       dbo.CUST_HESAB INNER JOIN
                       dbo.Visit_route ON dbo.CUST_HESAB.hes = dbo.Visit_route.HES ON Q_BEDEHBESTANHA_SUB.ROUTE_NAME = dbo.Visit_route.ROUTE_NAME )
