CREATE FUNCTION [dbo].[Q_CHEK_FROOSH_DAYLY](@Forms___F_MENU_GOZARESH_FROOSH___DT1 bigint,
@Forms___F_MENU_GOZARESH_FROOSH___DT2 bigint,
@Forms___F_MENU_GOZARESH_FROOSH___DEPART int,
@Forms___F_MENU_GOZARESH_FROOSH___USERR nvarchar(20),
@Forms___F_MENU_GOZARESH_FROOSH___SSHIFT nvarchar(20))
RETURNS TABLE
AS
RETURN ( SELECT     dbo.PAY_GETD.DATE, dbo.HEAD_LST.NUMBER, dbo.HEAD_LST.MOLAH, dbo.PAY_GETD.N_SERI, dbo.PAY_GETD.DATE_S, dbo.PAY_GETD.MABL, 
                      dbo.PAY_GETD.BANK, dbo.PAY_GETD.SHOBEH, dbo.PAY_GETD.N_HESAB, dbo.HEAD_LST.USER_NAME, 
                      RTRIM(CAST(dbo.HEAD_LST.SHIFT AS NVARCHAR)) AS SH, dbo.HEAD_LST.DEPATMAN, dbo.SHIFT.SHNAME, dbo.DEPART.DEPNAME, 
                      dbo.HEAD_LST.DATE_N
FROM         dbo.PERSON INNER JOIN
                      dbo.HEAD_LST ON dbo.PERSON.hes = dbo.HEAD_LST.CUST_NO INNER JOIN
                      dbo.PAY_GETD ON dbo.HEAD_LST.TAG = dbo.PAY_GETD.TAG AND dbo.HEAD_LST.NUMBER = dbo.PAY_GETD.NUMBER INNER JOIN
                      dbo.DEPART ON dbo.HEAD_LST.DEPATMAN = dbo.DEPART.DEPATMAN INNER JOIN
                      dbo.SHIFT ON dbo.HEAD_LST.SHIFT = dbo.SHIFT.SHIFT_ID
WHERE     (dbo.HEAD_LST.TAG = 2 OR
                      dbo.HEAD_LST.TAG = 14) AND (dbo.HEAD_LST.DEPATMAN = @Forms___F_MENU_GOZARESH_FROOSH___DEPART) AND 
                      (dbo.HEAD_LST.USER_NAME = @Forms___F_MENU_GOZARESH_FROOSH___USERR) AND (RTRIM(CAST(dbo.HEAD_LST.SHIFT AS NVARCHAR)) 
                      LIKE @Forms___F_MENU_GOZARESH_FROOSH___SSHIFT) AND (dbo.HEAD_LST.DATE_N BETWEEN 
                      @Forms___F_MENU_GOZARESH_FROOSH___DT1 AND @Forms___F_MENU_GOZARESH_FROOSH___DT2) )
