CREATE  FUNCTION [dbo].[Q_FISH_MAND_SUB2]
 (@Forms___F_MENU_BIM___MMO INT,
 @KOL INT,
 @MOIN INT,
 @TAF INT)
 RETURNS TABLE
 AS
 RETURN ( SELECT     HES_K, HES_M, HES_T, HES_T2, SHARH, SUM(MAND) AS SumOfMAND, @Forms___F_MENU_BIM___MMO AS MMO
 FROM         dbo.Q_FISH_MAND_SUB12(@Forms___F_MENU_BIM___MMO, @KOL, @MOIN, @TAF) Q_FISH_MAND_SUB12
 GROUP BY HES_K, HES_M, HES_T, SHARH, HES_T2 )
