CREATE FUNCTION [dbo].[Q_FOROSH_DAYLY_HED_USER]
(@DT1 bigint,
@DT2 bigint,
@USER nvarchar(40))
RETURNS TABLE
AS
RETURN ( SELECT     dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.NUMBER, SUM(dbo.HEAD_LST.M_NAGHD) AS SumOfM_NAGHD, SUM(dbo.HEAD_LST.MABL_VAR) 
                      AS SumOfMABL_VAR, SUM(dbo.HEAD_LST.MABL_HAV) AS SumOfMABL_HAV, SUM(dbo.UIIF(dbo.HEAD_LST.VAS, N'=', 1, dbo.HEAD_LST.MABL_HAZ, 
                      dbo.HEAD_LST.MABL_HAZ * - 1)) AS SumOfMABL_HAZ, SUM(dbo.HEAD_LST.TAKHFIF) AS SumOfTAKHFIF, dbo.PERSON.hes AS PNUMBER, 
                      dbo.PERSON.NAME, dbo.HEAD_LST.MOLAH, dbo.HEAD_LST.USER_NAME
FROM         dbo.HEAD_LST INNER JOIN
                      dbo.PERSON ON dbo.HEAD_LST.CUST_NO = dbo.PERSON.hes
WHERE     (dbo.HEAD_LST.TAG = 2)
GROUP BY dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.NUMBER, dbo.PERSON.hes, dbo.PERSON.NAME, dbo.HEAD_LST.MOLAH, 
                      dbo.HEAD_LST.USER_NAME
HAVING      (dbo.HEAD_LST.DATE_N BETWEEN @DT1 AND @DT2) AND (dbo.HEAD_LST.USER_NAME = @USER) )
