CREATE  FUNCTION [dbo].[Q_FROOSH_DAYLY_FCT1]
 (@Forms___F_MENU_KHFR___DT1 bigint,
 @Forms___F_MENU_KHFR___DT2 bigint,
 @Forms___F_MENU_KHFR___MMOIN NVARCHAR(20))
 RETURNS TABLE
 AS
 RETURN ( SELECT     TOP 100 PERCENT dbo.HEAD_BACK_ANBAR.NUMBER, dbo.HEAD_BACK_ANBAR.NUMBER1, dbo.PERSON.NAME, SUM(dbo.INVO_LST.MABL_K) AS SumOfMABL_K, 
                       dbo.HEAD_BACK_ANBAR.DATE_N, dbo.HEAD_BACK_ANBAR.HTAG AS tag
 FROM         dbo.PERSON INNER JOIN
                       dbo.HEAD_BACK_ANBAR ON dbo.PERSON.hes = dbo.HEAD_BACK_ANBAR.CUST_NO INNER JOIN
                       dbo.INVO_LST ON dbo.HEAD_BACK_ANBAR.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_BACK_ANBAR.HTAG = dbo.INVO_LST.TAG
 WHERE     (dbo.PERSON.hes LIKE @Forms___F_MENU_KHFR___MMOIN) AND (dbo.HEAD_BACK_ANBAR.HTAG = 2) AND (dbo.HEAD_BACK_ANBAR.DATE_N BETWEEN 
                       @Forms___F_MENU_KHFR___DT1 AND @Forms___F_MENU_KHFR___DT2)
 GROUP BY dbo.HEAD_BACK_ANBAR.NUMBER, dbo.PERSON.NAME, dbo.HEAD_BACK_ANBAR.DATE_N, dbo.HEAD_BACK_ANBAR.HTAG, dbo.HEAD_BACK_ANBAR.NUMBER1 )
