create  FUNCTION [dbo].[Q_FROOSH_CUSTOMER_BZ]
 (@DT1 nvarchar(50),
 @DT2 nvarchar(50))
 RETURNS TABLE
 AS
 RETURN ( SELECT     Q_FROOSH_DAYLY_HED2_MBA.hes, Q_FROOSH_DAYLY_HED2_MBA.NAME, QSL_FROOSH_DTL_BZ.FROOSH, Q_FROOSH_DAYLY_HED2_MBA.SumOfTAKHFIF, 
                       QSL_FROOSH_DTL_BZ.FROOSH - Q_FROOSH_DAYLY_HED2_MBA.SumOfTAKHFIF AS FROOSHKH, Q_FROOSH_DAYLY_HED2_MBA.SMBAA, 
                       QSL_FROOSH_DTL_BZ.FROOSH - Q_FROOSH_DAYLY_HED2_MBA.SumOfTAKHFIF + Q_FROOSH_DAYLY_HED2_MBA.SMBAA AS GHABEL, 1 AS KK, 
                       Q_FROOSH_DAYLY_HED2_MBA.ADDRESS, Q_FROOSH_DAYLY_HED2_MBA.CITY, Q_FROOSH_DAYLY_HED2_MBA.CODE_E, Q_FROOSH_DAYLY_HED2_MBA.ECODE, 
                       Q_FROOSH_DAYLY_HED2_MBA.IYALAT, Q_FROOSH_DAYLY_HED2_MBA.MCODEM, Q_FROOSH_DAYLY_HED2_MBA.MOBILE, Q_FROOSH_DAYLY_HED2_MBA.PCODE, 
                       Q_FROOSH_DAYLY_HED2_MBA.TEL, Q_FROOSH_DAYLY_HED2_MBA.TOZIH
 FROM         dbo.QSL_FROOSH_DTL_BZ(@DT1, @DT2) QSL_FROOSH_DTL_BZ INNER JOIN
                       dbo.Q_FROOSH_DAYLY_HED2_MBA(@DT1, @DT2) Q_FROOSH_DAYLY_HED2_MBA ON QSL_FROOSH_DTL_BZ.CUST_NO = Q_FROOSH_DAYLY_HED2_MBA.hes )
