CREATE FUNCTION [dbo].[Q_FROOSH_DAYLY_HED3_mba2]
(@Forms___F_MENU_GOZARESH_FROOSH___DT1 bigint,
@Forms___F_MENU_GOZARESH_FROOSH___DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     SUM(dbo.HEAD_LST.M_NAGHD) AS SumOfM_NAGHD, SUM(dbo.HEAD_LST.MABL_VAR) AS SumOfMABL_VAR, SUM(dbo.HEAD_LST.MABL_HAV) AS SumOfMABL_HAV, 
                      SUM(dbo.HEAD_LST.MABL_HAZ) AS SumOfMABL_HAZ, SUM(dbo.HEAD_LST.TAKHFIF) AS SumOfTAKHFIF, dbo.PERSON.NAME, SUM(dbo.HEAD_LST.MBAA) 
                      AS SMBAA, dbo.PERSON.hes, dbo.HEAD_LST.SADER
FROM         dbo.PERSON INNER JOIN
                      dbo.HEAD_LST ON dbo.PERSON.hes = dbo.HEAD_LST.CUST_NO
WHERE     (dbo.HEAD_LST.TAG = 13) AND (dbo.HEAD_LST.DATE_N BETWEEN @Forms___F_MENU_GOZARESH_FROOSH___DT1 AND 
                      @Forms___F_MENU_GOZARESH_FROOSH___DT2) AND (dbo.HEAD_LST.TICMBAA = 0)
GROUP BY dbo.PERSON.NAME, dbo.PERSON.hes, dbo.HEAD_LST.SADER )
