CREATE FUNCTION [dbo].[Q_FROOSH_DAYLY1]
(@Forms___F_MENU_KHFR___DT1 bigint,
@Forms___F_MENU_KHFR___DT2 bigint,
@Forms___F_MENU_KHFR___MMOIN NVARCHAR(20))
RETURNS TABLE
AS
RETURN ( SELECT     Q_FOROSH_DAYLY_HED1.DATE_N, Q_FOROSH_DAYLY_HED1.NUMBER, Q_FOROSH_DAYLY_HED1.SumOfM_NAGHD, Q_FOROSH_DAYLY_HED1.SumOfMABL_VAR,
                       Q_FOROSH_DAYLY_HED1.SumOfMABL_HAV, Q_FOROSH_DAYLY_HED1.SumOfMABL_HAZ, Q_FOROSH_DAYLY_HED1.SumOfTAKHFIF, 
                      Q_FOROSH_DAYLY_HED1.hes, Q_FOROSH_DAYLY_HED1.NAME, Q_FROOSH_DAYLY_CHEK1.SumOfMABL, ISNULL(Q_FROOSH_DAYLY_FCT1.SumOfMABL_K, 0) 
                      AS SumOfMABL_K, ' ' AS kk, Q_FOROSH_DAYLY_HED1.SMBAA, Q_FOROSH_DAYLY_HED1.NUMBER1, Q_FOROSH_DAYLY_HED1.MOLAH
FROM         dbo.Q_FOROSH_DAYLY_HED1(@Forms___F_MENU_KHFR___DT1, @Forms___F_MENU_KHFR___DT2, @Forms___F_MENU_KHFR___MMOIN) 
                      Q_FOROSH_DAYLY_HED1 LEFT OUTER JOIN
                      dbo.Q_FROOSH_DAYLY_FCT1(@Forms___F_MENU_KHFR___DT1, @Forms___F_MENU_KHFR___DT2, @Forms___F_MENU_KHFR___MMOIN) 
                      Q_FROOSH_DAYLY_FCT1 ON Q_FOROSH_DAYLY_HED1.TAG - 11 = Q_FROOSH_DAYLY_FCT1.tag AND 
                      Q_FOROSH_DAYLY_HED1.NUMBER = Q_FROOSH_DAYLY_FCT1.NUMBER LEFT OUTER JOIN
                      dbo.Q_FROOSH_DAYLY_CHEK1(@Forms___F_MENU_KHFR___DT1, @Forms___F_MENU_KHFR___DT2, @Forms___F_MENU_KHFR___MMOIN) 
                      Q_FROOSH_DAYLY_CHEK1 ON Q_FOROSH_DAYLY_HED1.TAG - 11 = Q_FROOSH_DAYLY_CHEK1.TAG AND 
                      Q_FOROSH_DAYLY_HED1.NUMBER = Q_FROOSH_DAYLY_CHEK1.NUMBER )
