CREATE FUNCTION [dbo].[Q_FROOSH_DAYLY4]
(@Forms___F_MENU_GOZARESH_FROOSH___DT1 bigint,
@Forms___F_MENU_GOZARESH_FROOSH___DT2 bigint,
@Forms___F_MENU_GOZARESH_FROOSH___DEPART int,
@Forms___F_MENU_GOZARESH_FROOSH___USERR nvarchar(20),
@Forms___F_MENU_GOZARESH_FROOSH___SSHIFT nvarchar(20))
RETURNS TABLE
AS
RETURN ( SELECT     Q_FROOSH_DAYLY_HED4.DATE_N, Q_FROOSH_DAYLY_HED4.NUMBER, Q_FROOSH_DAYLY_HED4.SumOfM_NAGHD, 
                      Q_FROOSH_DAYLY_HED4.SumOfMABL_VAR, Q_FROOSH_DAYLY_HED4.SumOfMABL_HAV, Q_FROOSH_DAYLY_HED4.SumOfMABL_HAZ, 
                      Q_FROOSH_DAYLY_HED4.SumOfTAKHFIF, Q_FROOSH_DAYLY_HED4.hes, Q_FROOSH_DAYLY_HED4.NAME, Q_FROOSH_DAYLY_HED4.DEPATMAN, 
                      Q_FROOSH_DAYLY_HED4.USER_NAME, RTRIM(CAST(Q_FROOSH_DAYLY_HED4.SHIFT AS NVARCHAR)) AS SHIFT, dbo.SHIFT.SHNAME, 
                      dbo.DEPART.DEPNAME, Q_FROOSH_DAYLY_HED4.USER_NAME AS USS, Q_FROOSH_DAYLY_HED4.TAG, ' ' AS kk, 
                      ISNULL(Q_FROOSH_DAYLY_FCT4.SumOfMABL_K, 0) + Q_FROOSH_DAYLY_HED4.SMBAA AS jamf, ISNULL(Q_FROOSH_DAYLY_CHEK4.SumOfMABL, 
                      0) AS jamch, Q_FROOSH_DAYLY_HED4.SMBAA, Q_FROOSH_DAYLY_FCT4.SumOfMABL_K
FROM         dbo.SHIFT INNER JOIN
                      dbo.DEPART INNER JOIN
                      dbo.Q_FROOSH_DAYLY_HED4(@Forms___F_MENU_GOZARESH_FROOSH___DT1, @Forms___F_MENU_GOZARESH_FROOSH___DT2) 
                      Q_FROOSH_DAYLY_HED4 ON dbo.DEPART.DEPATMAN = Q_FROOSH_DAYLY_HED4.DEPATMAN ON 
                      dbo.SHIFT.SHIFT_ID = Q_FROOSH_DAYLY_HED4.SHIFT LEFT OUTER JOIN
                      dbo.Q_FROOSH_DAYLY_CHEK4(@Forms___F_MENU_GOZARESH_FROOSH___DT1, @Forms___F_MENU_GOZARESH_FROOSH___DT2) 
                      Q_FROOSH_DAYLY_CHEK4 ON Q_FROOSH_DAYLY_HED4.TAG = Q_FROOSH_DAYLY_CHEK4.TAG AND 
                      Q_FROOSH_DAYLY_HED4.NUMBER = Q_FROOSH_DAYLY_CHEK4.NUMBER LEFT OUTER JOIN
                      dbo.Q_FROOSH_DAYLY_FCT4(@Forms___F_MENU_GOZARESH_FROOSH___DT1, @Forms___F_MENU_GOZARESH_FROOSH___DT2) 
                      Q_FROOSH_DAYLY_FCT4 ON Q_FROOSH_DAYLY_HED4.TAG = Q_FROOSH_DAYLY_FCT4.TAG AND 
                      Q_FROOSH_DAYLY_HED4.NUMBER = Q_FROOSH_DAYLY_FCT4.NUMBER
WHERE     (Q_FROOSH_DAYLY_HED4.DEPATMAN = @Forms___F_MENU_GOZARESH_FROOSH___DEPART) AND 
                      (Q_FROOSH_DAYLY_HED4.USER_NAME LIKE @Forms___F_MENU_GOZARESH_FROOSH___USERR) AND 
                      (RTRIM(CAST(Q_FROOSH_DAYLY_HED4.SHIFT AS NVARCHAR)) LIKE @Forms___F_MENU_GOZARESH_FROOSH___SSHIFT) )
