CREATE FUNCTION [dbo].[Q_FROOSH_DAYLY_FCT4]
(@Forms___F_MENU_GOZARESH_FROOSH___DT1 bigint,
@Forms___F_MENU_GOZARESH_FROOSH___DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     dbo.HEAD_LST.NUMBER, dbo.PERSON.NAME, SUM(dbo.INVO_LST.MABL_K) AS SumOfMABL_K, dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.TAG
FROM         dbo.PERSON INNER JOIN
                      dbo.HEAD_LST ON dbo.PERSON.hes = dbo.HEAD_LST.CUST_NO INNER JOIN
                      dbo.INVO_LST ON dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG AND dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER
WHERE     (dbo.HEAD_LST.TAG = 14) AND (dbo.HEAD_LST.DATE_N BETWEEN @Forms___F_MENU_GOZARESH_FROOSH___DT1 AND 
                      @Forms___F_MENU_GOZARESH_FROOSH___DT2)
GROUP BY dbo.HEAD_LST.NUMBER, dbo.PERSON.NAME, dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.TAG
UNION
SELECT     dbo.HEAD_LST.NUMBER, dbo.PERSON.NAME, SUM(dbo.INVO_LST.MABL_K) AS SumOfMABL_K, dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.TAG
FROM         dbo.PERSON INNER JOIN
                      dbo.HEAD_LST ON dbo.PERSON.hes = dbo.HEAD_LST.CUST_NO INNER JOIN
                      dbo.INVO_LST ON dbo.HEAD_LST.TAG - 11 = dbo.INVO_LST.TAG AND dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER
WHERE     (dbo.HEAD_LST.TAG = 13) AND (dbo.HEAD_LST.DATE_N BETWEEN @Forms___F_MENU_GOZARESH_FROOSH___DT1 AND 
                      @Forms___F_MENU_GOZARESH_FROOSH___DT2)
GROUP BY dbo.HEAD_LST.NUMBER, dbo.PERSON.NAME, dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.TAG )
