create FUNCTION [dbo].[Q_FROOSH_DAYLY_USER]
 (@dt1 BIGINT,
 @dt2 BIGINT,
 @USER nvarchar(50))
 RETURNS TABLE
 AS
 RETURN ( SELECT     Q_FOROSH_DAYLY_HED_USER.NUMBER, Q_FOROSH_DAYLY_HED_USER.DATE_N, Q_FOROSH_DAYLY_HED_USER.PNUMBER, 
                       Q_FOROSH_DAYLY_HED_USER.NAME, Q_FOROSH_DAYLY_HED_USER.MOLAH, Q_FOROSH_DAYLY_HED_USER.USER_NAME, 
                       ISNULL(Q_FOROSH_DAYLY_HED_USER.SumOfM_NAGHD, 0) AS SumOfM_NAGHD, ISNULL(Q_FOROSH_DAYLY_HED_USER.SumOfMABL_VAR, 0) 
                       AS SumOfMABL_VAR, ISNULL(Q_FOROSH_DAYLY_HED_USER.SumOfMABL_HAV, 0) AS SumOfMABL_HAV, 
                       ISNULL(Q_FOROSH_DAYLY_HED_USER.SumOfMABL_HAZ, 0) AS SumOfMABL_HAZ, ISNULL(Q_FOROSH_DAYLY_HED_USER.SumOfTAKHFIF, 0) 
                       AS SumOfTAKHFIF, ISNULL(Q_FROOSH_DAYLY_CHEK_USER.SumOfMABL, 0) AS SumOfMABL, 
                       ISNULL(Q_FROOSH_DAYLY_FCT_USER.SumOfMABL_K, 0) AS SumOfMABL_K
 FROM         dbo.Q_FOROSH_DAYLY_HED_USER(@dt1, @dt2, @USER) Q_FOROSH_DAYLY_HED_USER LEFT OUTER JOIN
                       dbo.Q_FROOSH_DAYLY_FCT_USER(@dt1, @dt2, @USER) Q_FROOSH_DAYLY_FCT_USER ON 
                       Q_FOROSH_DAYLY_HED_USER.NUMBER = Q_FROOSH_DAYLY_FCT_USER.NUMBER LEFT OUTER JOIN
                       dbo.Q_FROOSH_DAYLY_CHEK_USER(@dt1, @dt2, @USER) Q_FROOSH_DAYLY_CHEK_USER ON 
                       Q_FOROSH_DAYLY_HED_USER.NUMBER = Q_FROOSH_DAYLY_CHEK_USER.NUMBER )
