CREATE FUNCTION [dbo].[Q_FROOSH_DAYLY]
(@Forms___F_MENU_KHFR___DT1 bigint,
@Forms___F_MENU_KHFR___DT2 bigint,
@Forms___F_MENU_KHFR___MMOIN NVARCHAR(20))
RETURNS TABLE
AS
RETURN ( SELECT     Q_FOROSH_DAYLY_HED.DATE_N, Q_FOROSH_DAYLY_HED.NUMBER, Q_FOROSH_DAYLY_HED.SumOfM_NAGHD, 
                      Q_FOROSH_DAYLY_HED.SumOfMABL_VAR, Q_FOROSH_DAYLY_HED.SumOfMABL_HAV, Q_FOROSH_DAYLY_HED.SumOfMABL_HAZ, 
                      Q_FOROSH_DAYLY_HED.SumOfTAKHFIF, Q_FOROSH_DAYLY_HED.hes, Q_FOROSH_DAYLY_HED.NAME, Q_FROOSH_DAYLY_CHEK.SumOfMABL, 
                      ISNULL(Q_FROOSH_DAYLY_FCT.SumOfMABL_K, 0) AS SumOfMABL_K, ' ' AS kk, Q_FOROSH_DAYLY_HED.TAG, Q_FOROSH_DAYLY_HED.SMBAA, 
                      Q_FOROSH_DAYLY_HED.CUST_KIND
FROM         dbo.Q_FOROSH_DAYLY_HED(@Forms___F_MENU_KHFR___DT1, @Forms___F_MENU_KHFR___DT2, @Forms___F_MENU_KHFR___MMOIN) 
                      Q_FOROSH_DAYLY_HED LEFT OUTER JOIN
                      dbo.Q_FROOSH_DAYLY_CHEK(@Forms___F_MENU_KHFR___DT1, @Forms___F_MENU_KHFR___DT2, @Forms___F_MENU_KHFR___MMOIN) 
                      Q_FROOSH_DAYLY_CHEK ON Q_FOROSH_DAYLY_HED.TAG = Q_FROOSH_DAYLY_CHEK.TAG AND 
                      Q_FOROSH_DAYLY_HED.NUMBER = Q_FROOSH_DAYLY_CHEK.NUMBER LEFT OUTER JOIN
                      dbo.Q_FROOSH_DAYLY_FCT(@Forms___F_MENU_KHFR___DT1, @Forms___F_MENU_KHFR___DT2, @Forms___F_MENU_KHFR___MMOIN) 
                      Q_FROOSH_DAYLY_FCT ON Q_FOROSH_DAYLY_HED.TAG = Q_FROOSH_DAYLY_FCT.TAG AND 
                      Q_FOROSH_DAYLY_HED.NUMBER = Q_FROOSH_DAYLY_FCT.NUMBER )
