CREATE FUNCTION [dbo].[Q_FROOSH_CUSTOMER_mba2]
(@DT1 bigint,
@DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     Q_FROOSH_DAYLY_HED3_mba2.hes, Q_FROOSH_DAYLY_HED3_mba2.NAME, QSL_FROOSH_DTL_mba2.FROOSH, 
                      Q_FROOSH_DAYLY_HED3_mba2.SumOfTAKHFIF, QSL_FROOSH_DTL_mba2.FROOSH - Q_FROOSH_DAYLY_HED3_mba2.SumOfTAKHFIF AS FROOSHKH, 
                      Q_FROOSH_DAYLY_HED3_mba2.SMBAA, 
                      QSL_FROOSH_DTL_mba2.FROOSH - Q_FROOSH_DAYLY_HED3_mba2.SumOfTAKHFIF + Q_FROOSH_DAYLY_HED3_mba2.SMBAA AS GHABEL, 1 AS KK, 
                      Q_FROOSH_DAYLY_HED3_mba2.SADER
FROM         dbo.QSL_FROOSH_DTL_mba2(@DT1, @DT2) QSL_FROOSH_DTL_mba2 INNER JOIN
                      dbo.Q_FROOSH_DAYLY_HED3_mba2(@DT1, @DT2) Q_FROOSH_DAYLY_HED3_mba2 ON 
                      QSL_FROOSH_DTL_mba2.CUST_NO = Q_FROOSH_DAYLY_HED3_mba2.hes )
