CREATE  FUNCTION [dbo].[Q_FROOSH_CUSTOMER_mba]
 (@DT1 bigint,
 @DT2 bigint)
 RETURNS TABLE
 AS
 RETURN ( SELECT     Q_FROOSH_DAYLY_HED3_mba.hes, Q_FROOSH_DAYLY_HED3_mba.NAME, QSL_FROOSH_DTL_mba.FROOSH, Q_FROOSH_DAYLY_HED3_mba.SumOfTAKHFIF, 
                       QSL_FROOSH_DTL_mba.FROOSH - Q_FROOSH_DAYLY_HED3_mba.SumOfTAKHFIF AS FROOSHKH, Q_FROOSH_DAYLY_HED3_mba.SMBAA, 
                       QSL_FROOSH_DTL_mba.FROOSH - Q_FROOSH_DAYLY_HED3_mba.SumOfTAKHFIF + Q_FROOSH_DAYLY_HED3_mba.SMBAA AS GHABEL, 1 AS KK
 FROM         dbo.QSL_FROOSH_DTL_mba(@DT1, @DT2) QSL_FROOSH_DTL_mba INNER JOIN
                       dbo.Q_FROOSH_DAYLY_HED3_mba(@DT1, @DT2) Q_FROOSH_DAYLY_HED3_mba ON QSL_FROOSH_DTL_mba.CUST_NO = Q_FROOSH_DAYLY_HED3_mba.hes )
