CREATE FUNCTION [dbo].[Q_GARDESH_KHFR_MAND]
(@Forms___F_MENU_KOL_MOIN_TAFZIL___DT1 BIGINT,
@Forms___F_MENU_KOL_MOIN_TAFZIL___HTTAF nvarchar(40))
RETURNS TABLE
AS
RETURN ( SELECT     @Forms___F_MENU_KOL_MOIN_TAFZIL___DT1 AS DATE_S, 0 AS n_s, HES, NAME, 'مانده تا اين تاريخ' AS SHARH, SUM(BED - BES) AS MAND, 
                      @Forms___F_MENU_KOL_MOIN_TAFZIL___DT1 AS SARDATE, 0 AS MABL, 0 AS MAS, 0 AS BS, 0 AS BE, SUM(id) AS Expr1
FROM         dbo.Q_GARDESH_KHFR_MAND_SUB(@Forms___F_MENU_KOL_MOIN_TAFZIL___DT1, @Forms___F_MENU_KOL_MOIN_TAFZIL___HTTAF) 
                      Q_GARDESH_KHFR_MAND_SUB
GROUP BY HES, NAME )
