CREATE FUNCTION [dbo].[Q_KHARED_CUSTOMER]
 (@DT1 nvarchar(50),
 @DT2 nvarchar(50))
 RETURNS TABLE
 AS
 RETURN ( SELECT     Q_KHARED_DAYLY_HED3.hes, Q_KHARED_DAYLY_HED3.NAME, Q_KHARED_DTL.KHARED, Q_KHARED_DAYLY_HED3.SumOfTAKHFIF, 
                       Q_KHARED_DTL.KHARED - Q_KHARED_DAYLY_HED3.SumOfTAKHFIF AS KHAREDKH, Q_KHARED_DAYLY_HED3.SMBAA, 
                       Q_KHARED_DTL.KHARED - Q_KHARED_DAYLY_HED3.SumOfTAKHFIF + Q_KHARED_DAYLY_HED3.SMBAA AS GHABEL, 1 AS KK, 
                       Q_KHARED_DAYLY_HED3.ADDRESS, Q_KHARED_DAYLY_HED3.CITY, Q_KHARED_DAYLY_HED3.CODE_E, Q_KHARED_DAYLY_HED3.ECODE, 
                       Q_KHARED_DAYLY_HED3.IYALAT, Q_KHARED_DAYLY_HED3.MCODEM, Q_KHARED_DAYLY_HED3.MOBILE, Q_KHARED_DAYLY_HED3.PCODE, 
                       Q_KHARED_DAYLY_HED3.TEL, Q_KHARED_DAYLY_HED3.TOZIH
 FROM         dbo.Q_KHARED_DTL(@DT1, @DT2) Q_KHARED_DTL INNER JOIN
                       dbo.Q_KHARED_DAYLY_HED3(@DT1, @DT2) Q_KHARED_DAYLY_HED3 ON Q_KHARED_DTL.CUST_NO = Q_KHARED_DAYLY_HED3.hes )
