CREATE FUNCTION [dbo].[Q_KHARED_DTL_BZ]
 (@DT1 bigint,
 @DT2 bigint)
 RETURNS TABLE
 AS
 RETURN ( SELECT     dbo.HEAD_LST.CUST_NO, SUM(dbo.INVO_LST.MABL_K) AS KHARED
 FROM         dbo.HEAD_LST INNER JOIN
                       dbo.INVO_LST ON dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG
 WHERE     (dbo.HEAD_LST.DATE_N BETWEEN @DT1 AND @DT2)
 GROUP BY dbo.HEAD_LST.TAG, dbo.HEAD_LST.CUST_NO
 HAVING      (dbo.HEAD_LST.TAG = 1) )
