CREATE FUNCTION [dbo].[Q_KHARED_CUSTOMER_BZ]
 (@DT1 nvarchar(50),
 @DT2 nvarchar(50))
 RETURNS TABLE
 AS
 RETURN ( SELECT     Q_KHARED_DAYLY_HED.hes, Q_KHARED_DAYLY_HED.NAME, Q_KHARED_DTL_BZ.KHARED, Q_KHARED_DAYLY_HED.SumOfTAKHFIF, 
                       Q_KHARED_DTL_BZ.KHARED - Q_KHARED_DAYLY_HED.SumOfTAKHFIF AS KHAREDKH, Q_KHARED_DAYLY_HED.SMBAA, 
                       Q_KHARED_DTL_BZ.KHARED - Q_KHARED_DAYLY_HED.SumOfTAKHFIF + Q_KHARED_DAYLY_HED.SMBAA AS GHABEL, 1 AS KK, 
                       Q_KHARED_DAYLY_HED.ADDRESS, Q_KHARED_DAYLY_HED.CITY, Q_KHARED_DAYLY_HED.CODE_E, Q_KHARED_DAYLY_HED.ECODE, 
                       Q_KHARED_DAYLY_HED.IYALAT, Q_KHARED_DAYLY_HED.MCODEM, Q_KHARED_DAYLY_HED.MOBILE, Q_KHARED_DAYLY_HED.PCODE, 
                       Q_KHARED_DAYLY_HED.TEL, Q_KHARED_DAYLY_HED.TOZIH
 FROM         dbo.Q_KHARED_DTL_BZ(@DT1, @DT2) Q_KHARED_DTL_BZ INNER JOIN
                       dbo.Q_KHARED_DAYLY_HED(@DT1, @DT2, '%') Q_KHARED_DAYLY_HED ON Q_KHARED_DTL_BZ.CUST_NO = Q_KHARED_DAYLY_HED.hes )
