CREATE FUNCTION [dbo].[Q_LIST_FROOSH_DAILY2]
(@DT1 bigint,
@DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     dbo.HEAD_LST.NUMBER, SUM(dbo.HEAD_LST.M_NAGHD) AS SumOfM_NAGHD, SUM(dbo.HEAD_LST.MABL_HAV) AS SumOfMABL_HAV, 
                      SUM(dbo.HEAD_LST.MABL_HAZ) AS SumOfMABL_HAZ, SUM(dbo.HEAD_LST.TAKHFIF) AS SumOfTAKHFIF, dbo.CUST_HESAB.NAME, 
                      dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.DEPATMAN, dbo.HEAD_LST.USER_NAME, dbo.HEAD_LST.SHIFT, dbo.HEAD_LST.TAG, dbo.CUST_HESAB.hes, 
                      dbo.CUST_HESAB.ECODE, SUM(dbo.HEAD_LST.MBAA) AS SMBAA, dbo.HEAD_LST.MOLAH, dbo.CUST_HESAB.TEL, dbo.HEAD_LST.CUST_KIND, 
                      dbo.HEAD_LST.MOIN_HAV, dbo.HEAD_LST.MOIN_HAZ, dbo.HEAD_LST.MOIN_VAR, dbo.HEAD_LST.MABL_VAR AS SumOfMABL_VAR
FROM         dbo.HEAD_LST INNER JOIN
                      dbo.CUST_HESAB ON dbo.HEAD_LST.CUST_NO = dbo.CUST_HESAB.hes
WHERE     (dbo.HEAD_LST.TAG = 2 OR
                      dbo.HEAD_LST.TAG = 14) AND (dbo.HEAD_LST.DATE_N BETWEEN @DT1 AND @DT2)
GROUP BY dbo.HEAD_LST.NUMBER, dbo.CUST_HESAB.NAME, dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.DEPATMAN, dbo.HEAD_LST.USER_NAME, 
                      dbo.HEAD_LST.SHIFT, dbo.HEAD_LST.TAG, dbo.CUST_HESAB.hes, dbo.CUST_HESAB.ECODE, dbo.HEAD_LST.MOLAH, dbo.CUST_HESAB.TEL, 
                      dbo.HEAD_LST.CUST_KIND, dbo.HEAD_LST.MOIN_HAV, dbo.HEAD_LST.MOIN_HAZ, dbo.HEAD_LST.MOIN_VAR, dbo.HEAD_LST.MABL_VAR )
