 CREATE FUNCTION dbo.Q_LIST_FCT
  (@DT1 bigint,
  @DT2 bigint)
  RETURNS TABLE
  AS
  RETURN ( SELECT     dbo.HEAD_LST.NUMBER, SUM(dbo.INVO_LST.MABL_K) AS SumOfMABL_K, SUM(dbo.INVO_LST.IMBAA) AS SIMBAA, dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.MOLAH, 
                        dbo.HEAD_LST.TAG
  FROM         dbo.HEAD_LST INNER JOIN
                        dbo.INVO_LST ON dbo.HEAD_LST.TAG - 11 = dbo.INVO_LST.TAG AND dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER
  GROUP BY dbo.HEAD_LST.NUMBER, dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.MOLAH, dbo.HEAD_LST.TAG
  HAVING      (dbo.HEAD_LST.DATE_N BETWEEN @DT1 AND @DT2) AND (dbo.HEAD_LST.TAG = 13)
  UNION
  SELECT     dbo.HEAD_LST.NUMBER, SUM(dbo.INVO_LST.MABL_K) AS SumOfMABL_K, SUM(dbo.INVO_LST.IMBAA) AS SIMBAA, dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.MOLAH, 
                        dbo.HEAD_LST.TAG
  FROM         dbo.HEAD_LST INNER JOIN
                        dbo.INVO_LST ON dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG AND dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER
  GROUP BY dbo.HEAD_LST.NUMBER, dbo.HEAD_LST.DATE_N, dbo.HEAD_LST.MOLAH, dbo.HEAD_LST.TAG
  HAVING      (dbo.HEAD_LST.DATE_N BETWEEN @DT1 AND @DT2) AND (dbo.HEAD_LST.TAG = 14) )
 
 

