CREATE FUNCTION [dbo].[Q_LIST_DALY]
(@DT1 BIGINT,
@DT2 BIGINT)
RETURNS TABLE
AS
RETURN ( SELECT     TOP 100 PERCENT Q_LIST_FROOSH_DAILY2.DATE_N, Q_LIST_FROOSH_DAILY2.NUMBER, Q_LIST_FROOSH_DAILY2.SumOfM_NAGHD, 
                      Q_LIST_FROOSH_DAILY2.SumOfMABL_VAR, Q_LIST_FROOSH_DAILY2.SumOfMABL_HAV, Q_LIST_FROOSH_DAILY2.SumOfMABL_HAZ, 
                      Q_LIST_FROOSH_DAILY2.SumOfTAKHFIF, Q_LIST_FROOSH_DAILY2.hes, Q_LIST_FROOSH_DAILY2.NAME, Q_LIST_FROOSH_DAILY2.DEPATMAN, 
                      Q_LIST_FROOSH_DAILY2.USER_NAME, Q_LIST_FROOSH_DAILY2.SHIFT, dbo.SHIFT.SHNAME, dbo.DEPART.DEPNAME, 
                      RIGHT(Q_LIST_FROOSH_DAILY2.USER_NAME, LEN(Q_LIST_FROOSH_DAILY2.USER_NAME) - 2) AS USS, '""' AS kk, 
                      ISNULL(dbo.Q_LIST_FCT2.SumOfMABL_K, 0) AS jamf, ISNULL(Q_LIST_FROOSH_DAYLY_CHK2.SumOfMABL, 0) AS jamch, 
                      Q_LIST_FROOSH_DAILY2.ECODE, Q_LIST_FROOSH_DAILY2.SMBAA, ISNULL(dbo.Q_LIST_FCT2.SumOfMABL_K, 0) 
                      + Q_LIST_FROOSH_DAILY2.SMBAA + Q_LIST_FROOSH_DAILY2.SumOfMABL_HAZ - Q_LIST_FROOSH_DAILY2.SumOfTAKHFIF - Q_LIST_FROOSH_DAILY2.SumOfMABL_HAV
                       - Q_LIST_FROOSH_DAILY2.SumOfMABL_VAR - Q_LIST_FROOSH_DAILY2.SumOfM_NAGHD - ISNULL(Q_LIST_FROOSH_DAYLY_CHK2.SumOfMABL, 
                      0) AS mand, Q_LIST_FROOSH_DAILY2.MOLAH, Q_LIST_FROOSH_DAILY2.TEL, Q_LIST_FROOSH_DAILY2.CUST_KIND, dbo.CUSTKIND.CUSTKNAME, 
                      Q_LIST_FROOSH_DAILY2.TAG, Q_LIST_FROOSH_DAILY2.MOIN_HAV, Q_LIST_FROOSH_DAILY2.MOIN_HAZ, Q_LIST_FROOSH_DAILY2.MOIN_VAR, 
                      dbo.CUST_HESAB.ADDRESS, dbo.CUST_HESAB.PCODE, dbo.CUST_HESAB.IYALAT, dbo.CUST_HESAB.CITY, dbo.CUST_HESAB.MCODEM, 
                      dbo.CUST_HESAB.TOZIH, dbo.CUST_HESAB.MOBILE, dbo.CUST_HESAB.CODE_E, ISNULL(dbo.Q_LIST_FCT2.SumOfMABL_K, 0) 
                      + Q_LIST_FROOSH_DAILY2.SMBAA + Q_LIST_FROOSH_DAILY2.SumOfMABL_HAZ - Q_LIST_FROOSH_DAILY2.SumOfTAKHFIF AS GHABEL
FROM         dbo.DEPART INNER JOIN
                      dbo.Q_LIST_FROOSH_DAILY2(@DT1, @DT2) Q_LIST_FROOSH_DAILY2 ON 
                      dbo.DEPART.DEPATMAN = Q_LIST_FROOSH_DAILY2.DEPATMAN INNER JOIN
                      dbo.SHIFT ON Q_LIST_FROOSH_DAILY2.SHIFT = dbo.SHIFT.SHIFT_ID INNER JOIN
                      dbo.CUST_HESAB ON Q_LIST_FROOSH_DAILY2.hes = dbo.CUST_HESAB.hes LEFT OUTER JOIN
                      dbo.Q_LIST_FROOSH_DAYLY_CHK2(@DT1, @DT2) Q_LIST_FROOSH_DAYLY_CHK2 ON 
                      Q_LIST_FROOSH_DAILY2.TAG = Q_LIST_FROOSH_DAYLY_CHK2.TAG AND 
                      Q_LIST_FROOSH_DAILY2.NUMBER = Q_LIST_FROOSH_DAYLY_CHK2.NUMBER LEFT OUTER JOIN
                      dbo.Q_LIST_FCT2 ON Q_LIST_FROOSH_DAILY2.TAG = dbo.Q_LIST_FCT2.TAG AND 
                      Q_LIST_FROOSH_DAILY2.NUMBER = dbo.Q_LIST_FCT2.NUMBER LEFT OUTER JOIN
                      dbo.CUSTKIND ON Q_LIST_FROOSH_DAILY2.CUST_KIND = dbo.CUSTKIND.CUST_COD
WHERE     (Q_LIST_FROOSH_DAILY2.DATE_N BETWEEN @DT1 AND @DT2)
ORDER BY Q_LIST_FROOSH_DAILY2.NUMBER, Q_LIST_FROOSH_DAILY2.DATE_N )
