CREATE FUNCTION [dbo].[Q_TAFKIK_TAFZ_CHK]
 (@Forms___F_MENU_DATE_KOL_MOIN_TAFKIK___HKOL nvarchar(50),
 @Forms___F_MENU_DATE_KOL_MOIN_TAFKIK___HMOIN1 nvarchar(50),
 @Forms___F_MENU_DATE_KOL_MOIN_TAFKIK___TAFZ1 nvarchar(50),
 @Forms___F_MENU_DATE_KOL_MOIN_TAFKIK___TAFZ2 nvarchar(50),
 @Forms___F_MENU_DATE_KOL_MOIN_TAFKIK___DT1 nvarchar(50),
 @Forms___F_MENU_DATE_KOL_MOIN_TAFKIK___DT2 nvarchar(50))
 RETURNS TABLE
 AS
 RETURN ( SELECT     Q_TAFKIK_MOIN.HES_K, Q_TAFKIK_MOIN.HES_M, Q_TAFKIK_MOIN.HES_T, Q_TAFKIK_MOIN.SumOfBED, Q_TAFKIK_MOIN.SumOfBES, 
                       Q_TAFKIK_MOIN.BEDBES, Q_TAFKIK_MOIN.NAME, Q_TAFKIK_MOIN.DNAME, Q_TAFKIK_MOIN.hname, Q_TAFKIK_MOIN.NAMET, 
                       dbo.CHEKS_NOPASS_PERS.MABC, dbo.CHEKS_NOPASS_PERS.FHES, Q_TAFKIK_MOIN.HES
 FROM         dbo.Q_TAFKIK_MOIN(@Forms___F_MENU_DATE_KOL_MOIN_TAFKIK___HKOL, @Forms___F_MENU_DATE_KOL_MOIN_TAFKIK___HMOIN1, 
                       @Forms___F_MENU_DATE_KOL_MOIN_TAFKIK___TAFZ1, @Forms___F_MENU_DATE_KOL_MOIN_TAFKIK___TAFZ2, 
                       @Forms___F_MENU_DATE_KOL_MOIN_TAFKIK___DT1, @Forms___F_MENU_DATE_KOL_MOIN_TAFKIK___DT2) Q_TAFKIK_MOIN LEFT OUTER JOIN
                       dbo.CHEKS_NOPASS_PERS ON Q_TAFKIK_MOIN.HES = dbo.CHEKS_NOPASS_PERS.FHES )
