CREATE FUNCTION [dbo].[QSL_lIST_INVOICE_KHARED]
(@Forms___F_MENU_KHFR___DT1 nvarchar(20),
@Forms___F_MENU_KHFR___DT2 nvarchar(20),
@Forms___F_MENU_KHFR___MMOIN nvarchar(20))
RETURNS TABLE
AS
RETURN ( SELECT     HEAD_CHEK_KHARED.NUMBER, HEAD_CHEK_KHARED.TAG, HEAD_CHEK_KHARED.DATE_N, 
                      HEAD_CHEK_KHARED.CUST_NO, HEAD_CHEK_KHARED.ANBAR, HEAD_CHEK_KHARED.NUMBER1, 
                      HEAD_CHEK_KHARED.TAH, HEAD_CHEK_KHARED.MAS, HEAD_CHEK_KHARED.VAS, HEAD_CHEK_KHARED.N_S, 
                      HEAD_CHEK_KHARED.MOLAH, HEAD_CHEK_KHARED.M_NAGHD, HEAD_CHEK_KHARED.MABL_VAR, 
                      HEAD_CHEK_KHARED.MOIN_VAR, HEAD_CHEK_KHARED.MABL_HAV, HEAD_CHEK_KHARED.MOIN_HAV, 
                      HEAD_CHEK_KHARED.MABL_HAZ, HEAD_CHEK_KHARED.MOIN_HAZ, HEAD_CHEK_KHARED.TAKHFIF, 
                      HEAD_CHEK_KHARED.MOIN_KHF, HEAD_CHEK_KHARED.ANBARF, HEAD_CHEK_KHARED.FNUMCO, 
                      dbo.INVO_LST.NUMBER AS INUMBER, dbo.INVO_LST.TAG AS ITAG, dbo.INVO_LST.ANBAR AS IANBAR, 
                      dbo.INVO_LST.RADIF, dbo.INVO_LST.CODE, dbo.INVO_LST.MEGH, dbo.INVO_LST.MEGHk, dbo.INVO_LST.MEGH_MAR, 
                      dbo.INVO_LST.MANDAH, dbo.INVO_LST.MABL, dbo.INVO_LST.MABL_K, dbo.INVO_LST.FROM_A, 
                      dbo.INVO_LST.N_RASID, dbo.INVO_LST.MEGH_R, dbo.INVO_LST.RADAH, dbo.INVO_LST.SANAD_NO, 
                      dbo.INVO_LST.CUST_NO AS ICUST_NO, dbo.INVO_LST.ANBARF AS IANBARF, dbo.INVO_LST.VAHED_K, 
                      dbo.TCOD_ANBAR.NAMES, dbo.STUF_DEF.NAME, dbo.TCOD_VAHEDS.NAMES AS TNAMES, 
                      dbo.CUST_HESAB.hes AS BESN, dbo.CUST_HESAB.NAME AS CNAME, dbo.CUST_HESAB.ADDRESS, 
                      dbo.CUST_HESAB.TEL, HEAD_CHEK_KHARED.MAB, HEAD_CHEK_KHARED.CountOfMABL
FROM         dbo.TCOD_VAHEDS INNER JOIN
                      dbo.INVO_LST ON dbo.TCOD_VAHEDS.CODE = dbo.INVO_LST.VAHED_K INNER JOIN
                      dbo.HEAD_CHEK_KHARED() HEAD_CHEK_KHARED ON dbo.INVO_LST.NUMBER = HEAD_CHEK_KHARED.NUMBER AND 
                      dbo.INVO_LST.TAG = HEAD_CHEK_KHARED.TAG INNER JOIN
                      dbo.CUST_HESAB ON HEAD_CHEK_KHARED.CUST_NO = dbo.CUST_HESAB.hes INNER JOIN
                      dbo.TCOD_ANBAR ON dbo.INVO_LST.ANBAR = dbo.TCOD_ANBAR.CODE INNER JOIN
                      dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE
WHERE     (HEAD_CHEK_KHARED.TAG = 1) AND (HEAD_CHEK_KHARED.DATE_N BETWEEN 
                      @Forms___F_MENU_KHFR___DT1 AND @Forms___F_MENU_KHFR___DT2) AND 
                      (dbo.CUST_HESAB.hes LIKE @Forms___F_MENU_KHFR___MMOIN) )
