CREATE FUNCTION [dbo].[QSL_lIST_INVOICE_FROOSH]
(@Forms___F_MENU_KHFR___DT1 nvarchar(20),
@Forms___F_MENU_KHFR___DT2 nvarchar(20),
@Forms___F_MENU_KHFR___MMOIN nvarchar(20))
RETURNS TABLE
AS
RETURN ( SELECT     HEAD_CHEK_FROOSH.NUMBER, HEAD_CHEK_FROOSH.TAG, HEAD_CHEK_FROOSH.DATE_N, HEAD_CHEK_FROOSH.CUST_NO, 
                      HEAD_CHEK_FROOSH.ANBAR, HEAD_CHEK_FROOSH.NUMBER1, HEAD_CHEK_FROOSH.TAH, HEAD_CHEK_FROOSH.MAS, 
                      HEAD_CHEK_FROOSH.VAS, HEAD_CHEK_FROOSH.N_S, HEAD_CHEK_FROOSH.MOLAH, HEAD_CHEK_FROOSH.M_NAGHD, 
                      HEAD_CHEK_FROOSH.MABL_VAR, HEAD_CHEK_FROOSH.MOIN_VAR, HEAD_CHEK_FROOSH.MABL_HAV, HEAD_CHEK_FROOSH.MOIN_HAV, 
                      HEAD_CHEK_FROOSH.MABL_HAZ, HEAD_CHEK_FROOSH.MOIN_HAZ, HEAD_CHEK_FROOSH.TAKHFIF, HEAD_CHEK_FROOSH.MOIN_KHF, 
                      HEAD_CHEK_FROOSH.ANBARF, HEAD_CHEK_FROOSH.FNUMCO, dbo.INVO_LST.NUMBER AS INUMBER, dbo.INVO_LST.TAG AS ITAG, 
                      dbo.INVO_LST.ANBAR AS IANBAR, dbo.INVO_LST.RADIF, dbo.TCOD_VAHEDS.CODE, dbo.INVO_LST.MEGH, dbo.INVO_LST.MEGHk, 
                      dbo.INVO_LST.MEGH_MAR, dbo.INVO_LST.MANDAH, dbo.INVO_LST.MABL, dbo.INVO_LST.MABL_K, dbo.INVO_LST.FROM_A, dbo.INVO_LST.N_RASID, 
                      dbo.INVO_LST.MEGH_R, dbo.INVO_LST.RADAH, dbo.INVO_LST.SANAD_NO, dbo.INVO_LST.CUST_NO AS ICUST_NO, 
                      dbo.INVO_LST.ANBARF AS IANBARF, dbo.INVO_LST.VAHED_K, dbo.CUST_HESAB.hes AS BEDN, dbo.CUST_HESAB.NAME, 
                      dbo.CUST_HESAB.ADDRESS, dbo.CUST_HESAB.TEL, dbo.TCOD_ANBAR.NAMES, dbo.STUF_DEF.NAME AS SNAME, 
                      dbo.TCOD_VAHEDS.NAMES AS TNAMES, HEAD_CHEK_FROOSH.mab, HEAD_CHEK_FROOSH.CountOfMABL, 
                      dbo.INVO_LST.MEGH_MAR * dbo.INVO_LST.MABL AS mabl_mar, HEAD_CHEK_FROOSH.DEPNAME, HEAD_CHEK_FROOSH.MBAA, 
                      dbo.INVO_LST.N_KOL, dbo.INVO_LST.N_MOIN, dbo.INVO_LST.TKHN
FROM         dbo.INVO_LST INNER JOIN
                      dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE INNER JOIN
                      dbo.TCOD_VAHEDS ON dbo.INVO_LST.VAHED_K = dbo.TCOD_VAHEDS.CODE INNER JOIN
                      dbo.HEAD_CHEK_FROOSH() HEAD_CHEK_FROOSH ON dbo.INVO_LST.NUMBER = HEAD_CHEK_FROOSH.NUMBER AND 
                      dbo.INVO_LST.TAG = HEAD_CHEK_FROOSH.TAG INNER JOIN
                      dbo.CUST_HESAB ON HEAD_CHEK_FROOSH.CUST_NO = dbo.CUST_HESAB.hes INNER JOIN
                      dbo.TCOD_ANBAR ON dbo.INVO_LST.ANBAR = dbo.TCOD_ANBAR.CODE
WHERE     (HEAD_CHEK_FROOSH.TAG = 2) AND (HEAD_CHEK_FROOSH.DATE_N BETWEEN @Forms___F_MENU_KHFR___DT1 AND 
                      @Forms___F_MENU_KHFR___DT2) AND (dbo.CUST_HESAB.hes LIKE @Forms___F_MENU_KHFR___MMOIN) )
