CREATE FUNCTION [dbo].[QSL_LIST_INVOICE_KHAREDG]
 (@Forms___F_MENU_KHFR___DT1 nvarchar(20),
 @Forms___F_MENU_KHFR___DT2 nvarchar(20),
 @Forms___F_MENU_KHFR___MMOIN nvarchar(20))
 RETURNS TABLE
 AS
 RETURN ( SELECT     dbo.HEAD_CHEK_KHAREDG.NUMBER, dbo.HEAD_CHEK_KHAREDG.TAG, dbo.HEAD_CHEK_KHAREDG.DATE_N, 
                       dbo.HEAD_CHEK_KHAREDG.CUST_NO, dbo.HEAD_CHEK_KHAREDG.ANBAR, dbo.HEAD_CHEK_KHAREDG.NUMBER1, 
                       dbo.HEAD_CHEK_KHAREDG.TAH, dbo.HEAD_CHEK_KHAREDG.MAS, dbo.HEAD_CHEK_KHAREDG.VAS, dbo.HEAD_CHEK_KHAREDG.N_S, 
                       dbo.HEAD_CHEK_KHAREDG.MOLAH, dbo.HEAD_CHEK_KHAREDG.M_NAGHD, dbo.HEAD_CHEK_KHAREDG.MABL_VAR, 
                       dbo.HEAD_CHEK_KHAREDG.MOIN_VAR, dbo.HEAD_CHEK_KHAREDG.MABL_HAV, dbo.HEAD_CHEK_KHAREDG.MOIN_HAV, 
                       dbo.HEAD_CHEK_KHAREDG.MABL_HAZ, dbo.HEAD_CHEK_KHAREDG.MOIN_HAZ, dbo.HEAD_CHEK_KHAREDG.TAKHFIF, 
                       dbo.HEAD_CHEK_KHAREDG.MOIN_KHF, dbo.HEAD_CHEK_KHAREDG.ANBARF, dbo.HEAD_CHEK_KHAREDG.FNUMCO, 
                       dbo.INVO_LST.NUMBER AS INUMBER, dbo.INVO_LST.TAG AS ITAG, dbo.INVO_LST.ANBAR AS IANBAR, dbo.INVO_LST.RADIF, dbo.INVO_LST.CODE, 
                       dbo.INVO_LST.MEGH, dbo.INVO_LST.MEGHk, dbo.INVO_LST.MEGH_MAR, dbo.INVO_LST.MANDAH, dbo.INVO_LST.MABL, dbo.INVO_LST.MABL_K, 
                       dbo.INVO_LST.FROM_A, dbo.INVO_LST.N_RASID, dbo.INVO_LST.MEGH_R, dbo.INVO_LST.RADAH, dbo.INVO_LST.SANAD_NO, 
                       dbo.INVO_LST.CUST_NO AS ICUST_NO, dbo.INVO_LST.ANBARF AS IANBARF, dbo.INVO_LST.VAHED_K, dbo.TCOD_ANBAR.NAMES, 
                       dbo.STUF_DEF.NAME, dbo.TCOD_VAHEDS.NAMES AS TNAMES, dbo.CUST_HESAB.hes AS BESN, dbo.CUST_HESAB.NAME AS CNAME, 
                       dbo.CUST_HESAB.ADDRESS, dbo.CUST_HESAB.TEL, dbo.HEAD_CHEK_KHAREDG.MAB, dbo.HEAD_CHEK_KHAREDG.CountOfMABL
 FROM         dbo.TCOD_VAHEDS INNER JOIN
                       dbo.INVO_LST ON dbo.TCOD_VAHEDS.CODE = dbo.INVO_LST.VAHED_K INNER JOIN
                       dbo.HEAD_CHEK_KHAREDG ON dbo.INVO_LST.NUMBER = dbo.HEAD_CHEK_KHAREDG.NUMBER AND 
                       dbo.INVO_LST.TAG = dbo.HEAD_CHEK_KHAREDG.TAG - 11 INNER JOIN
                       dbo.CUST_HESAB ON dbo.HEAD_CHEK_KHAREDG.CUST_NO = dbo.CUST_HESAB.hes INNER JOIN
                       dbo.TCOD_ANBAR ON dbo.INVO_LST.ANBAR = dbo.TCOD_ANBAR.CODE INNER JOIN
                       dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE
 WHERE     (dbo.CUST_HESAB.hes LIKE @Forms___F_MENU_KHFR___MMOIN) AND (dbo.HEAD_CHEK_KHAREDG.DATE_N BETWEEN 
                       @Forms___F_MENU_KHFR___DT1 AND @Forms___F_MENU_KHFR___DT2) )
