CREATE FUNCTION [dbo].[QSL_FROOSH_DTL_mba2]
(@DT1 bigint,
@DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     dbo.HEAD_LST.CUST_NO, SUM(dbo.INVO_LST.MABL_K) AS FROOSH
FROM         dbo.HEAD_LST INNER JOIN
                      dbo.INVO_LST ON dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_LST.TAG - 11 = dbo.INVO_LST.TAG
WHERE     (dbo.HEAD_LST.DATE_N BETWEEN @DT1 AND @DT2) AND (dbo.HEAD_LST.TICMBAA = 0)
GROUP BY dbo.HEAD_LST.TAG, dbo.HEAD_LST.CUST_NO
HAVING      (dbo.HEAD_LST.TAG = 13) )
