CREATE FUNCTION [dbo].[R_LIST_MEHMAN](@Forms___F_MENU_HOTEL___DT1 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     ID, MNAME, MFAMILY, FATHER, KNOW, MSODUR, BDATE, TAHSIL, JOB, GHASD, SCITY, DCITY, ENGIN, ADDRESS, VDATE AS VDATEE, KDATE, 
                      HAMRAH, ROOMN, EZAFAH, MABLPISH, MOLAH, NAHVAH, SEX, TAFZ, IDH, SAZMANM, TABEI
FROM         dbo.MEHMAN
WHERE     (VDATE = @Forms___F_MENU_HOTEL___DT1) )
