CREATE FUNCTION [dbo].[R_LIST_MEHMAN_KHORUG](@Forms___F_MENU_HOTEL___DT1 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     ID, MNAME, MFAMILY, FATHER, KNOW, MSODUR, BDATE, TAHSIL, JOB, GHASD, SCITY, DCITY, ENGIN, ADDRESS, VDATE, KDATE, HAMRAH, ROOMN, 
                      EZAFAH, MABLPISH, MOLAH, NAHVAH, SEX, TAFZ, IDH, SAZMANM, TABEI, dbo.Udatediff(VDATE, KDATE) + 1 AS MODAT
FROM         dbo.MEHMAN
WHERE     (KDATE = @Forms___F_MENU_HOTEL___DT1) )
