CREATE FUNCTION [dbo].[SELECT_HOKM](@MeWDATE bigint)
RETURNS TABLE
AS
RETURN ( SELECT     dbo.WORKING.PCODE, dbo.WORKING.WDATE, dbo.WORKING.DAYS, dbo.WORKING.EZAFAH, dbo.WORKING.PADASH, dbo.WORKING.KASR_VAM, 
                      dbo.PERSONEL.SEX, dbo.PERSONEL.TAB56, dbo.PHOKM.HDATE, dbo.PHOKM.SALARY_DAYLY, dbo.PHOKM.SALARY_DAYLYB, dbo.PHOKM.HOME, 
                      dbo.PHOKM.CHILDREN, dbo.PHOKM.CONDITIONS, dbo.PHOKM.BON, dbo.PHOKM.JAZB, dbo.PHOKM.SAYER, dbo.WORKING.HAZCENTER, 
                      dbo.HEAD_MANF.NAMES, dbo.HEAD_MANF.CODE, dbo.PHOKM.MABEZ, dbo.WORKING.EZAD, dbo.WORKING.EZTAT
FROM         dbo.PERSONEL INNER JOIN
                      dbo.WORKING LEFT OUTER JOIN
                      dbo.HEAD_MANF ON dbo.WORKING.HAZCENTER = dbo.HEAD_MANF.FNUMB ON dbo.PERSONEL.CODE = dbo.WORKING.PCODE INNER JOIN
                      dbo.PHOKM ON dbo.PERSONEL.CODE = dbo.PHOKM.CODE INNER JOIN
                      dbo.LASTHOKM(@MeWDATE) LASTHOKM ON dbo.PHOKM.HONUM = LASTHOKM.MaxOfHONUM AND dbo.PHOKM.CODE = LASTHOKM.CODE
WHERE     (dbo.WORKING.WDATE = @MeWDATE) )
