CREATE FUNCTION [dbo].[SUDZIANGHEMAT](@FROOSH int,
@GHEMAT int,
@DT1 bigint,
@DT2 bigint)
RETURNS TABLE
AS
RETURN ( SELECT     MANDFROOSH.NAME, MANDFROOSH.FROOSH, 
                      dbo.UIIF(MANDFROOSH.FROOSH - (MANDGHEMATCROSS.DAST + MANDGHEMATCROSS.SARBAR + MANDGHEMATCROSS.MAVAD), N'>', 0, 
                      MANDFROOSH.FROOSH - (MANDGHEMATCROSS.DAST + MANDGHEMATCROSS.SARBAR + MANDGHEMATCROSS.MAVAD), 0) AS SUD, 
                      dbo.UIIF(MANDFROOSH.FROOSH - (MANDGHEMATCROSS.DAST + MANDGHEMATCROSS.SARBAR + MANDGHEMATCROSS.MAVAD), N'<', 0, 
                      MANDGHEMATCROSS.DAST + MANDGHEMATCROSS.SARBAR + MANDGHEMATCROSS.MAVAD - MANDFROOSH.FROOSH, 0) AS ZIAN, 
                      MANDFROOSH.HES_M, MANDGHEMATCROSS.DAST, MANDGHEMATCROSS.SARBAR, MANDGHEMATCROSS.MAVAD, 
                      MANDGHEMATCROSS.DAST + MANDGHEMATCROSS.SARBAR + MANDGHEMATCROSS.MAVAD AS GHEMAT, 
                      (MANDGHEMATCROSS.DAST + MANDGHEMATCROSS.SARBAR + MANDGHEMATCROSS.MAVAD) / dbo.GHEYMAT_TAMAM.GHEMAT AS megh
FROM         dbo.MANDFROOSH(@FROOSH, @DT1, @DT2) MANDFROOSH INNER JOIN
                      dbo.MANDGHEMATCROSS(@GHEMAT, @DT1, @DT2) MANDGHEMATCROSS ON MANDFROOSH.HES_M = MANDGHEMATCROSS.HES_M INNER JOIN
                      dbo.GHEYMAT_TAMAM ON MANDFROOSH.HES_M = dbo.GHEYMAT_TAMAM.CODE )
