create FUNCTION [dbo].[SURATMANABE]
 (@Forms___FMENU_TARAZ_4___SNDNUM1 FLOAT,
 @Forms___FMENU_TARAZ_4___DT1 FLOAT,
 @Forms___FMENU_TARAZ_4___SNDNUM2 FLOAT,
 @Forms___FMENU_TARAZ_4___DT2 FLOAT)
 RETURNS TABLE
 AS
 RETURN ( SELECT     TOP 100 PERCENT SURAT_MANABE_SUB1.daraee, SURAT_MANABE_SUB1.BEDEHE, SURAT_MANABE_SUB1.grp, SURAT_MANABE_SUB1.GR, 
                       SURAT_MANABE_SUB2.daraee AS daraeeE, SURAT_MANABE_SUB2.BEDEHE AS BEDEHEE, 
                       SURAT_MANABE_SUB2.daraee - SURAT_MANABE_SUB1.daraee AS DARAEECH, 
                       SURAT_MANABE_SUB2.BEDEHE - SURAT_MANABE_SUB1.BEDEHE AS BEDEHECH, dbo.TOTA_HES.NUMBER, dbo.TOTA_HES.NAME AS NAM, 
                       dbo.TCOD_HESGROUP.NAMES, dbo.TCOD_HESGROUP.CODE
 FROM         dbo.SURAT_MANABE_SUB1(@Forms___FMENU_TARAZ_4___SNDNUM1, @Forms___FMENU_TARAZ_4___DT1) SURAT_MANABE_SUB1 INNER JOIN
                       dbo.TOTA_HES ON SURAT_MANABE_SUB1.NUMBER = dbo.TOTA_HES.NUMBER INNER JOIN
                       dbo.SURAT_MANABE_SUB2(@Forms___FMENU_TARAZ_4___SNDNUM2, @Forms___FMENU_TARAZ_4___DT2) SURAT_MANABE_SUB2 ON 
                       dbo.TOTA_HES.NUMBER = SURAT_MANABE_SUB2.NUMBER INNER JOIN
                       dbo.TCOD_HESGROUP ON dbo.TOTA_HES.[GROUP] = dbo.TCOD_HESGROUP.CODE
 ORDER BY SURAT_MANABE_SUB1.daraee )
