CREATE FUNCTION [dbo].[SURAT_HESAB_KHAREED]
(@Forms___F_MENU_KHFR___DT1 bigint,
@Forms___F_MENU_KHFR___DT2 bigint,
@Forms___F_MENU_KHFR___HMOIN nvarchar(40))
RETURNS TABLE
AS
RETURN ( SELECT     dbo.STUF_DEF.NAME AS KALA, dbo.INVO_LST.MANDAH, dbo.INVO_LST.MABL, dbo.INVO_LST.MABL_K, dbo.INVO_LST.MEGH, dbo.INVO_LST.MEGHk, 
                      RHEAD_CHEK_KHARED2.NUMBER, RHEAD_CHEK_KHARED2.TAG, RHEAD_CHEK_KHARED2.DATE_N, RHEAD_CHEK_KHARED2.VAS, 
                      dbo.CUST_HESAB.NAME + N' - ' + RHEAD_CHEK_KHARED2.CUST_NO AS PERSON, RHEAD_CHEK_KHARED2.M_NAGHD, 
                      RHEAD_CHEK_KHARED2.MABL_VAR, RHEAD_CHEK_KHARED2.MABL_HAV, RHEAD_CHEK_KHARED2.MABL_HAZ, RHEAD_CHEK_KHARED2.TAKHFIF, 
                      RHEAD_CHEK_KHARED2.mab, dbo.UIIF(RHEAD_CHEK_KHARED2.VAS, N'=', 1, RHEAD_CHEK_KHARED2.MABL_HAZ, 0) 
                      + RHEAD_CHEK_KHARED2.MBAA AS BES, 
                      RHEAD_CHEK_KHARED2.M_NAGHD + RHEAD_CHEK_KHARED2.MABL_VAR + RHEAD_CHEK_KHARED2.MABL_HAV + RHEAD_CHEK_KHARED2.mab + dbo.UIIF(RHEAD_CHEK_KHARED2.VAS,
                       '=', 1, 0, RHEAD_CHEK_KHARED2.MABL_HAZ) + RHEAD_CHEK_KHARED2.TAKHFIF AS beD, dbo.INVO_LST.CODE, dbo.CUST_HESAB.ADDRESS, 
                      RHEAD_CHEK_KHARED2.CUST_NO, RHEAD_CHEK_KHARED2.SumOfMEGH, RHEAD_CHEK_KHARED2.SumOfMEGHk, 
                      RHEAD_CHEK_KHARED2.SumOfMABL_K, (RHEAD_CHEK_KHARED2.SumOfMABL_K + RHEAD_CHEK_KHARED2.MBAA) 
                      - (RHEAD_CHEK_KHARED2.M_NAGHD + RHEAD_CHEK_KHARED2.MABL_VAR + RHEAD_CHEK_KHARED2.MABL_HAV + RHEAD_CHEK_KHARED2.mab +
                       dbo.UIIF(RHEAD_CHEK_KHARED2.VAS, N'=', 1, 0, RHEAD_CHEK_KHARED2.MABL_HAZ) + RHEAD_CHEK_KHARED2.TAKHFIF) 
                      + dbo.UIIF(RHEAD_CHEK_KHARED2.VAS, N'=', 1, RHEAD_CHEK_KHARED2.MABL_HAZ, 0) AS MANDF, RHEAD_CHEK_KHARED2.MBAA
FROM         dbo.STUF_DEF INNER JOIN
                      dbo.RHEAD_CHEK_KHARED2(@Forms___F_MENU_KHFR___DT1, @Forms___F_MENU_KHFR___DT2, @Forms___F_MENU_KHFR___HMOIN) 
                      RHEAD_CHEK_KHARED2 INNER JOIN
                      dbo.INVO_LST ON RHEAD_CHEK_KHARED2.TAG = dbo.INVO_LST.TAG AND RHEAD_CHEK_KHARED2.NUMBER = dbo.INVO_LST.NUMBER ON 
                      dbo.STUF_DEF.CODE = dbo.INVO_LST.CODE LEFT OUTER JOIN
                      dbo.CUST_HESAB ON RHEAD_CHEK_KHARED2.CUST_NO = dbo.CUST_HESAB.hes
WHERE     (RHEAD_CHEK_KHARED2.DATE_N BETWEEN @Forms___F_MENU_KHFR___DT1 AND @Forms___F_MENU_KHFR___DT2) AND 
                      (RHEAD_CHEK_KHARED2.CUST_NO = @Forms___F_MENU_KHFR___HMOIN) )
