CREATE FUNCTION [dbo].[SURAT_HESAB_FROOSH]
(@Forms___F_MENU_KHFR___DT1 bigint,
@Forms___F_MENU_KHFR___DT2 bigint,
@Forms___F_MENU_KHFR___HMOIN nvarchar(40))
RETURNS TABLE
AS
RETURN ( SELECT     dbo.STUF_DEF.NAME AS KALA, dbo.INVO_LST.MANDAH, dbo.INVO_LST.MABL, dbo.INVO_LST.MABL_K, dbo.INVO_LST.MEGH, dbo.INVO_LST.MEGHk, 
                      RHEAD_CHEK_FROOSH2.NUMBER, RHEAD_CHEK_FROOSH2.TAG, RHEAD_CHEK_FROOSH2.DATE_N, RHEAD_CHEK_FROOSH2.VAS, 
                      RHEAD_CHEK_FROOSH2.M_NAGHD, RHEAD_CHEK_FROOSH2.MABL_VAR, RHEAD_CHEK_FROOSH2.MABL_HAV, RHEAD_CHEK_FROOSH2.MABL_HAZ, 
                      RHEAD_CHEK_FROOSH2.TAKHFIF, RHEAD_CHEK_FROOSH2.mab, dbo.UIIF(RHEAD_CHEK_FROOSH2.VAS, '=', 1, RHEAD_CHEK_FROOSH2.MABL_HAZ, 0) AS BED, 
                      RHEAD_CHEK_FROOSH2.M_NAGHD + RHEAD_CHEK_FROOSH2.MABL_VAR + RHEAD_CHEK_FROOSH2.MABL_HAV + RHEAD_CHEK_FROOSH2.mab + dbo.UIIF(RHEAD_CHEK_FROOSH2.VAS,
                       '=', 1, 0, RHEAD_CHEK_FROOSH2.MABL_HAZ) + RHEAD_CHEK_FROOSH2.TAKHFIF AS bes, dbo.INVO_LST.CODE, dbo.CUST_HESAB.ADDRESS, 
                      RHEAD_CHEK_FROOSH2.CUST_NO, RHEAD_CHEK_FROOSH2.SumOfMEGH, RHEAD_CHEK_FROOSH2.SumOfMEGHk, RHEAD_CHEK_FROOSH2.SumOfMABL_K, 
                      RHEAD_CHEK_FROOSH2.SumOfMABL_K - (RHEAD_CHEK_FROOSH2.M_NAGHD + RHEAD_CHEK_FROOSH2.MABL_VAR + RHEAD_CHEK_FROOSH2.MABL_HAV + RHEAD_CHEK_FROOSH2.mab
                       + dbo.UIIF(RHEAD_CHEK_FROOSH2.VAS, N'=', 1, 0, RHEAD_CHEK_FROOSH2.MABL_HAZ) + RHEAD_CHEK_FROOSH2.TAKHFIF) 
                      + dbo.UIIF(RHEAD_CHEK_FROOSH2.VAS, N'=', 1, RHEAD_CHEK_FROOSH2.MABL_HAZ, 0) AS MANDF, 
                      dbo.CUST_HESAB.NAME + N' - ' + RHEAD_CHEK_FROOSH2.CUST_NO AS PERSON, dbo.INVO_LST.IMBAA, dbo.INVO_LST.N_MOIN, dbo.INVO_LST.N_KOL, 
                      RHEAD_CHEK_FROOSH2.SumOfMABL_K - RHEAD_CHEK_FROOSH2.TAKHFIF + RHEAD_CHEK_FROOSH2.MMBAA AS MABKK, RHEAD_CHEK_FROOSH2.MMBAA, 
                      dbo.INVO_LST.MABL_K + dbo.INVO_LST.IMBAA - dbo.INVO_LST.N_MOIN AS MABKKK
FROM         dbo.STUF_DEF INNER JOIN
                      dbo.RHEAD_CHEK_FROOSH2(@Forms___F_MENU_KHFR___DT1, @Forms___F_MENU_KHFR___DT2, @Forms___F_MENU_KHFR___HMOIN) 
                      RHEAD_CHEK_FROOSH2 INNER JOIN
                      dbo.INVO_LST ON RHEAD_CHEK_FROOSH2.TAG = dbo.INVO_LST.TAG AND RHEAD_CHEK_FROOSH2.NUMBER = dbo.INVO_LST.NUMBER ON 
                      dbo.STUF_DEF.CODE = dbo.INVO_LST.CODE LEFT OUTER JOIN
                      dbo.CUST_HESAB ON RHEAD_CHEK_FROOSH2.CUST_NO = dbo.CUST_HESAB.hes
WHERE     (RHEAD_CHEK_FROOSH2.DATE_N BETWEEN @Forms___F_MENU_KHFR___DT1 AND @Forms___F_MENU_KHFR___DT2) AND 
                      (RHEAD_CHEK_FROOSH2.CUST_NO = @Forms___F_MENU_KHFR___HMOIN) )
