CREATE FUNCTION [dbo].[TARAZNAMAH]
 (@ns float)
 RETURNS TABLE
 AS
 RETURN ( SELECT     dbo.TOTA_HES.NUMBER, dbo.TOTA_HES.NAME AS NAM, dbo.TCOD_HESGROUP.CODE, dbo.TCOD_HESGROUP.NAMES, TARAZNAMAH_SUB.daraee, 
                       TARAZNAMAH_SUB.BEDEHE, dbo.UIIF(dbo.TCOD_HESGROUP.CODE, N'<', 20, 1, 2) AS GRP
 FROM         dbo.TOTA_HES INNER JOIN
                       dbo.TCOD_HESGROUP ON dbo.TOTA_HES.[GROUP] = dbo.TCOD_HESGROUP.CODE INNER JOIN
                       dbo.TARAZNAMAH_SUB(@ns) TARAZNAMAH_SUB ON dbo.TOTA_HES.NUMBER = TARAZNAMAH_SUB.NUMBER )
