CREATE FUNCTION [dbo].[TARAZNAMAH_SUB]
 (@ns float)
 RETURNS TABLE
 AS
 RETURN ( SELECT     dbo.TOTA_HES.NUMBER, SUM(dbo.DEED_DTL.BED - dbo.DEED_DTL.BES) AS daraee, 0 AS BEDEHE, dbo.TOTA_HES.[GROUP] AS grp
 FROM         dbo.TOTA_HES INNER JOIN
                       dbo.DEED_DTL ON dbo.TOTA_HES.NUMBER = dbo.DEED_DTL.HES_K INNER JOIN
                       dbo.TARAZHES ON dbo.TOTA_HES.NUMBER = dbo.TARAZHES.NUMBER
 WHERE     (dbo.DEED_DTL.N_S <= @ns) AND (dbo.TOTA_HES.[GROUP] < 20)
 GROUP BY dbo.TOTA_HES.NUMBER, dbo.TOTA_HES.[GROUP]
 UNION
 SELECT     dbo.TOTA_HES.NUMBER, 0 AS daraee, SUM(dbo.DEED_DTL.BES - dbo.DEED_DTL.BED) AS BEDEHE, dbo.TOTA_HES.[GROUP] AS grp
 FROM         dbo.TOTA_HES INNER JOIN
                       dbo.DEED_DTL ON dbo.TOTA_HES.NUMBER = dbo.DEED_DTL.HES_K INNER JOIN
                       dbo.TARAZHES ON dbo.TOTA_HES.NUMBER = dbo.TARAZHES.NUMBER
 WHERE     (dbo.TOTA_HES.[GROUP] > 20) AND (dbo.DEED_DTL.N_S <= @ns)
 GROUP BY dbo.TOTA_HES.NUMBER, dbo.TOTA_HES.[GROUP] )
