CREATE FUNCTION [dbo].[VISITOR_DTL_GRP]
 (@dt1 bigint,
 @dt2 bigint,
 @visitor nvarchar(40))
 RETURNS TABLE
 AS
 RETURN ( SELECT     TOP 100 PERCENT SUM(dbo.INVO_LST.MEGHk) AS MEGHk, SUM(dbo.INVO_LST.MABL_K) AS MABL_K, SUM(dbo.INVO_LST.IMBAA) AS IMBAA, 
                       SUM(dbo.INVO_LST.N_MOIN) AS N_MOIN, dbo.CUST_HESAB.NAME AS VISITOR, dbo.VISITOR_DTL.CUST_NO, SUM(dbo.INVO_LST.MEGH_MAR) 
                       AS MEGH_MAR, SUM(dbo.INVO_LST.MEGH_MAR * dbo.INVO_LST.MABL) AS MABMAR, 
                       SUM(dbo.INVO_LST.MABL_K - dbo.INVO_LST.MEGH_MAR * dbo.INVO_LST.MABL + dbo.INVO_LST.IMBAA - dbo.INVO_LST.N_MOIN) AS GHABEL, 
                       dbo.CUST_HESAB.ADDRESS, dbo.CUST_HESAB.TEL, dbo.CUST_HESAB.TOZIH, dbo.CUST_HESAB.MOBILE, dbo.STUF_DEF.RADAH
 FROM         dbo.HEAD_LST INNER JOIN
                       dbo.INVO_LST ON dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG INNER JOIN
                       dbo.VISITOR_DTL ON dbo.HEAD_LST.NUMBER = dbo.VISITOR_DTL.NUMBER AND dbo.HEAD_LST.TAG = dbo.VISITOR_DTL.TAG INNER JOIN
                       dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE INNER JOIN
                       dbo.CUST_HESAB ON dbo.VISITOR_DTL.CUST_NO = dbo.CUST_HESAB.hes
 WHERE     (dbo.HEAD_LST.DATE_N BETWEEN @dt1 AND @dt2) AND (dbo.HEAD_LST.TAG = 2)
 GROUP BY dbo.CUST_HESAB.NAME, dbo.VISITOR_DTL.CUST_NO, dbo.CUST_HESAB.ADDRESS, dbo.CUST_HESAB.TEL, dbo.CUST_HESAB.TOZIH, 
                       dbo.CUST_HESAB.MOBILE, dbo.STUF_DEF.RADAH
 HAVING      (dbo.VISITOR_DTL.CUST_NO LIKE @visitor)
 ORDER BY dbo.CUST_HESAB.NAME, SUM(dbo.INVO_LST.MABL_K) DESC )
