CREATE VIEW [dbo].[AMAR_FROOSH_DAYLY]
AS
SELECT     TOP 100 PERCENT SUM(dbo.INVO_LST.MEGHk) AS MEGHT, dbo.TCOD_STUFGROUP.NAMES, dbo.TCOD_VAHEDS.NAMES AS vahed, 
                      dbo.HEAD_LST.DATE_N, dbo.TCOD_STUFGROUP.CODE AS GRP, dbo.TCOD_VAHEDS.CODE AS VH, dbo.STUF_DEF.NAME, 
                      dbo.Uday(dbo.HEAD_LST.DATE_N) AS DAYY
FROM         dbo.HEAD_LST INNER JOIN
                      dbo.INVO_LST ON dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG INNER JOIN
                      dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE INNER JOIN
                      dbo.TCOD_STUFGROUP ON dbo.STUF_DEF.RADAH = dbo.TCOD_STUFGROUP.CODE INNER JOIN
                      dbo.TCOD_VAHEDS ON dbo.STUF_DEF.VAHED = dbo.TCOD_VAHEDS.CODE
WHERE     (dbo.HEAD_LST.TAG = 2)
GROUP BY dbo.TCOD_STUFGROUP.NAMES, dbo.TCOD_VAHEDS.NAMES, dbo.HEAD_LST.DATE_N, dbo.TCOD_STUFGROUP.CODE, dbo.TCOD_VAHEDS.CODE, 
                      dbo.STUF_DEF.NAME, dbo.Uday(dbo.HEAD_LST.DATE_N)
ORDER BY dbo.HEAD_LST.DATE_N
