CREATE VIEW [dbo].[APMOGO_AVL_KOL_SUB]
AS
SELECT     CODE, SUM(MOGODI_A) AS MEG, SUM(MABL_A) AS SumOfMABL_A, ANBAR, 0 AS AA
FROM         dbo.STUF_FSK
GROUP BY CODE, ANBAR
UNION
SELECT     dbo.INVO_LST.CODE, SUM(dbo.INVO_LST.MEGHk - dbo.INVO_LST.MEGH_MAR) AS MEG, SUM(dbo.INVO_LST.MABL_K) AS SumOfMABL_K, 
                      dbo.INVO_LST.ANBAR, 1 AS AA
FROM         dbo.HEAD_LST INNER JOIN
                      dbo.INVO_LST ON dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG AND dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER
WHERE     (dbo.INVO_LST.TAG = 1)
GROUP BY dbo.INVO_LST.CODE, dbo.INVO_LST.ANBAR
UNION
SELECT     dbo.INVO_LST.CODE, SUM(dbo.INVO_LST.MEGHk - dbo.INVO_LST.MEGH_MAR) AS MEG, SUM(dbo.INVO_LST.MABL_K) AS SumOfMABL_K, 
                      dbo.INVO_LST.ANBARF, 2 AS AA
FROM         dbo.HEAD_LST INNER JOIN
                      dbo.INVO_LST ON dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG AND dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER
WHERE     (dbo.INVO_LST.TAG = 5)
GROUP BY dbo.INVO_LST.CODE, dbo.INVO_LST.ANBARF
