CREATE VIEW [dbo].[B_MOG_KOL_SUB]
AS

SELECT     ANBAR, CODE, SUM(MEGHk - MEGH_MAR) AS MEG, 0 AS AA
FROM         dbo.INVO_LST
WHERE     (TAG = 1) OR
                      (TAG = 7) OR
                      (TAG = 9) OR
                      (TAG = 24)
GROUP BY ANBAR, CODE
UNION
SELECT     ANBAR, CODE, SUM(MOGODI_A) AS MEG, 1 AS AA
FROM         dbo.STUF_FSK
GROUP BY ANBAR, CODE
UNION
SELECT     ANBARF, CODE, SUM(MEGHk - MEGH_MAR) AS MEG, 2 AS AA
FROM         dbo.INVO_LST
WHERE     (TAG = 5)
GROUP BY ANBARF, CODE
UNION
SELECT     ANBAR, CODE, SUM(MEGH_MAR) AS MEG, 0 AS AA
FROM         dbo.INVO_LST
WHERE     (TAG = 22)
GROUP BY ANBAR, CODE
