CREATE VIEW [dbo].[B_MOG_AVL_KOL_sub]
AS

SELECT     CODE, SUM(MEG) AS SumOfMEG, ANBAR
FROM         dbo.B_MOG_KOL_SUB
GROUP BY ANBAR, CODE
UNION
SELECT     dbo.ANBGRD_LST.CODE, (dbo.ANBGRD_LST.MOG - dbo.ANBGRD_LST.NUM3) * - 1 AS MEG, dbo.ANBGRD_HEAD.GRD_ANBAR AS anbar
FROM         dbo.ANBGRD_LST INNER JOIN
                      dbo.ANBGRD_HEAD ON dbo.ANBGRD_LST.GRD_NUM = dbo.ANBGRD_HEAD.GRD_NUM
WHERE     ((dbo.ANBGRD_LST.MOG - dbo.ANBGRD_LST.NUM3) * - 1 > 0 AND (NOT (dbo.ANBGRD_HEAD.N_S IS NULL)))
