CREATE VIEW [dbo].[BED-BES]
AS
SELECT     HES_K, HES_M, HES_T, HES_T2, HES_T3, HES_T4, SUM(BED - BES) AS BEST, HES
FROM         dbo.DEED_DTL
GROUP BY HES_K, HES_M, HES_T, HES, HES_T2, HES_T3, HES_T4
HAVING      (SUM(BED - BES) <> 0)
