CREATE VIEW [dbo].[CHEKS_NOPASS_PERS_SUB]
 AS
 SELECT     SUM(dbo.PAY_GETD.MABL) AS kmab, dbo.PGET_LST.FHES
 FROM         dbo.PGET_LST INNER JOIN
                       dbo.PAY_GETD ON dbo.PGET_LST.N_SERI = dbo.PAY_GETD.N_SERI AND dbo.PGET_LST.BANK = dbo.PAY_GETD.BANK
 WHERE     (dbo.PAY_GETD.N_KOL3 IS NULL) AND (dbo.PGET_LST.NO_AM = 1) AND (dbo.PGET_LST.NAHVA = 2)
 GROUP BY dbo.PGET_LST.FHES
 UNION
 SELECT     SUM(dbo.PAY_GETD.MABL) AS kmab, dbo.HEAD_LST.CUST_NO
 FROM         dbo.HEAD_LST INNER JOIN
                       dbo.PAY_GETD ON dbo.HEAD_LST.NUMBER = dbo.PAY_GETD.NUMBER
 WHERE     (dbo.PAY_GETD.N_KOL3 IS NULL) AND (dbo.PAY_GETD.TAG = 2) AND (dbo.PAY_GETD.N_KOL2 IS NULL)
 GROUP BY dbo.HEAD_LST.CUST_NO
