CREATE VIEW [dbo].[CHK_SODUR]
AS
SELECT     N_SERI, BANK, DATE_S, DATE, SHOBEH, MABL, NAME_TAH, N_HESAB, N_S, N_KOL, N_MOIN, N_KOL2, N_MOIN2, 
                      N_KOL3, N_MOIN3, NUMBER, TAG, ANBAR, RADIF, CUST_NO, N_TAF, N_TAF2, N_TAF3
FROM         dbo.PAY_GETP
WHERE     (NOT (N_MOIN IS NULL))
