CREATE VIEW   [dbo].[CHREC_LSP_Q]
AS
SELECT     TOP 100 PERCENT dbo.CHRE_LSP.N_SERI, dbo.CHRE_LSP.BANK, dbo.CHRE_LSP.DATE_S, dbo.CHRE_LSP.DATE, dbo.CHRE_LSP.RADIF, 
                      dbo.PAY_GETP.SHOBEH, dbo.PAY_GETP.MABL, dbo.PAY_GETP.DATE_S AS PDTS, dbo.PAY_GETP.N_KOL3, dbo.PAY_GETP.N_MOIN3, 
                      dbo.PAY_GETP.N_MOIN, dbo.PAY_GETP.N_TAF, dbo.PAY_GETP.N_TAF3, dbo.PAY_GETP.HES1
FROM         dbo.PAY_GETP RIGHT OUTER JOIN
                      dbo.CHRE_LSP ON dbo.PAY_GETP.DATE_S = dbo.CHRE_LSP.DATE_S AND dbo.PAY_GETP.BANK = dbo.CHRE_LSP.BANK AND 
                      dbo.PAY_GETP.N_SERI = dbo.CHRE_LSP.N_SERI
ORDER BY dbo.PAY_GETP.N_TAF3, dbo.CHRE_LSP.BANK, dbo.CHRE_LSP.N_SERI
