CREATE VIEW [dbo].[DEAD_HEAD_PRINT]
AS
SELECT     dbo.DEAD_DTL_PRINT.DATE_S, dbo.DEAD_DTL_PRINT.SHARH_S, dbo.DEAD_DTL_PRINT.HES, dbo.DEAD_DTL_PRINT.TNUMBER, 
                      dbo.DEAD_DTL_PRINT.NUMBER, dbo.DEAD_DTL_PRINT.HNAME, dbo.DEAD_DTL_PRINT.TNAME, dbo.DEAD_DTL_PRINT.MNAME, 
                      dbo.DEAD_DTL_PRINT.KNAME, dbo.DEAD_DTL_PRINT.N_KOL, dbo.DEAD_DTL_PRINT.BED, dbo.DEAD_DTL_PRINT.BES, 
                      dbo.DEAD_DTL_PRINT.SHARH, dbo.DEAD_DTL_PRINT.kk, dbo.DEAD_DTL_PRINT.BASE, dbo.DEAD_DTL_PRINT.RADIF, dbo.DEAD_DTL_PRINT.GR, 
                      dbo.DEAD_DTL_PRINT.N_S, dbo.DEAD_WITHSUM.SUMOFBED, dbo.DEAD_WITHSUM.SumOfBES, 
                      dbo.DEAD_DTL_PRINT.BED + dbo.DEAD_DTL_PRINT.BES AS JOZ, dbo.UIIF(dbo.DEAD_WITHSUM.SUMOFBED, N'>', 0, 
                      dbo.DEAD_WITHSUM.SUMOFBED * 1000 + dbo.DEAD_DTL_PRINT.N_KOL, dbo.DEAD_WITHSUM.SumOfBES * - 1000 - dbo.DEAD_DTL_PRINT.N_KOL) 
                      AS GRPAS
FROM         dbo.DEAD_DTL_PRINT INNER JOIN
                      dbo.DEAD_WITHSUM ON dbo.DEAD_DTL_PRINT.GR = dbo.DEAD_WITHSUM.GR AND 
                      dbo.DEAD_DTL_PRINT.N_KOL = dbo.DEAD_WITHSUM.N_KOL AND dbo.DEAD_DTL_PRINT.N_S = dbo.DEAD_WITHSUM.N_S
