CREATE VIEW [dbo].[DEAD_WITHSUM]
AS
SELECT     DATE_S, N_S, N_KOL, BED AS SUMOFBED, SUM(BES) AS SumOfBES, GR
FROM         dbo.DEAD_DTL_PRINT
GROUP BY DATE_S, N_S, N_KOL, BED, GR
HAVING      (BED = 0)
UNION
SELECT     DATE_S, N_S, N_KOL, SUM(BED) AS SumOfBED, BES AS SUMOFBES, GR
FROM         dbo.DEAD_DTL_PRINT
GROUP BY DATE_S, N_S, N_KOL, BES, GR
HAVING      (BES = 0)
