create view  [dbo].[EVENTS_USER_DAYS]
 as
 SELECT     TOP 100 PERCENT STDATE, COUNT(USERNAME) AS CountOfUSERNAME, USERNAME
 FROM         dbo.EVENTS
 GROUP BY STDATE, USERNAME
 ORDER BY STDATE DESC
