CREATE VIEW [dbo].[FACTOREFROOSH]
 AS
 SELECT     TOP 100 PERCENT NUMBER, TAG, ANBAR, RADIF, CODE, MEGH, MEGHk, MEGH_MAR, MANDAH, MABL, MABL_K, FROM_A, N_RASID, MEGH_R, RADAH, SANAD_NO,
                        CUST_NO, ANBARF, VAHED_K, N_KOL, N_MOIN, N_TAF, AVRAGE, id, AVRAGE2, IMBAA, TOTALARZ, VISITOR, TKHN, JAY, JAYO
 FROM         dbo.INVO_LST
 ORDER BY id
