CREATE view [dbo].[GHAEYMAT_TAMAM_SUB]
as
SELECT     dbo.HEAD_MANF.CODE, SUM(dbo.DTL_MANF.MABLK) AS SumOfMABLK, dbo.HEAD_MANF.IMBIBE_MANF AS SumOfIMBIBE_MANF, 
                      dbo.HEAD_MANF.IMBIBE_SAR AS SumOfIMBIBE_SAR, dbo.DTL_MANF.FNUMB
FROM         dbo.HEAD_MANF INNER JOIN
                      dbo.DTL_MANF ON dbo.HEAD_MANF.FNUMB = dbo.DTL_MANF.FNUMB
GROUP BY dbo.HEAD_MANF.CODE, dbo.HEAD_MANF.IMBIBE_MANF, dbo.HEAD_MANF.IMBIBE_SAR, dbo.DTL_MANF.FNUMB
