CREATE VIEW [dbo].[GRADEFORMATVIEW]
 AS
 SELECT     dbo.GRADE_GRP_FT.GFGRPZARIB * dbo.GRADE_GRP_FT.GFGRPGRADE AS EMTZAR, 
                       dbo.GRADE_GRP_FT.GFGRPZARIB * dbo.GRADE_GRP_FT.GFGRPGRADE * dbo.GRADE_TAB_FT.GFGZARIB AS EMTZARTAB, dbo.GRADE_FORMAT.IDD, 
                       dbo.GRADE_FORMAT.GFNAME, dbo.GRADE_FORMAT.GFDATE, dbo.GRADE_FORMAT.TOZIH, dbo.GRADE_FORMAT.USERNAME, dbo.GRADE_FORMAT.JAMZARIB, 
                       dbo.GRADE_FORMAT.EMTIAZ, dbo.GRADE_TAB_FT.GFTID, dbo.GRADE_TAB_FT.GFNAMEFT, dbo.GRADE_TAB_FT.GFGZARIB, dbo.GRADE_GRP_FT.GFTGRPID, 
                       dbo.GRADE_GRP_FT.GFGRPNAMEFT, dbo.GRADE_GRP_FT.GFGRPZARIB, dbo.GRADE_GRP_FT.GFGRPGRADE
 FROM         dbo.GRADE_TAB_FT INNER JOIN
                       dbo.GRADE_FORMAT ON dbo.GRADE_TAB_FT.GFID = dbo.GRADE_FORMAT.IDD INNER JOIN
                       dbo.GRADE_GRP_FT ON dbo.GRADE_TAB_FT.GFTID = dbo.GRADE_GRP_FT.GFTID
