CREATE VIEW [dbo].[GRADEVIEW]
AS
SELECT     dbo.AZAE.HES, dbo.AZAE.TOPETEB, dbo.AZAE.TOPASN, dbo.AZAE.ENDIS, dbo.AZAE.TOPMEGH, dbo.CUST_HESAB.NAME, dbo.CUST_HESAB.ADDRESS, 
                      dbo.CUST_HESAB.TEL, dbo.CUST_HESAB.CODE_E, dbo.CUST_HESAB.ECODE, dbo.CUST_HESAB.PCODE, dbo.CUST_HESAB.IYALAT, dbo.CUST_HESAB.CITY, 
                      dbo.CUST_HESAB.MCODEM, dbo.CUST_HESAB.TOZIH, dbo.CUST_HESAB.CUST_COD, dbo.CUST_HESAB.MOBILE, dbo.CUST_HESAB.Longitude, 
                      dbo.CUST_HESAB.Latitude, dbo.CUST_HESAB.ROUTE_NAME, dbo.GRADE_CUST_TAB.GCTABID, dbo.GRADE_CUST_TAB.GCNAME, dbo.GRADE_CUST_TAB.GCZARIB, 
                      dbo.GRADE_CUST_TAB.GCCUST_HES, dbo.GRADE_CUST_TAB.GCDATE, dbo.GRADE_CUST_TAB.USERNAME, dbo.GRADE_CUST_GRP.GCGRPID, 
                      dbo.GRADE_CUST_GRP.GCGRPNAME, dbo.GRADE_CUST_GRP.GCGRPZARIB, dbo.GRADE_CUST_GRP.GCGRPGRADE, 
                      dbo.GRADE_CUST_GRP.GCGRPZARIB * dbo.GRADE_CUST_GRP.GCGRPGRADE AS EMTZAR, 
                      dbo.GRADE_CUST_GRP.GCGRPZARIB * dbo.GRADE_CUST_GRP.GCGRPGRADE * dbo.GRADE_CUST_TAB.GCZARIB AS EMTZARTAB, dbo.AZAE.JAMZARIB, 
                      dbo.AZAE.EMTIAZ
FROM         dbo.GRADE_CUST_GRP INNER JOIN
                      dbo.GRADE_CUST_TAB ON dbo.GRADE_CUST_GRP.GCTABID = dbo.GRADE_CUST_TAB.GCTABID INNER JOIN
                      dbo.AZAE ON dbo.GRADE_CUST_TAB.GCCUST_HES = dbo.AZAE.HES INNER JOIN
                      dbo.CUST_HESAB ON dbo.AZAE.HES = dbo.CUST_HESAB.hes
