CREATE VIEW [dbo].[hamrah]
AS
SELECT MEHMAN.ROOMN, MEHMAN.IDH, MEHMAN.SAZMANM
FROM MEHMAN
GROUP BY MEHMAN.KDATE, MEHMAN.ROOMN, MEHMAN.IDH, MEHMAN.SAZMANM
HAVING (((MEHMAN.KDATE) Is Null) AND (Not (MEHMAN.IDH) Is Null))
