CREATE VIEW [dbo].[HEAD_LAST_RASID12]
AS
SELECT     TOP 100 PERCENT NUMBER, TAG AS htag, TAG - 11 AS Dtag, ANBAR, NUMBER1, DATE_N, TAH, MAS, VAS, N_S, CUST_NO, MOLAH, M_NAGHD, 
                      MABL_VAR, MOIN_VAR, MABL_HAV, MOIN_HAV, MABL_HAZ, MOIN_HAZ, TAKHFIF, MOIN_KHF, ANBARF, FNUMCO, USER_NAME
FROM         dbo.HEAD_LST
WHERE     (TAG = 12)
ORDER BY NUMBER
