CREATE VIEW  [dbo].[JAMFACTPRS]
 AS
 SELECT     TOP 100 PERCENT dbo.HEAD_LST.NUMBER, dbo.HEAD_LST.TAG, dbo.HEAD_LST.CUST_NO, dbo.HEAD_LST.DATE_N, 
                       SUM(dbo.INVO_LST.MABL_K - dbo.INVO_LST.N_MOIN + dbo.INVO_LST.IMBAA) AS mab
 FROM         dbo.HEAD_LST INNER JOIN
                       dbo.INVO_LST ON dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG
 GROUP BY dbo.HEAD_LST.NUMBER, dbo.HEAD_LST.TAG, dbo.HEAD_LST.CUST_NO, dbo.HEAD_LST.DATE_N
 HAVING      (dbo.HEAD_LST.TAG = 2)
 ORDER BY dbo.HEAD_LST.DATE_N DESC
