CREATE VIEW [dbo].[KA_EN]
AS
SELECT INVO_LST.ANBARF, INVO_LST.CODE, INVO_LST.MEGHk AS MEG, INVO_LST.MABL, INVO_LST.MABL_K, 6 AS TA, INVO_LST.MEGHk, HEAD_LST.DATE_N
FROM HEAD_LST INNER JOIN INVO_LST ON (HEAD_LST.NUMBER = INVO_LST.NUMBER)
WHERE (((HEAD_LST.TAG)=5))
