CREATE VIEW [dbo].[KA_FSK]
AS
SELECT INVO_LST.ANBAR, INVO_LST.CODE, INVO_LST.MEGHk AS MEG, INVO_LST.MABL, INVO_LST.MABL_K, HEAD_LST.TAG, INVO_LST.MEGHk, HEAD_LST.DATE_N
FROM HEAD_LST INNER JOIN INVO_LST ON (HEAD_LST.TAG = INVO_LST.TAG)
WHERE (((HEAD_LST.TAG)=1 Or (HEAD_LST.TAG)=4))
