CREATE VIEW [dbo].[KH_FR]
AS
SELECT INVO_LST.ANBAR, INVO_LST.CODE, MEGHk*-1 AS MEG, INVO_LST.MABL, INVO_LST.MABL_K, HEAD_LST.TAG, INVO_LST.MEGHk, HEAD_LST.DATE_N
FROM HEAD_LST INNER JOIN INVO_LST ON (HEAD_LST.TAG = INVO_LST.TAG)
WHERE (((HEAD_LST.TAG)=2 Or (HEAD_LST.TAG)=3 Or (HEAD_LST.TAG)=5))
