CREATE VIEW [dbo].[MANF_JAMK]
AS
SELECT HEAD_MANF.CODE, sum(DTL_MANF.MABLK) AS SumOfMABLK, HEAD_MANF.IMBIBE_MANF, HEAD_MANF.IMBIBE_SAR
FROM HEAD_MANF INNER JOIN DTL_MANF ON (HEAD_MANF.FNUMB = DTL_MANF.FNUMB)
GROUP BY HEAD_MANF.CODE, HEAD_MANF.IMBIBE_MANF, HEAD_MANF.IMBIBE_SAR
