CREATE VIEW  [dbo].[MEGH_RAIS]
 AS
 SELECT     dbo.HEAD_LST.TAG, dbo.HEAD_LST.NUMBER1, dbo.INVO_LST.ANBAR, dbo.INVO_LST.CODE, SUM(dbo.INVO_LST.MEGHk) AS MEGHkS, dbo.INVO_LST.RADAH
 FROM         dbo.HEAD_LST INNER JOIN
                       dbo.INVO_LST ON dbo.HEAD_LST.NUMBER = dbo.INVO_LST.NUMBER AND dbo.HEAD_LST.TAG = dbo.INVO_LST.TAG
 GROUP BY dbo.HEAD_LST.TAG, dbo.HEAD_LST.NUMBER1, dbo.INVO_LST.ANBAR, dbo.INVO_LST.CODE, dbo.INVO_LST.RADAH
 HAVING      (dbo.HEAD_LST.TAG = 1) AND (NOT (dbo.INVO_LST.RADAH IS NULL))
