CREATE VIEW [dbo].[MODIRIYAT]
AS
SELECT     dbo.MEHMAN.*, dbo.HEAD_LST.CUST_NO, dbo.INVO_LST.MEGHk, dbo.INVO_LST.MABL, dbo.INVO_LST.MABL_K, dbo.STUF_DEF.NAME, 
                      dbo.HEAD_LST.NUMBER, dbo.HEAD_LST.USER_NAME AS USF
FROM         dbo.INVO_LST INNER JOIN
                      dbo.HEAD_LST ON dbo.INVO_LST.NUMBER = dbo.HEAD_LST.NUMBER AND dbo.INVO_LST.TAG = dbo.HEAD_LST.TAG INNER JOIN
                      dbo.MEHMAN ON dbo.HEAD_LST.CUST_NO = '124-1-' + CAST(dbo.MEHMAN.TAFZ AS NVARCHAR) INNER JOIN
                      dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE
WHERE     (NOT (dbo.MEHMAN.VDATE IS NULL)) AND (NOT (dbo.MEHMAN.KDATE IS NULL)) AND (NOT (dbo.MEHMAN.VTIME IS NULL)) AND 
                      (NOT (dbo.MEHMAN.KTIME IS NULL)) AND (dbo.HEAD_LST.TAG = 14) AND (dbo.MEHMAN.IDH IS NULL)
