CREATE VIEW [dbo].[PERSON]
AS
SELECT     RTRIM(CAST(N_KOL AS NVARCHAR)) + '-' + RTRIM(CAST(NUMBER AS NVARCHAR)) + '-' + RTRIM(CAST(TNUMBER AS NVARCHAR)) AS hes, N_KOL, 
                      NUMBER, TNUMBER, NAME, TOZIH, BED_BES, ADDRESS, TEL, CODE_E, ECODE, PCODE, IYALAT, CITY, MCODEM
FROM         dbo.TDETA_HES
