CREATE VIEW [dbo].[Q_HEAD_MANF]
AS
SELECT     FNUMB, CODE, DATE_ACTIV, IMBIBE_MANF, IMBIBE_SAR, GHEYMAT, NAMES, N_KOL, NUMBER, TNUMBER, SA_HOUR, SA_NHOU
FROM         dbo.HEAD_MANF
WHERE     (NAMES IS NULL)
