CREATE VIEW [dbo].[QPASED3]
AS
SELECT     dbo.PROGPAS1.PRGID, dbo.PROGPAS1.CODB, COUNT(dbo.PROGPAS1.CODB) AS CountOfCODB, dbo.PROGPAS1.PASED, dbo.PROGPAS1.RADAH, 
                      SUM(dbo.HEAD_MANF.IMBIBE_MANF) AS MANF, SUM(dbo.HEAD_MANF.IMBIBE_SAR) AS SAR
FROM         dbo.PROGPAS1 INNER JOIN
                      dbo.HEAD_MANF ON dbo.PROGPAS1.CODB = dbo.HEAD_MANF.CODE
GROUP BY dbo.PROGPAS1.PRGID, dbo.PROGPAS1.CODB, dbo.PROGPAS1.PASED, dbo.PROGPAS1.RADAH
HAVING      (dbo.PROGPAS1.RADAH <> 1)
