CREATE VIEW [dbo].[QPROGPASS2]
AS
SELECT     dbo.PROGPAS1.CODB, dbo.PROGPAS1.VAHED, SUM(dbo.PROGPAS1.MEGH * dbo.PRGHEAD.NUM) AS SumOfMEGH, 
                      SUM(dbo.PROGPAS1.MEGHK * dbo.PRGHEAD.NUM) AS SumOfMEGHK, SUM(dbo.PROGPAS1.PERT * dbo.PRGHEAD.NUM) AS SumOfPERT, 
                      SUM(dbo.PROGPAS1.KOLMAV * dbo.PRGHEAD.NUM) AS SumOfKOLMAV, SUM(dbo.PROGPAS1.MABL) AS SumOfMABL, 
                      SUM(dbo.PROGPAS1.MABLK * dbo.PRGHEAD.NUM) AS SumOfMABLK, dbo.PROGPAS1.PASED, dbo.PROGPAS1.RADAH, dbo.PRGHEAD.GRP
FROM         dbo.PROGPAS1 INNER JOIN
                      dbo.PRGHEAD ON dbo.PROGPAS1.PRGID = dbo.PRGHEAD.PRGID
GROUP BY dbo.PROGPAS1.CODB, dbo.PROGPAS1.VAHED, dbo.PROGPAS1.PASED, dbo.PROGPAS1.RADAH, dbo.PRGHEAD.GRP
HAVING      (dbo.PROGPAS1.RADAH = 1)
