CREATE  VIEW  [dbo].[QSL_INVOICE_KH_BACK]
as
SELECT     dbo.HEAD_BACK.NUMBER, dbo.HEAD_BACK.HTAG, dbo.HEAD_BACK.DATE_N, dbo.HEAD_BACK.CUST_NO, dbo.HEAD_BACK.ANBAR, 
                      dbo.HEAD_BACK.NUMBER1, dbo.HEAD_BACK.TAH, dbo.HEAD_BACK.MAS, dbo.HEAD_BACK.VAS, dbo.HEAD_BACK.N_S, dbo.HEAD_BACK.MOLAH, 
                      dbo.HEAD_BACK.M_NAGHD, dbo.HEAD_BACK.MABL_VAR, dbo.HEAD_BACK.MOIN_VAR, dbo.HEAD_BACK.MABL_HAV, dbo.HEAD_BACK.MOIN_HAV, 
                      dbo.HEAD_BACK.MABL_HAZ, dbo.HEAD_BACK.MOIN_HAZ, dbo.HEAD_BACK.TAKHFIF, dbo.HEAD_BACK.MOIN_KHF, dbo.HEAD_BACK.ANBARF, 
                      dbo.HEAD_BACK.FNUMCO, dbo.INVO_LST.NUMBER AS INUMBER, dbo.INVO_LST.TAG AS ITAG, dbo.INVO_LST.ANBAR AS IANBAR, 
                      dbo.INVO_LST.RADIF, dbo.INVO_LST.CODE, dbo.INVO_LST.MEGH, dbo.INVO_LST.MEGHk, dbo.INVO_LST.MEGH_MAR, dbo.INVO_LST.MANDAH, 
                      dbo.INVO_LST.MABL, dbo.INVO_LST.MABL_K, dbo.INVO_LST.FROM_A, dbo.INVO_LST.N_RASID, dbo.INVO_LST.MEGH_R, dbo.INVO_LST.RADAH, 
                      dbo.INVO_LST.SANAD_NO, dbo.INVO_LST.CUST_NO AS ICUST_NO, dbo.INVO_LST.ANBARF AS IANBARF, dbo.INVO_LST.VAHED_K, 
                      dbo.CUST_HESAB.NAME, dbo.CUST_HESAB.ADDRESS, dbo.CUST_HESAB.TEL, dbo.TCOD_ANBAR.NAMES, dbo.STUF_DEF.NAME AS SNAME, 
                      dbo.TCOD_VAHEDS.NAMES AS VNAMES, dbo.CUST_HESAB.hes, dbo.INVO_LST.MEGH_MAR * dbo.INVO_LST.MABL AS MABMAR, 
                      dbo.STUF_DEF.N_FANI, ISNULL(dbo.STUF_DEF.NAME, N' ') + N' ' + ISNULL(dbo.INVO_LST.MANDAH, N' ') AS KALA
FROM         dbo.INVO_LST INNER JOIN
                      dbo.TCOD_VAHEDS ON dbo.INVO_LST.VAHED_K = dbo.TCOD_VAHEDS.CODE INNER JOIN
                      dbo.TCOD_ANBAR ON dbo.INVO_LST.ANBAR = dbo.TCOD_ANBAR.CODE INNER JOIN
                      dbo.HEAD_BACK ON dbo.INVO_LST.NUMBER = dbo.HEAD_BACK.NUMBER1 AND dbo.INVO_LST.TAG = dbo.HEAD_BACK.HTAG INNER JOIN
                      dbo.CUST_HESAB ON dbo.HEAD_BACK.CUST_NO = dbo.CUST_HESAB.hes INNER JOIN
                      dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE
WHERE     (dbo.INVO_LST.MEGH_MAR <> 0)
