CREATE VIEW [dbo].[QSL_HAVALAH_ANBAR_VROUD]
AS
SELECT     dbo.HEAD_BACK_ANBAR.NUMBER1, dbo.HEAD_BACK_ANBAR.NUMBER, dbo.HEAD_BACK_ANBAR.DATE_N, dbo.HEAD_BACK_ANBAR.HTAG, 
                      dbo.INVO_LST.ANBAR, dbo.INVO_LST.RADIF, dbo.INVO_LST.CODE, dbo.INVO_LST.MEGH, dbo.INVO_LST.MEGHk, dbo.INVO_LST.MEGH_MAR, 
                      dbo.INVO_LST.MANDAH, dbo.INVO_LST.MABL, dbo.INVO_LST.MABL_K, dbo.INVO_LST.FROM_A, dbo.INVO_LST.N_RASID, dbo.INVO_LST.MEGH_R, 
                      dbo.INVO_LST.RADAH, dbo.INVO_LST.SANAD_NO, dbo.INVO_LST.CUST_NO, dbo.INVO_LST.ANBARF, dbo.INVO_LST.VAHED_K, 
                      dbo.TCOD_ANBAR.NAMES, dbo.STUF_DEF.NAME, dbo.TCOD_VAHEDS.NAMES AS VNAMES, dbo.HEAD_BACK_ANBAR.TAH, 
                      dbo.HEAD_BACK_ANBAR.MOLAH
FROM         dbo.INVO_LST INNER JOIN
                      dbo.TCOD_VAHEDS ON dbo.INVO_LST.VAHED_K = dbo.TCOD_VAHEDS.CODE INNER JOIN
                      dbo.TCOD_ANBAR ON dbo.INVO_LST.ANBAR = dbo.TCOD_ANBAR.CODE INNER JOIN
                      dbo.HEAD_BACK_ANBAR ON dbo.INVO_LST.NUMBER = dbo.HEAD_BACK_ANBAR.NUMBER AND 
                      dbo.INVO_LST.TAG = dbo.HEAD_BACK_ANBAR.HTAG INNER JOIN
                      dbo.STUF_DEF ON dbo.INVO_LST.CODE = dbo.STUF_DEF.CODE
