CREATE VIEW [dbo].[QSL_F_HEAD_LST]
AS
SELECT     TOP 100 PERCENT NUMBER, TAG AS htag, ANBAR, NUMBER1, DATE_N, TAH, MAS, VAS, N_S, CUST_NO, MOLAH, M_NAGHD, MABL_VAR, MOIN_VAR, 
                      MABL_HAV, MOIN_HAV, MABL_HAZ, MOIN_HAZ, TAKHFIF, MOIN_KHF, ANBARF, FNUMCO, USER_NAME, CUST_KIND, SHIFT, DEPATMAN
FROM         dbo.HEAD_LST
WHERE     (TAG = 2)
ORDER BY NUMBER
