CREATE VIEW [dbo].[QSL_INVOICE_FROOSH_G]
AS
SELECT     dbo.HEAD_CHEK_FROOSHG.TAG, dbo.HEAD_CHEK_FROOSHG.DATE_N, dbo.HEAD_CHEK_FROOSHG.CUST_NO, dbo.HEAD_CHEK_FROOSHG.ANBAR, 
                      dbo.HEAD_CHEK_FROOSHG.NUMBER1, dbo.HEAD_CHEK_FROOSHG.TAH, dbo.HEAD_CHEK_FROOSHG.MAS, dbo.HEAD_CHEK_FROOSHG.VAS, 
                      dbo.HEAD_CHEK_FROOSHG.N_S, dbo.HEAD_CHEK_FROOSHG.MOLAH, dbo.HEAD_CHEK_FROOSHG.M_NAGHD, 
                      dbo.HEAD_CHEK_FROOSHG.MABL_VAR, dbo.HEAD_CHEK_FROOSHG.MOIN_VAR, dbo.HEAD_CHEK_FROOSHG.MABL_HAV, 
                      dbo.HEAD_CHEK_FROOSHG.MOIN_HAV, dbo.HEAD_CHEK_FROOSHG.MABL_HAZ, dbo.HEAD_CHEK_FROOSHG.MOIN_HAZ, 
                      dbo.HEAD_CHEK_FROOSHG.TAKHFIF, dbo.HEAD_CHEK_FROOSHG.MOIN_KHF, dbo.HEAD_CHEK_FROOSHG.ANBARF, 
                      dbo.HEAD_CHEK_FROOSHG.FNUMCO, dbo.INVO_LST.NUMBER, dbo.INVO_LST.ANBAR AS IANBAR, dbo.INVO_LST.RADIF, dbo.INVO_LST.CODE, 
                      dbo.INVO_LST.MEGH, dbo.INVO_LST.MEGHk, dbo.INVO_LST.MEGH_MAR, dbo.INVO_LST.MANDAH, dbo.INVO_LST.MABL, dbo.INVO_LST.MABL_K, 
                      dbo.INVO_LST.FROM_A, dbo.INVO_LST.N_RASID, dbo.INVO_LST.MEGH_R, dbo.INVO_LST.RADAH, dbo.INVO_LST.SANAD_NO, 
                      dbo.INVO_LST.CUST_NO AS ICUST_NO, dbo.INVO_LST.ANBARF AS IANBARF, dbo.INVO_LST.VAHED_K, dbo.CUST_HESAB.hes AS BEDN, 
                      dbo.CUST_HESAB.NAME, dbo.CUST_HESAB.ADDRESS, dbo.CUST_HESAB.TEL, dbo.TCOD_ANBAR.NAMES, dbo.STUF_DEF.NAME AS SNAME, 
                      dbo.TCOD_VAHEDS.NAMES AS TNAMES, dbo.HEAD_CHEK_FROOSHG.mab, dbo.HEAD_CHEK_FROOSHG.CountOfMABL, 
                      dbo.INVO_LST.MEGH_MAR * dbo.INVO_LST.MABL AS MABL_MAR, ISNULL(dbo.STUF_DEF.NAME, N'') + N'-' + ISNULL(dbo.INVO_LST.MANDAH, N'') 
                      AS KALA, dbo.HEAD_CHEK_FROOSHG.DEPNAME, dbo.HEAD_CHEK_FROOSHG.SHNAME, dbo.HEAD_CHEK_FROOSHG.USER_NAME, 
                      dbo.HEAD_CHEK_FROOSHG.MBAA
FROM         dbo.CUST_HESAB INNER JOIN
                      dbo.STUF_DEF INNER JOIN
                      dbo.TCOD_ANBAR INNER JOIN
                      dbo.INVO_LST INNER JOIN
                      dbo.TCOD_VAHEDS ON dbo.INVO_LST.VAHED_K = dbo.TCOD_VAHEDS.CODE ON dbo.TCOD_ANBAR.CODE = dbo.INVO_LST.ANBAR ON 
                      dbo.STUF_DEF.CODE = dbo.INVO_LST.CODE INNER JOIN
                      dbo.HEAD_CHEK_FROOSHG ON dbo.INVO_LST.NUMBER = dbo.HEAD_CHEK_FROOSHG.NUMBER AND 
                      dbo.INVO_LST.TAG = dbo.HEAD_CHEK_FROOSHG.TAG - 11 ON dbo.CUST_HESAB.hes = dbo.HEAD_CHEK_FROOSHG.CUST_NO
