CREATE VIEW [dbo].[QSL_KH_INVO_LST]
AS
SELECT     NUMBER, TAG, ANBAR, RADIF, CODE, MEGH, MEGHk, MEGH_MAR, MANDAH, MABL, MABL_K, FROM_A, N_RASID, MEGH_R, RADAH, SANAD_NO, 
                      CUST_NO, ANBARF, VAHED_K
FROM         dbo.INVO_LST
