CREATE  VIEW [dbo].[qsl_invoice_froosh_y]
AS
SELECT     NUMBER, TAG, DATE_N, CUST_NO, ANBAR, NUMBER1, TAH, MAS, VAS, N_S, M_NAGHD, MABL_VAR, MOIN_VAR, MABL_HAV, MOIN_HAV, MABL_HAZ, 
                      MOIN_HAZ, TAKHFIF, MOIN_KHF, ANBARF, FNUMCO, INUMBER, ITAG, IANBAR, CODE, SUM(MEGH) AS MEGH, SUM(MEGHk) AS MEGHk, MANDAH, 
                      MABL, SUM(MABL_K) AS MABL_K, NAME, ADDRESS, TEL, NAMES, KALA, VNAMES, MOLAH, hes, DEPNAME, USER_NAME, SHNAME, kala2, RADAH, 
                      HMBAA, MBAA, IMBAA, CODEn, SANAD_NO, ROUND(N_KOL * MABL / 100, 0) AS fikh
FROM         dbo.QSL_INVOICE_FROOSH
GROUP BY NUMBER, TAG, DATE_N, CUST_NO, ANBAR, NUMBER1, TAH, MAS, VAS, N_S, M_NAGHD, MABL_VAR, MOIN_VAR, MABL_HAV, MOIN_HAV, 
                      MABL_HAZ, MOIN_HAZ, TAKHFIF, MOIN_KHF, ANBARF, FNUMCO, INUMBER, ITAG, IANBAR, CODE, MANDAH, NAME, ADDRESS, TEL, NAMES, KALA, 
                      VNAMES, MOLAH, hes, DEPNAME, USER_NAME, SHNAME, kala2, RADAH, HMBAA, MBAA, IMBAA, CODEn, MABL, SANAD_NO,ROUND(N_KOL * MABL / 100, 0)
HAVING      (TAG = 2)
