CREATE VIEW [dbo].[ROOM SUB]
AS

SELECT     ID, MNAME, MFAMILY, FATHER, KNOW, MSODUR, BDATE, TAHSIL, JOB, GHASD, SCITY, DCITY, ENGIN, ADDRESS, VDATE, KDATE, HAMRAH, ROOMN, 
                      EZAFAH, MABLPISH, MOLAH, NAHVAH, SEX, TAFZ, IDH, SAZMANM, TABEI, ENDEGH
FROM         dbo.MEHMAN
WHERE     (KDATE IS NULL) AND (IDH IS NULL)
