CREATE VIEW [dbo].[ROOM_AMAR_SUB]
 AS
 SELECT     TOP 100 PERCENT dbo.ROOM.RFLAG, dbo.ROOM.TAKHT, COUNT(dbo.ROOM.ROOM_NUM) AS RCON
 FROM         dbo.ROOM LEFT OUTER JOIN
                       dbo.[ROOM SUB] ON dbo.ROOM.ROOM_NUM = dbo.[ROOM SUB].ROOMN
 GROUP BY dbo.ROOM.RFLAG, dbo.ROOM.TAKHT
