CREATE VIEW [dbo].[sum_sub2]
AS
SELECT MEHMAN.BDATE, MEHMAN.TAHSIL, MEHMAN.JOB, MEHMAN.GHASD, MEHMAN.SCITY, MEHMAN.DCITY, MEHMAN.ENGIN, MEHMAN.ADDRESS, MEHMAN.VDATE, MEHMAN.KDATE, MEHMAN.HAMRAH, MEHMAN.ROOMN, MEHMAN.EZAFAH, MEHMAN.MABLPISH, MEHMAN.MOLAH, MEHMAN.NAHVAH, MEHMAN.SEX, MEHMAN.TAFZ, MEHMAN.IDH, MEHMAN.SAZMANM, MEHMAN.TABEI, MEHMAN.ID, MEHMAN.MNAME, MEHMAN.MFAMILY, MEHMAN.FATHER, MEHMAN.KNOW, MEHMAN.MSODUR
FROM MEHMAN
WHERE (((MEHMAN.KDATE) Is Null) AND (Not (MEHMAN.IDH) Is Null))
