CREATE VIEW [dbo].[View_1]
AS
SELECT     TOP (100) PERCENT dbo.INVO_LST.NUMBER, dbo.INVO_LST.TAG, dbo.INVO_LST.N_KOL, dbo.HEAD_MANF.FNUMB
FROM         dbo.HEAD_MANF INNER JOIN
                      dbo.INVO_LST ON dbo.HEAD_MANF.FNUMB = dbo.INVO_LST.N_KOL
WHERE     (dbo.INVO_LST.TAG = 9)
ORDER BY dbo.INVO_LST.N_KOL
