CREATE VIEW [dbo].[View_4]
AS
SELECT     TOP (100) PERCENT dbo.HEAD_MANF.GHEYMAT, HEAD_MANF_1.GHEYMAT AS Expr1, dbo.HEAD_MANF.IMBIBE_MANF, dbo.HEAD_MANF.IMBIBE_SAR, 
                      HEAD_MANF_1.IMBIBE_MANF AS Expr2, HEAD_MANF_1.IMBIBE_SAR AS Expr3, dbo.HEAD_MANF.CODE, dbo.HEAD_MANF.FNUMB
FROM         dbo.HEAD_MANF INNER JOIN
                      dbo.HEAD_MANF AS HEAD_MANF_1 ON dbo.HEAD_MANF.CODE = HEAD_MANF_1.CODE
WHERE     (dbo.HEAD_MANF.GHEYMAT = 3) AND (HEAD_MANF_1.GHEYMAT = 2)
ORDER BY dbo.HEAD_MANF.IMBIBE_MANF DESC
