CREATE VIEW [dbo].[VISITOR_DTLO]
AS
SELECT
    VD.NUMBER,
    VD.TAG,
    VD.CUST_NO,
    VD.PURSANT - ISNULL(VDR.PURSANT, 0) AS mabpur,
    VD.PURSANT,
    VD.TOZIH,
    VD.STAT
FROM dbo.VISITOR_DTL AS VD
LEFT OUTER JOIN dbo.VISITOR_DTLR AS VDR
    ON VD.NUMBER = VDR.NUMBER
   AND VD.TAG = VDR.tag
   AND VD.CUST_NO = VDR.CUST_NO
WHERE VD.TAG = 2
