CREATE  VIEW [dbo].[VISITOR_DTLR]
AS
SELECT     dbo.HEAD_LST.NUMBER1 AS NUMBER, 2 AS tag, dbo.VISITOR_DTL.CUST_NO, dbo.VISITOR_DTL.DARSAD, dbo.VISITOR_DTL.PURSANT, dbo.VISITOR_DTL.TOZIH, 
                      dbo.VISITOR_DTL.STAT
FROM         dbo.HEAD_LST INNER JOIN
                      dbo.VISITOR_DTL ON dbo.HEAD_LST.NUMBER = dbo.VISITOR_DTL.NUMBER AND dbo.HEAD_LST.TAG = dbo.VISITOR_DTL.TAG
WHERE     (dbo.VISITOR_DTL.TAG = 4)
