CREATE VIEW [dbo].[VISITOR_DTLO]
AS
SELECT     dbo.VISITOR_DTL.NUMBER, dbo.VISITOR_DTL.TAG, dbo.VISITOR_DTL.CUST_NO, dbo.VISITOR_DTL.PURSANT - ISNULL(dbo.VISITOR_DTLR.PURSANT, 0) AS mabpur, 
                      dbo.VISITOR_DTL.PURSANT, dbo.VISITOR_DTL.TOZIH, dbo.VISITOR_DTL.STAT
FROM         dbo.VISITOR_DTL LEFT OUTER JOIN
                      dbo.VISITOR_DTLR  ON dbo.VISITOR_DTL.NUMBER = dbo.VISITOR_DTLR.NUMBER AND dbo.VISITOR_DTL.TAG = dbo.VISITOR_DTLR.tag
WHERE     (dbo.VISITOR_DTL.TAG = 2)
