CREATE VIEW [dbo].[zanbekht]
AS
SELECT     TOP (100) PERCENT SUM(dbo.ANBGRD_LST.MOG - dbo.ANBGRD_LST.NUM3) AS ekh, dbo.ANBGRD_LST.CODE
FROM         dbo.ANBGRD_HEAD INNER JOIN
                      dbo.ANBGRD_LST ON dbo.ANBGRD_HEAD.GRD_NUM = dbo.ANBGRD_LST.GRD_NUM
WHERE     (dbo.ANBGRD_HEAD.GRD_DATE BETWEEN 14040800 AND 14040831) AND (dbo.ANBGRD_HEAD.GRD_ANBAR = 7)
GROUP BY dbo.ANBGRD_LST.CODE
HAVING      (SUM(dbo.ANBGRD_LST.MOG - dbo.ANBGRD_LST.NUM3) <> 0)
ORDER BY ekh
