CREATE VIEW [dbo].[zdastmozd]
AS
SELECT     dbo.HEAD_MANF.GHEYMAT, dbo.HEAD_MANF.FNUMB, dbo.HEAD_MANF.CODE, dbo.HEAD_MANF.IMBIBE_MANF, dbo.HEAD_MANF.IMBIBE_SAR, 
                      HEAD_MANF_1.GHEYMAT AS Expr1, HEAD_MANF_1.IMBIBE_MANF AS dast8, HEAD_MANF_1.IMBIBE_SAR AS sar8, HEAD_MANF_1.FNUMB AS Expr4, 
                      HEAD_MANF_1.CODE AS Expr5
FROM         dbo.HEAD_MANF INNER JOIN
                      dbo.HEAD_MANF AS HEAD_MANF_1 ON dbo.HEAD_MANF.CODE = HEAD_MANF_1.CODE
WHERE     (dbo.HEAD_MANF.GHEYMAT = 7) AND (HEAD_MANF_1.GHEYMAT = 8)
