CREATE VIEW [dbo].[ztolidformol]
AS
SELECT     TOP (100) PERCENT dbo.HEAD_LST.NUMBER, dbo.HEAD_LST.TAG, dbo.HEAD_LST.DATE_N, dbo.INVO_LST.N_KOL, dbo.HEAD_MANF.GHEYMAT
FROM         dbo.INVO_LST INNER JOIN
                      dbo.HEAD_LST ON dbo.INVO_LST.NUMBER = dbo.HEAD_LST.NUMBER AND dbo.INVO_LST.TAG = dbo.HEAD_LST.TAG INNER JOIN
                      dbo.HEAD_MANF ON dbo.INVO_LST.N_KOL = dbo.HEAD_MANF.FNUMB
WHERE     (dbo.HEAD_LST.TAG = 9)
ORDER BY dbo.HEAD_LST.DATE_N DESC, dbo.INVO_LST.N_KOL DESC
