CREATE PROCEDURE [dbo].[DEED_DTL_P1]
AS INSERT INTO dbo.DEAD_DTL_PRINT
                      (DATE_S, SHARH_S, N_S, HES, TNUMBER, NUMBER, HNAME, N_KOL, BED, BES, SHARH, kk, BASE, RADIF, GR, TNAME, MNAME, KNAME)
SELECT     DATE_S, SHARH_S, N_S, HES, TNUMBER, NUMBER, HNAME, N_KOL, BED, BES, SHARH, kk, BASE, RADIF, GR, TNAME, MNAME, KNAME
FROM         dbo.DEAD_WITH_GRP1
WHERE     (N_S BETWEEN 1 AND 2)
