CREATE PROCEDURE [dbo].[GENERAT_ANBARGARDANY]
(@Forms___F_MENU_ANBAR___DT2 BIGINT,
@Forms___F_MENU_ANBAR___MANBAR nvarchar(10),
@GRD_NUM INT)
AS INSERT INTO dbo.ANBGRD_LST
                      (CODE, MOG, GRD_NUM)
SELECT     CODE, MAND, @GRD_NUM AS GN
FROM         dbo.AKMOGUDI_KOL_ANBAR(@Forms___F_MENU_ANBAR___DT2, @Forms___F_MENU_ANBAR___MANBAR) AKMOGUDI_KOL_ANBAR
