
-- ================================================================
-- ۴. SP_PAY2_GEN_DEED_SETTLE — تولید آرتیکل‌های سند تسویه
-- ================================================================
CREATE   PROCEDURE [dbo].[SP_PAY2_GEN_DEED_SETTLE]
    @SET_ID  INT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @STATUS TINYINT;
    DECLARE @WS_ID  INT;
    DECLARE @EMP_ID INT;

    SELECT @STATUS = STATUS, @WS_ID = WS_ID, @EMP_ID = EMP_ID
    FROM PAY2_SETTLEMENT WHERE SET_ID = @SET_ID;

    IF @STATUS <> 2
    BEGIN
        RAISERROR(N'SP_PAY2_GEN_DEED_SETTLE: تسویه %d باید نهایی (STATUS=2) شود.', 16, 1, @SET_ID);
        RETURN;
    END;

    DECLARE @ACC_SALARY_PAY  NVARCHAR(20);
    DECLARE @ACC_INS_PAYABLE NVARCHAR(20);
    DECLARE @ACC_TAX_PAYABLE NVARCHAR(20);
    SELECT
        @ACC_SALARY_PAY  = MAX(CASE WHEN ACC_KEY='SALARY_PAYABLE' THEN ACC_CODE END),
        @ACC_INS_PAYABLE = MAX(CASE WHEN ACC_KEY='INS_PAYABLE'    THEN ACC_CODE END),
        @ACC_TAX_PAYABLE = MAX(CASE WHEN ACC_KEY='TAX_PAYABLE'    THEN ACC_CODE END)
    FROM PAY2_WORKSHOP_ACC WHERE WS_ID = @WS_ID;

    SELECT N'هزینه عیدی'        AS SHARH, EIDI     AS BED, 0        AS BES, 'COST_EIDI'    AS ACC_KEY FROM PAY2_SETTLEMENT WHERE SET_ID=@SET_ID AND EIDI     > 0
    UNION ALL
    SELECT N'هزینه حق سنوات', SANAVAT,  0, 'COST_SANAVAT'  FROM PAY2_SETTLEMENT WHERE SET_ID=@SET_ID AND SANAVAT   > 0
    UNION ALL
    SELECT N'هزینه مانده مرخصی', LEAVE_PAY, 0, 'COST_LEAVE'  FROM PAY2_SETTLEMENT WHERE SET_ID=@SET_ID AND LEAVE_PAY  > 0
    UNION ALL
    SELECT N'پرداختنی تسویه حساب',  0, CAST(EIDI+BON+LEAVE_PAY+SANAVAT+PREV_CREDIT+OTHER_INCOME-PREV_DEBIT-EIDI_TAX-LOAN_BALANCE-OTHER_DED AS BIGINT), 'SETTLE_PAYABLE' FROM PAY2_SETTLEMENT WHERE SET_ID=@SET_ID
    UNION ALL
    SELECT N'وصول مانده وام',        0, LOAN_BALANCE, 'LOAN_COLLECT'  FROM PAY2_SETTLEMENT WHERE SET_ID=@SET_ID AND LOAN_BALANCE > 0
    UNION ALL
    SELECT N'وصول بدهکاری (مساعده)', 0, PREV_DEBIT,   'ADV_COLLECT'   FROM PAY2_SETTLEMENT WHERE SET_ID=@SET_ID AND PREV_DEBIT   > 0
    UNION ALL
    SELECT N'مالیات عیدی',           0, EIDI_TAX,     @ACC_TAX_PAYABLE FROM PAY2_SETTLEMENT WHERE SET_ID=@SET_ID AND EIDI_TAX    > 0;
END;
