
-- ================================================================
-- ۳. SP_PAY2_CALC_SETTLE — محاسبه تسویه حساب پرسنل
-- ================================================================
CREATE   PROCEDURE [dbo].[SP_PAY2_CALC_SETTLE]
    @EMP_ID        INT,
    @WS_ID         INT,
    @SETTLE_DATE   BIGINT,
    @END_DATE      BIGINT,
    @PREV_CREDIT   BIGINT = 0,
    @OTHER_INCOME  BIGINT = 0,
    @OTHER_DED     BIGINT = 0,
    @CALC_BY       INT    = NULL,
    @NEW_SET_ID    INT    OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE
        @BONUS_MODE          NVARCHAR(20),
        @BONUS_CUSTOM_DAYS   INT,
        @MIN_WAGE_DAILY      BIGINT,
        @MIN_WAGE_MONTHLY    BIGINT,
        @EIDI_MIN_DAYS       INT,
        @EIDI_MAX_DAYS       INT,
        @SENIORITY_MODE      NVARCHAR(20),
        @SENIORITY_FIXED_AMT BIGINT,
        @TAX_YEAR            SMALLINT,
        @LEAVE_MINS_PER_DAY  INT;

    SELECT
        @BONUS_MODE          = MAX(CASE WHEN CFG_KEY='BONUS_MODE'          THEN CFG_VALUE END),
        @BONUS_CUSTOM_DAYS   = MAX(CASE WHEN CFG_KEY='BONUS_CUSTOM_DAYS'   THEN CAST(CFG_VALUE AS INT) END),
        @MIN_WAGE_DAILY      = MAX(CASE WHEN CFG_KEY='MIN_WAGE_DAILY'      THEN CAST(CFG_VALUE AS BIGINT) END),
        @MIN_WAGE_MONTHLY    = MAX(CASE WHEN CFG_KEY='MIN_WAGE_MONTHLY'    THEN CAST(CFG_VALUE AS BIGINT) END),
        @EIDI_MIN_DAYS       = MAX(CASE WHEN CFG_KEY='EIDI_MIN_DAYS'       THEN CAST(CFG_VALUE AS INT) END),
        @EIDI_MAX_DAYS       = MAX(CASE WHEN CFG_KEY='EIDI_MAX_DAYS'       THEN CAST(CFG_VALUE AS INT) END),
        @SENIORITY_MODE      = MAX(CASE WHEN CFG_KEY='SENIORITY_MODE'      THEN CFG_VALUE END),
        @SENIORITY_FIXED_AMT = MAX(CASE WHEN CFG_KEY='SENIORITY_FIXED_AMT' THEN CAST(CFG_VALUE AS BIGINT) END),
        @TAX_YEAR            = MAX(CASE WHEN CFG_KEY='TAX_YEAR'            THEN CAST(CFG_VALUE AS SMALLINT) END),
        @LEAVE_MINS_PER_DAY  = MAX(CASE WHEN CFG_KEY='LEAVE_MINS_PER_DAY' THEN CAST(CFG_VALUE AS INT) END)
    FROM PAY2_CONFIG
    WHERE CFG_KEY IN (
        'BONUS_MODE','BONUS_CUSTOM_DAYS','MIN_WAGE_DAILY','MIN_WAGE_MONTHLY',
        'EIDI_MIN_DAYS','EIDI_MAX_DAYS','SENIORITY_MODE','SENIORITY_FIXED_AMT',
        'TAX_YEAR','LEAVE_MINS_PER_DAY'
    );

    DECLARE
        @HIRE_DATE           BIGINT,
        @EMP_FIRST_NAME      NVARCHAR(50),
        @EMP_LAST_NAME       NVARCHAR(50);

    SELECT
        @HIRE_DATE      = HIRE_DATE,
        @EMP_FIRST_NAME = FIRST_NAME,
        @EMP_LAST_NAME  = LAST_NAME
    FROM PAY2_EMPLOYEE
    WHERE EMP_ID = @EMP_ID;

    IF @HIRE_DATE IS NULL
    BEGIN
        RAISERROR(N'SP_PAY2_CALC_SETTLE: پرسنل %d یافت نشد.', 16, 1, @EMP_ID);
        RETURN;
    END;

    DECLARE @PREV_SET_ID INT = NULL;
    DECLARE @PREV_SEN_DAYS INT = 0;

    SELECT TOP 1
        @PREV_SET_ID   = SET_ID,
        @PREV_SEN_DAYS = SENIORITY_DAYS + PREV_SENIORITY_DAYS
    FROM PAY2_SETTLEMENT
    WHERE EMP_ID = @EMP_ID AND STATUS >= 2
    ORDER BY SETTLE_DATE DESC;

    DECLARE @HIRE_YEAR   INT = @HIRE_DATE / 10000;
    DECLARE @HIRE_MONTH  INT = (@HIRE_DATE % 10000) / 100;
    DECLARE @HIRE_DAY    INT = @HIRE_DATE % 100;
    DECLARE @END_YEAR    INT = @END_DATE / 10000;
    DECLARE @END_MONTH   INT = (@END_DATE % 10000) / 100;
    DECLARE @END_DAY     INT = @END_DATE % 100;

    DECLARE @SENIORITY_DAYS INT =
        (@END_YEAR * 365) + (@END_MONTH * 30) + @END_DAY
        - (@HIRE_YEAR * 365) - (@HIRE_MONTH * 30) - @HIRE_DAY
        - @PREV_SEN_DAYS;

    IF @SENIORITY_DAYS < 0 SET @SENIORITY_DAYS = 0;

    DECLARE @SENIORITY_YEARS  DECIMAL(6,2) = CAST(@SENIORITY_DAYS AS DECIMAL(10,2)) / 365.0;
    DECLARE @SENIORITY_FULL   INT           = @SENIORITY_DAYS / 365;
    DECLARE @SENIORITY_REMAIN INT           = @SENIORITY_DAYS % 365;

    DECLARE @LAST_DEC_ID  INT;
    SELECT TOP 1 @LAST_DEC_ID = DEC_ID
    FROM PAY2_DECREE
    WHERE EMP_ID = @EMP_ID AND IS_CONFIRMED = 1
      AND EFF_FROM <= @SETTLE_DATE
      AND (EFF_TO IS NULL OR EFF_TO >= @SETTLE_DATE)
    ORDER BY EFF_FROM DESC;

    DECLARE @LAST_SALARY BIGINT = 0;
    SELECT @LAST_SALARY = ISNULL(SUM(DL.AMOUNT), 0)
    FROM PAY2_DECREE_LINE DL
    INNER JOIN PAY2_ITEM_DEF ID ON DL.ITEM_ID = ID.ITEM_ID
    WHERE DL.DEC_ID = @LAST_DEC_ID
      AND ID.ITEM_TYPE = 1
      AND ID.INS_SUBJECT = 1;

    DECLARE @LAST_DAILY BIGINT = @LAST_SALARY / 30;
    IF @LAST_DAILY < @MIN_WAGE_DAILY SET @LAST_DAILY = @MIN_WAGE_DAILY;

    DECLARE @EIDI BIGINT = 0;
    DECLARE @EIDI_DAYS INT;
    DECLARE @DAYS_THIS_YEAR INT = CASE WHEN @SENIORITY_DAYS >= 365 THEN 365 ELSE @SENIORITY_DAYS END;

    IF @DAYS_THIS_YEAR < @EIDI_MIN_DAYS
        SET @EIDI = 0;
    ELSE
    BEGIN
        SET @EIDI_DAYS = CASE
            WHEN @DAYS_THIS_YEAR >= @EIDI_MAX_DAYS THEN @EIDI_MAX_DAYS
            ELSE @EIDI_MIN_DAYS
        END;

        IF @BONUS_MODE = 'MIN_WAGE'
        BEGIN
            DECLARE @EIDI_BASE BIGINT = CASE WHEN @LAST_SALARY < @MIN_WAGE_MONTHLY THEN @LAST_SALARY ELSE @MIN_WAGE_MONTHLY END;
            SET @EIDI = @EIDI_BASE / 30 * @EIDI_DAYS;
        END;
        ELSE IF @BONUS_MODE = 'ACTUAL'
            SET @EIDI = @LAST_DAILY * @EIDI_DAYS;
        ELSE IF @BONUS_MODE = 'CUSTOM'
        BEGIN
            SET @EIDI_DAYS = ISNULL(@BONUS_CUSTOM_DAYS, 60);
            SET @EIDI = @LAST_DAILY * @EIDI_DAYS;
        END;
    END;

    DECLARE @EIDI_TAX BIGINT = 0;
    DECLARE @EIDI_MIN_AMT BIGINT = @MIN_WAGE_DAILY * @EIDI_MIN_DAYS;
    IF @EIDI > @EIDI_MIN_AMT
    BEGIN
        DECLARE @EIDI_TAXABLE BIGINT = (@EIDI - @EIDI_MIN_AMT) * 12;
        SET @EIDI_TAX = [dbo].[FN_PAY2_CALC_TAX](@EIDI_TAXABLE, @TAX_YEAR) / 12;
    END;

    DECLARE @SANAVAT BIGINT = 0;
    IF @SENIORITY_MODE = 'LAST_SAL'
    BEGIN
        SET @SANAVAT = @LAST_SALARY * @SENIORITY_FULL + CAST(@LAST_SALARY * @SENIORITY_REMAIN / 365.0 AS BIGINT);
    END;
    ELSE IF @SENIORITY_MODE = 'DAILY'
        SET @SANAVAT = @LAST_DAILY * 30 * @SENIORITY_FULL + CAST(@LAST_DAILY * @SENIORITY_REMAIN AS BIGINT);
    ELSE IF @SENIORITY_MODE = 'FIXED'
        SET @SANAVAT = ISNULL(@SENIORITY_FIXED_AMT, 0) * @SENIORITY_FULL;

    DECLARE @LEAVE_BAL_MIN  INT = 0;
    DECLARE @LEAVE_BAL_DAYS_CALC DECIMAL(5,2) = 0;
    SELECT @LEAVE_BAL_MIN = ISNULL(SUM(BALANCE_MIN), 0)
    FROM PAY2_LEAVE_BAL
    WHERE EMP_ID = @EMP_ID;

    IF @LEAVE_BAL_MIN < 0 SET @LEAVE_BAL_MIN = 0;
    SET @LEAVE_BAL_DAYS_CALC = CAST(@LEAVE_BAL_MIN AS DECIMAL(10,2)) / @LEAVE_MINS_PER_DAY;

    DECLARE @LEAVE_DAILY BIGINT = @LAST_SALARY / 26;
    DECLARE @LEAVE_PAY   BIGINT = CAST(@LEAVE_BAL_DAYS_CALC * @LEAVE_DAILY AS BIGINT);

    DECLARE @BON_SETTLE BIGINT = 0;
    SELECT @BON_SETTLE = ISNULL(
        (SELECT TOP 1 DL.AMOUNT * @SENIORITY_FULL
         FROM PAY2_DECREE_LINE DL
         INNER JOIN PAY2_ITEM_DEF ID ON DL.ITEM_ID = ID.ITEM_ID
         WHERE DL.DEC_ID = @LAST_DEC_ID AND ID.ITEM_CODE = 'GROCERY')
    , 0);

    DECLARE @LOAN_BALANCE_TOT BIGINT = 0;
    SELECT @LOAN_BALANCE_TOT = ISNULL(SUM(BALANCE), 0)
    FROM V_PAY2_LOAN_BALANCE
    WHERE EMP_ID = @EMP_ID;

    DECLARE @PREV_DEBIT BIGINT = 0;

    INSERT INTO PAY2_SETTLEMENT (
        EMP_ID, WS_ID, SETTLE_DATE, HIRE_DATE, END_DATE,
        SENIORITY_DAYS, SENIORITY_YEARS, LAST_SALARY, LAST_DAILY,
        PREV_SET_ID, PREV_SENIORITY_DAYS, LEAVE_BAL_MIN, LEAVE_BAL_DAYS,
        EIDI, BON, LEAVE_PAY, SANAVAT, PREV_CREDIT, OTHER_INCOME,
        PREV_DEBIT, EIDI_TAX, LOAN_BALANCE, OTHER_DED,
        STATUS, CALC_METHOD, CREATED_BY
    )
    VALUES (
        @EMP_ID, @WS_ID, @SETTLE_DATE, @HIRE_DATE, @END_DATE,
        @SENIORITY_DAYS, @SENIORITY_YEARS, @LAST_SALARY, @LAST_DAILY,
        @PREV_SET_ID, @PREV_SEN_DAYS, @LEAVE_BAL_MIN, @LEAVE_BAL_DAYS_CALC,
        @EIDI, @BON_SETTLE, @LEAVE_PAY, @SANAVAT, @PREV_CREDIT, @OTHER_INCOME,
        @PREV_DEBIT, @EIDI_TAX, @LOAN_BALANCE_TOT, @OTHER_DED,
        1,
        (
            N'{"bonus_mode":"' + @BONUS_MODE + N'"'
            + N',"seniority_mode":"' + @SENIORITY_MODE + N'"'
            + N',"seniority_days":' + CAST(@SENIORITY_DAYS AS NVARCHAR)
            + N',"leave_bal_min":' + CAST(@LEAVE_BAL_MIN AS NVARCHAR)
            + N',"tax_year":' + CAST(@TAX_YEAR AS NVARCHAR) + N'}'
        ),
        @CALC_BY
    );

    SET @NEW_SET_ID = SCOPE_IDENTITY();

    UPDATE PAY2_EMPLOYEE SET FIRE_DATE = @END_DATE, IS_ACTIVE = 0
    WHERE EMP_ID = @EMP_ID AND FIRE_DATE IS NULL;

    PRINT N'SP_PAY2_CALC_SETTLE — موفق. SET_ID = ' + CAST(@NEW_SET_ID AS NVARCHAR);
END;
