CREATE PROCEDURE [dbo].[UNION_ALL]
AS
INSERT INTO DEAD_DTL_PRINT (DATE_S, SHARH_S, N_S, HES, TNUMBER, NUMBER, HNAME, TDETA_HES_NAME, DETA_HES_NAME, TOTA_HES_NAME, N_KOL, BED, BES, SHARH, kk, BASE, RADIF, GR) 
SELECT DEAD_DTL_PRINT2.DATE_S, DEAD_DTL_PRINT2.SHARH_S, DEAD_DTL_PRINT2.N_S, DEAD_DTL_PRINT2.HES, DEAD_DTL_PRINT2.TNUMBER, DEAD_DTL_PRINT2.NUMBER, DEAD_DTL_PRINT2.HNAME, DEAD_DTL_PRINT2.TDETA_HES_NAME, DEAD_DTL_PRINT2.DETA_HES_NAME, DEAD_DTL_PRINT2.TOTA_HES_NAME, DEAD_DTL_PRINT2.N_KOL, DEAD_DTL_PRINT2.BED, DEAD_DTL_PRINT2.BES, DEAD_DTL_PRINT2.SHARH, DEAD_DTL_PRINT2.kk, DEAD_DTL_PRINT2.BASE, DEAD_DTL_PRINT2.RADIF, DEAD_DTL_PRINT2.GR
FROM DEAD_DTL_PRINT2
