Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub Command_Visitor_Click()
        Call scrolff2(10, 1)

End Sub

Private Sub Command2_Click()
        scrolff (10)

End Sub

Private Sub Label36_Click()
     DoCmd.RunMacro "FACTORS.VISITROUT"

End Sub

Private Sub Label50_Click()
        DoCmd.RunMacro "FACTORS.KHCUST"

End Sub

Private Sub Label54_Click()
    Call scrolff2(10, 1)

End Sub

Private Sub P10E3_Click()
    DoCmd.RunMacro "FACTORS.RAAS"

End Sub

Private Sub P11E3_Click()
    DoCmd.RunMacro "FACTORS.SEFARESH"

End Sub

Private Sub P12E3_Click()
    DoCmd.RunMacro "FACTORS.FACTFRSA"

End Sub

Private Sub P13E3_Click()
    DoCmd.RunMacro "CHEK.MONCHP"

End Sub

Private Sub P14E3_Click()
    DoCmd.RunMacro "CHEK.CHKPLIST"

End Sub

Private Sub P15E3_Click()
    DoCmd.RunMacro "CHEK.PCHSS"

End Sub

Private Sub P16E3_Click()
    DoCmd.RunMacro "CHEK.FPV"

End Sub

Private Sub P17E3_Click()
    DoCmd.RunMacro "CHEK.RCHEKP"

End Sub

Private Sub P18E3_Click()
    DoCmd.OpenForm "board_hes9"

End Sub

Private Sub P19E3_Click()
    DoCmd.RunMacro "FACTORS.FROOSHDAY"

End Sub

Private Sub P1E3_Click()
    DoCmd.RunMacro "FACTORS.PFACTFR"

End Sub

Private Sub P20E3_Click()
        DoCmd.RunMacro "FACTORS.FKHAREDAY"

End Sub

Private Sub P21E3_Click()
        DoCmd.RunMacro "FACTORS.FROOSHDAY2"

End Sub

Private Sub P22E3_Click()
     DoCmd.RunMacro "FACTORS.CROSS"

End Sub

Private Sub P23E3_Click()
     DoCmd.RunMacro "FACTORS.CFRALL"

End Sub

Private Sub P24E3_Click()
     DoCmd.RunMacro "FACTORS.CKRALL"

End Sub

Private Sub P25E3_Click()
     DoCmd.RunMacro "FACTORS.AMFDAY"

End Sub

Private Sub P26E3_Click()
     DoCmd.RunMacro "FACTORS.FLIST"

End Sub

Private Sub P27E3_Click()
     DoCmd.RunMacro "FACTORS.KLIST"

End Sub

Private Sub Label56_Click()
        Call scrolff2(10, 2)
End Sub

Private Sub P28E3_Click()
    DoCmd.RunMacro "FACTORS.VISITDEV"

End Sub

Private Sub P29E3_Click()
        DoCmd.RunMacro "FACTORS.VISITKAL"

End Sub

Private Sub P2E3_Click()
        DoCmd.RunMacro "FACTORS.FACTFR"

End Sub

Private Sub P30E3_Click()
        DoCmd.RunMacro "FACTORS.VISITKALMA"

End Sub

Private Sub P31E3_Click()
     DoCmd.RunMacro "FACTORS.LVBP"

End Sub

Private Sub P32E3_Click()
     DoCmd.RunMacro "FACTORS.VISITONE"

End Sub

Private Sub P33E3_Click()
     DoCmd.RunMacro "FACTORS.VISITOR"

End Sub

Private Sub P34E3_Click()
     DoCmd.RunMacro "FACTORS.VISITROUT"

End Sub

Private Sub P35E3_Click()
     DoCmd.RunMacro "FACTORS.VISIT_DAY"

End Sub

Private Sub P36E3_Click()
     DoCmd.RunMacro "FACTORS.VISIT_POR"

End Sub

Private Sub P37E3_Click()
    DoCmd.RunMacro "FACTORS.VISITGOL"

End Sub

Private Sub P38E3_Click()
    DoCmd.RunMacro "FACTORS.VISITGOLMON"

End Sub

Private Sub P39E3_Click()
    DoCmd.RunMacro "FACTORS.VISITGOLMONG"

End Sub

Private Sub P3E3_Click()
        DoCmd.RunMacro "FACTORS.FACTBFR"

End Sub

Private Sub P40E3_Click()
    DoCmd.RunMacro "FACTORS.VISITGOLMONGR"

End Sub

Private Sub P41E3_Click()
    DoCmd.RunMacro "FACTORS.VISIT_MAS"

End Sub

Private Sub P42E3_Click()
    DoCmd.RunMacro "FACTORS.VISITGOLMONR"

End Sub

Private Sub P43E3_Click()
    DoCmd.RunMacro "FACTORS.tozied"

End Sub

Private Sub P44E3_Click()
    DoCmd.RunMacro "FACTORS.HBGHB"

End Sub

Private Sub P45E3_Click()
        DoCmd.RunMacro "FACTORS.FRCUST"

End Sub

Private Sub P46E3_Click()
        DoCmd.RunMacro "FACTORS.FASLIBR"

End Sub

Private Sub P47E3_Click()
        DoCmd.RunMacro "FACTORS.FASLIKHBR"

End Sub

Private Sub P48E3_Click()
        DoCmd.RunMacro "FACTORS.KHCUST"

End Sub

Private Sub P49E3_Click()
        DoCmd.RunMacro "FACTORS.KHLS"

End Sub

Private Sub P4E3_Click()
     DoCmd.RunMacro "FACTORS.FKHAD"

End Sub

Private Sub P50E3_Click()
        DoCmd.RunMacro "FACTORS.LFACT"

End Sub

Private Sub P5E3_Click()
     DoCmd.RunMacro "FACTORS.FACTKH"

End Sub

Private Sub P6E3_Click()
     DoCmd.RunMacro "FACTORS.FACTBKH"

End Sub

Private Sub P7E3_Click()
     DoCmd.RunMacro "FACTORS.FACTKHSA"

End Sub

Private Sub P8E3_Click()
     DoCmd.RunMacro "FACTORS.MOS"

End Sub

Private Sub P9E3_Click()
     DoCmd.RunMacro "FACTORS.MFACTFR"

End Sub
