Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database


Private Sub Label35_Click()
    Call scrolff2(11, 1)

End Sub

Private Sub P10E3_Click()
    DoCmd.RunMacro "CHEK.CHVBV"

End Sub

Private Sub P11E3_Click()
    DoCmd.RunMacro "CHEK.CHVBVP"

End Sub

Private Sub P12E3_Click()
    DoCmd.RunMacro "CHEK.CHPRN"

End Sub

Private Sub P13E3_Click()
    DoCmd.RunMacro "CHEK.TCHEK"

End Sub

Private Sub P14E3_Click()
    DoCmd.RunMacro "CHEK.FORMAT"

End Sub

Private Sub P15E3_Click()
    DoCmd.RunMacro "CHEK.CHKP"

End Sub

Private Sub P16E3_Click()
    DoCmd.RunMacro "CHEK.FVP"

End Sub

Private Sub P17E3_Click()
    DoCmd.RunMacro "CHEK.RCHEKP"

End Sub

Private Sub P18E3_Click()
    DoCmd.OpenForm "board_hes9"

End Sub

Private Sub P1E3_Click()
    DoCmd.RunMacro "CHEK.VBP"

End Sub

Private Sub P2E3_Click()
        DoCmd.RunMacro "CHEK.CHKB"

End Sub

Private Sub P3E3_Click()
        DoCmd.RunMacro "CHEK.CHAPCHEK"

End Sub

Private Sub P4E3_Click()
     DoCmd.RunMacro "CHEK.CHKM"

End Sub

Private Sub P5E3_Click()
     DoCmd.RunMacro "CHEK.SERIAL"

End Sub

Private Sub P6E3_Click()
     DoCmd.RunMacro "CHEK.DCHS"

End Sub

Private Sub P7E3_Click()
     DoCmd.RunMacro "CHEK.PCHS"

End Sub

Private Sub P9E3_Click()
     DoCmd.RunMacro "CHEK.GBEHESAB"

End Sub

Private Sub P8E3_Click()
     DoCmd.RunMacro "CHEK.BEHESAB"

End Sub
