Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub Command2_Click()
        scrolff (12)

End Sub

Private Sub P10E3_Click()
    DoCmd.RunMacro "FACTORS.DARKHRLIS"

End Sub

Private Sub P11E3_Click()
    DoCmd.RunMacro "FACTORS.VISITGOLMON"

End Sub

Private Sub P12E3_Click()
    DoCmd.RunMacro "FACTORS.VISITGOLMONG"

End Sub

Private Sub P13E3_Click()
    DoCmd.RunMacro "FACTORS.VISITGOLMONGR"

End Sub

Private Sub P14E3_Click()
    DoCmd.RunMacro "FACTORS.VISIT_MAS"

End Sub

Private Sub P15E3_Click()
    DoCmd.RunMacro "FACTORS.VISITGOLMONR"

End Sub

Private Sub P16E3_Click()
    DoCmd.RunMacro "FACTORS.RDFTKHFRA4"

End Sub

Private Sub P17E3_Click()
    DoCmd.RunMacro "FACTORS.HBGHB"

End Sub

Private Sub P18E3_Click()
    DoCmd.RunMacro "FACTORS.VISITGOLMONR"

End Sub

Private Sub P1E3_Click()
        DoCmd.RunMacro "ANABAR.HAVL"

End Sub

Private Sub P2E3_Click()
        DoCmd.RunMacro "ANABAR.RASID"

End Sub

Private Sub P3E3_Click()
        DoCmd.RunMacro "ANABAR.ESWAP"

End Sub

Private Sub P4E3_Click()
        DoCmd.RunMacro "ANABAR.RBRFR"

End Sub

Private Sub P5E3_Click()
        DoCmd.RunMacro "ANABAR.SAYERHAV"

End Sub

Private Sub P6E3_Click()
        DoCmd.RunMacro "FACTORS.DARKHR"

End Sub

Private Sub P7E3_Click()
        DoCmd.RunMacro "ANABAR.ANGD"

End Sub

Private Sub P8E3_Click()
        DoCmd.OpenForm "BOARD_HES20"

End Sub

Private Sub P9E3_Click()
     DoCmd.RunMacro "ANABAR.SEARCHMO"

End Sub
