Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub Command2_Click()
        scrolff (3)
End Sub

Private Sub P10E3_Click()
    DoCmd.RunMacro "SALARY.FISH1"

End Sub

Private Sub P11E3_Click()
    DoCmd.RunMacro "SALARY.FISH2"

End Sub

Private Sub P12E3_Click()
    DoCmd.RunMacro "SALARY.LISTBIM"

End Sub

Private Sub P13E3_Click()
    DoCmd.RunMacro "SALARY.DISK"

End Sub

Private Sub P14E3_Click()
    DoCmd.RunMacro "SALARY.LISTMAL"

End Sub

Private Sub P15E3_Click()
    DoCmd.RunMacro "SALARY.DISKM"

End Sub

Private Sub P16E3_Click()
    DoCmd.RunMacro "SALARY.EP"

End Sub

Private Sub P17E3_Click()
    DoCmd.RunMacro "SALARY.TASV"

End Sub

Private Sub P1E3_Click()
    DoCmd.RunMacro "SALARY.PERS"

End Sub

Private Sub P2E3_Click()
        DoCmd.RunMacro "SALARY.HOKM"

End Sub

Private Sub P3E3_Click()
        DoCmd.RunMacro "SALARY.MORAKH"

End Sub

Private Sub P4E3_Click()
     DoCmd.RunMacro "SALARY.GHARA"

End Sub

Private Sub P5E3_Click()
     DoCmd.RunMacro "SALARY.SAND"

End Sub

Private Sub P6E3_Click()
     DoCmd.RunMacro "SALARY.VAM"

End Sub

Private Sub P7E3_Click()
     DoCmd.RunMacro "SALARY.WORK"

End Sub

Private Sub P8E3_Click()
     DoCmd.RunMacro "SALARY.WOKPER"

End Sub

Private Sub P9E3_Click()
     DoCmd.RunMacro "SALARY.SALAR"

End Sub
