Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub Command2_Click()
        scrolff (8)
End Sub

Private Sub Label6_Click()

End Sub

Private Sub p1e4_Click()
        DoCmd.RunMacro "PROG.PROG"

End Sub

Private Sub p2e4_Click()
        DoCmd.RunMacro "nemudar.CT4"

End Sub

Private Sub P3E4_Click()
        DoCmd.RunMacro "nemudar.CT5"

End Sub

Private Sub P4E4_Click()
        DoCmd.RunMacro "nemudar.CH1"

End Sub

Private Sub P5E4_Click()
        DoCmd.RunMacro "nemudar.CT1"

End Sub

Private Sub P6E4_Click()
        DoCmd.RunMacro "nemudar.CT2"

End Sub

Private Sub P7E4_Click()
        DoCmd.RunMacro "nemudar.CT3"

End Sub

Private Sub P8E4_Click()
        DoCmd.RunMacro "PAZTAM.PTM"

End Sub

Private Sub P9E4_Click()
        DoCmd.RunMacro "PAZTAM.PKINCO"
End Sub
