Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub Command0_Click()



'Dim appexcel As Excel.Application

'Dim wb As Workbook

'Set appexcel = CreateObject("excel.application")

'Set wb = appexcel.Workbooks.Open("C:\Users\my-pc\Desktop\softpluse.xlsx")

'appexcel.Visible = True
'
'End Sub
End Sub
