Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub D31_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D30_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D29_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D28_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D27_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D26_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D25_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D24_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D23_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D22_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D21_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D20_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D19_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D18_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D17_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D16_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D15_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D14_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D13_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D12_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D11_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D10_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D9_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D8_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D7_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D6_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D5_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D4_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D3_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D2_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub
Private Sub D1_AfterUpdate()
                   On Error Resume Next
  Me.ZD = D31 + D30 + D29 + D28 + D27 + D26 + D25 + D24 + D23 + D22 + D21 + D20 + D19 + D18 + D17 + D16 + D15 + D14 + D13 + D12 + D11 + d10 + d9 + d8 + d7 + d6 + d5 + d4 + d3 + d2 + d1
End Sub

Private Sub DEPART_NotInList(NewData As String, Response As Integer)
  If Me.DEPART.Text = "-" Or Me.DEPART.Text = "+" Then
'     DoCmd.OpenForm "SERCHKJOB"
       DoCmd.OpenForm "SERSNDTAF1", , , , , , "43"
       Response = acDataErrContinue
    Else
        Me.DEPART = NewData
  End If
  Response = acDataErrContinue
End Sub

Private Sub Form_Current()
                   On Error Resume Next
  Call SETSECURITYSUB("KAR_HEAD", Me.NAME, "KARB", 3)
End Sub

Private Sub Form_Error(DataErr As Integer, Response As Integer)
                        On Error Resume Next: errdetector (DataErr)
   Response = acDataErrContinue: DoCmd.RunMacro "stop"
End Sub

Private Sub Form_Open(CANCEL As Integer)
 If MID(Forms![BASEKNOW]![OPTIONSS], 30, 1) <> "5" Then
    DEPART.RowSource = "SELECT HEAD_MANF.FNUMB, ISNULL(HEAD_MANF.NAMES, STUF_DEF.NAME) AS NAM, HEAD_MANF.CODE AS CODE FROM STUF_DEF RIGHT OUTER JOIN HEAD_MANF ON STUF_DEF.CODE = HEAD_MANF.CODE"
    DEPART.Requery
 End If

End Sub
