Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub Form_Open(CANCEL As Integer)
  Me.TAR = "با فعال كردن سيزدهمين 5 در فيلد كد تنظيمات سيستم سرفصهاي فروش و برگشت فروش و تخفيفات فروش را بصورت فروش خالص با معينهاي فروش - تخفيفات فروش - برگشت فروش تعريف مي نمايد" & Chr(13) & Me.TAR
  Me.TAR = "با دابل كليك كردن روي شماره فني در ليست موجودي كالا به تفكيك انبار موجودي را بر اساس كدينگ شماره فني ارائه مي كند" & Chr(13) & Me.TAR
End Sub
